### ISSUE TITLE
Update pep.xml schema

### ISSUE THREAD

**Issue by prvst** [Nesvilab/MSFragger#1]
MSFragger is following the pep.XML schema 1.18 from 2015. The latest version 1.22 is from 2017 and it contains diferences that can cause problems during parsing. Some of the corrections we see PeptideProphet applying in the beginning of the analysis are not necessary when using the newest schema.

The pep.xml shcemas can be found [here](https://sourceforge.net/p/sashimi/code/HEAD/tree/trunk/trans_proteomic_pipeline/schema/).

**Comment by fcyu** [comment]
Updated to 1.22 since version 3.2.
