### ISSUE TITLE
Non-centroid MS2 spectra

### ISSUE THREAD

**Issue by ekawaler** [Nesvilab/MSFragger#100]
I'm getting this error when running MSFragger (as part of the Philosopher pipeline):

"There are non-centroid MS2 spectra. Please prepare the spectral file with peak picking."

My spectral files have been prepared with peak picking and should be centroided. I've been working with CPTAC data, and most of these spectra have run with no problem. (The dataset where I'm encountering this problem is the prospective colon cancer dataset, and I'm finding it in multiple MS runs in this dataset.) 

Has anyone else encountered this issue before? How does MSFragger do its centroiding check? I'm wondering if maybe there's an mzML header item I'm missing.

**Comment by fcyu** [comment]
Can you send the mzML with the warning to us?

Thanks,

Fengchao

**Comment by ekawaler** [comment]
Sure - it's probably going to be too big to attach here, is there an email address I should send it to?

**Comment by fcyu** [comment]
Here is the link https://umich.app.box.com/f/1fceaaf3b4e04288a5a3ba935a364b81 to upload.

Thanks,

Fengchao

**Comment by ekawaler** [comment]
File now uploaded! Thank you in advance for your help!

**Comment by fcyu** [comment]
I think your mzML is not centroided. Following is a tag from one MS2 scan.
```xml
<cvParam cvRef="MS" accession="MS:1000128" name="profile spectrum" value=""/>
```

Best,

Fengchao

**Comment by ekawaler** [comment]
Interesting. This was converted from raw with the following command:

msconvert /path/CO/01CPTAC_COprospective_W_PNNL_20170123_B1S2_f01.raw -o /path/CO/mzML --filter "peakPicking true -1"

...am I doing something very obviously wrong?

**Comment by fcyu** [comment]
I think it should be `--filter "peakPicking true 1-`

Best,

Fengchao

**Comment by ekawaler** [comment]
Ah yeah that was the wrong command, sorry - it was [1-2], not -1, if that makes a difference

**Comment by fcyu** [comment]
It makes a big difference, actually. You can use msconvert GUI if it is available to you.

**Comment by ekawaler** [comment]
Okay - it looks like I thought I had changed all of my scripts to run with the correct version of the command, but I think I had missed a few. My fault entirely. Thank you for your help!
