### ISSUE TITLE
Accepted file formats for MSFragger 

### ISSUE THREAD

**Issue by ashwinkallor** [Nesvilab/MSFragger#102]
Hi,

I've just started using MSFragger. Due to certain logistic issues, converting to mzml has been a challenge for me. So, in this regard, may I ask if it is possible to perform Open Search using raw files?  Your manual clearly mentions mzml, mzxml etc as acceptable formats but is there a workaround that I could use to input raw files as well. Your help would be most appreciated. 

Thanks!
Ashwin

**Comment by ashwinkallor** [comment]
I am using MSFragger 3.1.1.

**Comment by hayse1** [comment]
Hi Ashwin, you should have no issue performing open search workflows with Thermo .raw files. From the compatibility table in the [main FragPipe tutorial](https://msfragger.nesvilab.org/tutorial_fragpipe.html), label-based quantification and spectral library generation are the only steps that won't work with .raw files.

Sarah

**Comment by fcyu** [comment]
Hi Ashwin,

You may need to install [Mono ](https://www.mono-project.com/download/stable/#download-lin)if you are using LInux.

Best,

Fengchao

**Comment by ashwinkallor** [comment]
Thanks so much guys. Let me try this and revert to you. I will close this issue after that.

**Comment by ashwinkallor** [comment]
**Update:**

Hi guys, 
I tried running my raw files but unfortunately I keep getting an error as follows: 
"Did not get port information from server output within timeout".

This error is shown 3 times, before concluding with "Failed in checking <filename>. Could not get ThermoIndex".

Is this caused by a connection issue? Or is there something wrong with my raw file?

Thanks,
Ashwin

**Comment by fcyu** [comment]
Hi Ashwin,

This is because your computer prevent MSFragger from communicating with Thermo's library. I think there is not much we can do about it.

Best,

Fengchao

**Comment by guoci** [comment]
@ashwinkallor Can you run the following on the command line
`mono <PATH TO YOUR ext DIRECTORY>/thermo/BatmassIoThermoServer.exe`
and show me the output?

**Comment by ashwinkallor** [comment]
Hi @guoci , here is the output:

![image](https://user-images.githubusercontent.com/55626622/95721451-3b9e8300-0c90-11eb-9d6d-eaacfa83b201.png)

**Comment by guoci** [comment]
@ashwinkallor it seems the server is working.
Can you try this on a different computer?

**Comment by ashwinkallor** [comment]
That will unfortunately not be possible in the present circumstances. I will close this issue now and re-open it later if required once I manage to try the procedure again. Thanks guys for all your help.
