### ISSUE TITLE
MSFragger 3.1.1 on Linux couldn't find optimal parameters after mass calibration 

### ISSUE THREAD

**Issue by merbllab** [Nesvilab/MSFragger#103]
Hi,
I run MSFragger 3.1.1 on linux system with calibrate_mass = 2. it calibrate the masses but didn't find any optimal parameters. when I run MSFragger through  FragPipe on the same database with same params it successfully allocate optimal parameters. 
this is how it looks in FragPipe:
*********************MASS CALIBRATION AND PARAMETER OPTIMIZATION*******************
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
 001 |   5.00   2.40 |  -0.01   2.00 |   1.77   2.85 |  -0.08   3.25  
 002 |   4.55   1.67 |   0.11   1.39 |   1.67   3.30 |  -0.07   3.61  
-----|---------------|---------------|---------------|---------------
Finding the optimal parameters:
-------|-------|-------|-------|-------|-------|-------
  MS2  |    7  |   10  |   15  |   20  |   25  |   30  
-------|-------|-------|-------|-------|-------|-------
 Count |   2245|    947| skip rest
-------|-------|-------|-------|-------|-------|-------
-------|-------|-------|-------|-------
 Peaks | 300_0 | 200_0 | 150_1 | 100_1 
-------|-------|-------|-------|-------
 Count |   2245|   2929|   2677| skip rest
-------|-------|-------|-------|-------
-------|-------
 Int.  |    0  
-------|-------
 Count |   2736
-------|-------
-------|-------
 Rm P. |    0  
-------|-------
 Count |   2946
-------|-------
New fragment_mass_tolerance = 7 PPM
New use_topN_peaks = 200
New minimum_ratio = 0.000000
New intensity_transform = 1
New remove_precursor_peak = 0
************MASS CALIBRATION AND PARAMETER OPTIMIZATION DONE IN 9.483 MIN*********

this is how it looks like in stand alone MSFragger in linux:
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
 001 |   5.03   2.56 |   0.11   1.94 |   1.73   2.88 |  -0.15   3.24  
 002 |   4.51   1.67 |   0.25   1.33 |   1.66   3.27 |  -0.18   3.61  
-----|---------------|---------------|---------------|---------------
Finding the optimal parameters:
-------|-------|-------|-------|-------|-------|-------
  MS2  |    7  |   10  |   15  |   20  |   25  |   30  
-------|-------|-------|-------|-------|-------|-------
 Count |      0|      0|      0|      0|      0|      0
-------|-------|-------|-------|-------|-------|-------
-------|-------|-------|-------|-------
 Peaks | 300_0 | 200_0 | 150_1 | 100_1 
-------|-------|-------|-------|-------
 Count |      0|      0|      0|      1
-------|-------|-------|-------|-------
-------|-------
 Int.  |    0  
-------|-------
 Count |      0
-------|-------
-------|-------
 Rm P. |    0  
-------|-------
 Count |      1
-------|-------
New fragment_mass_tolerance = 20 PPM
New use_topN_peaks = 100
New minimum_ratio = 0.010000
New intensity_transform = 1
New remove_precursor_peak = 0

**full log file is attached.** 
[LOG-MSFragger_mass_calib-346894.txt](https://github.com/Nesvilab/MSFragger/files/5358921/LOG-MSFragger_mass_calib-346894.txt)

**Comment by fcyu** [comment]
I think your two searches have different parameters because the calibration measures are different.
```
-----|---------------|---------------|---------------|---------------
| MS1 (Old) | MS1 (New) | MS2 (Old) | MS2 (New)
-----|---------------|---------------|---------------|---------------
Run | Median MAD | Median MAD | Median MAD | Median MAD
001 | 5.00 2.40 | -0.01 2.00 | 1.77 2.85 | -0.08 3.25
```
vs
```
-----|---------------|---------------|---------------|---------------
| MS1 (Old) | MS1 (New) | MS2 (Old) | MS2 (New)
-----|---------------|---------------|---------------|---------------
Run | Median MAD | Median MAD | Median MAD | Median MAD
001 | 5.03 2.56 | 0.11 1.94 | 1.73 2.88 | -0.15 3.24
```

Could you send me both logs?

Thanks,

Fengchao

**Comment by merbllab** [comment]
Hi

Attached is the log of FragPipe. 

The stand-alone MSFragger log was attached in the previous mail 

Thanks

Assaf

**Comment by fcyu** [comment]
Hi Assaf,

There are some differences between two jobs:

`database_name = 2020-10-07-decoys-contam-Human_SP_27042020.fasta.fas`
vs
`database_name = 2020-10-07-decoys-contam-Human_SP_27042020.fasta-with-contaminate-with-decoy.fasta`

`min_matched_fragments = 5`
vs
`min_matched_fragments = 4`

`isotope_error = 0/1`
vs
`isotope_error = 0/1/2`

`max_variable_mods_per_peptide = 4`
vs
`max_variable_mods_per_peptide = 3`

`max_variable_mods_combinations = 5000`
vs
`max_variable_mods_combinations = 65000`

Could you please unify the parameters (using the same fragger.params) and try again?

Best,

Fengchao

**Comment by merbllab** [comment]
HI Fengchao,

 

You are right – after aligning those parameters it gave the same results. My bad – I should have notice those differences.

Thanks

Assaf

**Comment by fcyu** [comment]
Hi Assaf,

No problem!

Please feel free to contact us if there is any further questions.

Best,

Fengchao
