### ISSUE TITLE
update site down

### ISSUE THREAD

**Issue by CuypersBart** [Nesvilab/MSFragger#108]
Hi,

is it possible the update site 'https://msfragger.arsci.com/upgrader/' is down? 
The connection seems to time out.

**Comment by fcyu** [comment]
Hi @CuypersBart ,

That URL is down for maintenance. Could you please try [http://msfragger-upgrader.nesvilab.org/upgrader/](http://msfragger-upgrader.nesvilab.org/upgrader/)?

Best,

Fengchao

**Comment by CuypersBart** [comment]
Hi Fengchao,

thank you so much! That works perfectly.

Best,

Bart
