### ISSUE TITLE
MSfragger from commandline with DB-splitting option

### ISSUE THREAD

**Issue by jjGG** [Nesvilab/MSFragger#110]
Dear Developers, 

While I can now run the complete LFQ-pipeline with FragPipeGUI - I would like to run it from a script when invoking my huge-MetaproteomicsDB. 
Using the log-file from FragPipe (or "Print Commands") I can execute most commands as-is on the commandline. 
Only the python3 command when specifying the number of splits and then directly calling the MSFragger java file gives me an error. 
How do I need to properly run the MSFragger with DB-splitting option?

I tried (from the log-file) like this: 

`python3 /export/data01/FragPipe14/fragpipe/tools/msfragger_pep_split.py 4 java -jar -Dfile.encoding=UTF-8 -Xmx976G /usr/local/nesvilab/MSFragger-3.1.1/MSFragger-3.1.1.jar /scratch/j_p3635_wFragPipe/outputFromCmdLine/fragger.params /scratch/j_p3635_wFragPipe/20200904_008_autoQC4L.raw`

but I end up with the following error message on the commandline:

```
jonas@fgcz-r-033:/scratch/j_p3635_wFragPipe$ python3 /export/data01/FragPipe14/fragpipe/tools/msfragger_pep_split.py 4 java -jar -Dfile.encoding=UTF-8 -Xmx976G /usr/local/nesvilab/MSFragger-3.1.1/MSFragger-3.1.1.jar /scratch/j_p3635_wFragPipe/outputFromCmdLine/fragger.params /scratch/j_p3635_wFragPipe/20200904_008_autoQC4L.raw
**Traceback (most recent call last):
  File "/export/data01/FragPipe14/fragpipe/tools/msfragger_pep_split.py", line 47, in <module>
    params_txt = param_path.read_bytes().decode()
  File "/usr/local/lib/python3.7/pathlib.py", line 1192, in read_bytes
    with self.open(mode='rb') as f:
  File "/usr/local/lib/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
  File "/usr/local/lib/python3.7/pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '-Dfile.encoding=UTF-8'**
```

Thanks for looking into it & best regards- 
jonas

**Comment by guoci** [comment]
@jjGG Please try:
`python3 /export/data01/FragPipe14/fragpipe/tools/msfragger_pep_split.py 4 "java -jar -Dfile.encoding=UTF-8 -Xmx976G" /usr/local/nesvilab/MSFragger-3.1.1/MSFragger-3.1.1.jar /scratch/j_p3635_wFragPipe/outputFromCmdLine/fragger.params /scratch/j_p3635_wFragPipe/20200904_008_autoQC4L.raw`

**Comment by jjGG** [comment]
Hei @guoci , great.. this seems to work.. thanks for answering my stoopid/trivial question. 

One more question: For a fasta-db of 136gb how many splits would you recommend to start with? (Alexey commented that there should not be more than 2 billions of theoretical peptides.. how can I estimate this?)

Best regards - jonas

**Comment by fcyu** [comment]
Hi @jjGG ,

I don't think there is any good rule to estimate required splits accurately. We normally try different numbers from small to large until everything runs well. For your case, I guess the number would be something more than 100....

Best,

Fengchao

**Comment by jjGG** [comment]
@fcyu - great - thanks - I close the issue

**Comment by anesvi** [comment]
Fengchao, Guo Ci, any way to estimate that?
I think it is hard, because the database is probably quite redundant. So we cannot take what we know for a regular human database and scale.
I would start with 10. If crashes, double to 20. Etc.
If works with 10, see what the number of peptides is for each slice, and consider reducing next time
Alexey
