### ISSUE TITLE
download database through Fragpipe

### ISSUE THREAD

**Issue by ChennanRU2019** [Nesvilab/MSFragger#113]
When i try to download the database through FragPipe GUI, i got a message like below:

[message.docx](https://github.com/Nesvilab/MSFragger/files/5466034/message.docx)

Can anyone help me solve this issue? Thanks a lot!

**Comment by fcyu** [comment]
Thanks for your interest in our tools. Are you using the latest version? Could you please restart FragPipe and try again? If the error still happens, could you please take a screenshot of the command window (the one starts after clicking 'fragpipe' or 'fragpipe.bat')?

Thanks,

Fengchao

**Comment by ChennanRU2019** [comment]
Hi Fengchao,

I solved the issue by changing the file path. I don’t know the reason, but it works now.

Thanks a lot.

Best,
Nan


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by fcyu** [comment]
You are welcome.
