### ISSUE TITLE
TSV Writing With Split Database

### ISSUE THREAD

**Issue by BadAtComputerGuy** [Nesvilab/MSFragger#116]
I'm currently having an issue writing the output of MSFragger to TSV. The files I am using work fine when writing to pepXML. When I run without splitting the database, TSV writing works just fine. However, whenever I use the split database function (which I need for some large databases) I consistently see the following error:

`concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ch208774/anaconda3/envs/fraggerenv/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/data/Kyle/FragPipe14.0/fragpipe/tools/msfragger_pep_split.py", line 315, in write_pepxml
    pepxml_header, = set([get_pepxml_header(tempdir_part / (infile.stem + '.' + output_file_extension)) for tempdir_part in tempdir_parts])
  File "/data/Kyle/FragPipe14.0/fragpipe/tools/msfragger_pep_split.py", line 315, in <listcomp>
    pepxml_header, = set([get_pepxml_header(tempdir_part / (infile.stem + '.' + output_file_extension)) for tempdir_part in tempdir_parts])
  File "/data/Kyle/FragPipe14.0/fragpipe/tools/msfragger_pep_split.py", line 299, in get_pepxml_header
    ret = re_pepxml_header.match(mm).group()
AttributeError: 'NoneType' object has no attribute 'group'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/Kyle/FragPipe14.0/fragpipe/tools/msfragger_pep_split.py", line 470, in <module>
    main()
  File "/data/Kyle/FragPipe14.0/fragpipe/tools/msfragger_pep_split.py", line 465, in main
    combine_results()
  File "/data/Kyle/FragPipe14.0/fragpipe/tools/msfragger_pep_split.py", line 331, in combine_results
    e.result()
  File "/home/ch208774/anaconda3/envs/fraggerenv/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/ch208774/anaconda3/envs/fraggerenv/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AttributeError: 'NoneType' object has no attribute 'group'
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stoppingMsFragger move pepxml`

I have tried Python 3.7.9 and 3.8.3 (and cannot try 3.9 as it says numpy is a required module, but is incompatible in an environment with 3.9 at the moment). Philosopher is version 3.3.12 and Fragger is 3.1.1. The database I am using for troubleshooting is a human uniprot plus decoyPYrat generated decoy database. 

Is there anything I can do get this up and running? 
Thanks in advance for your time. (And for working on MSFragger which has been awesome in all other cases!)

**Comment by guoci** [comment]
@BadAtComputerGuy please send your MSFragger pepxml files

**Comment by BadAtComputerGuy** [comment]
Hi guoci,

How can I get these to you privately?

**Comment by guoci** [comment]
@BadAtComputerGuy you can upload it to google drive and share it with me, or email to me at teog@umich.edu

**Comment by BadAtComputerGuy** [comment]
Thank you! I have sent along one of these files.

**Comment by guoci** [comment]
@BadAtComputerGuy Can you send all the `pepXML`s? The one you sent wasn't causing the problem.

**Comment by guoci** [comment]
@BadAtComputerGuy Also, please try the following modified FragPipe, if it resolves the problem, let me know.
https://drive.google.com/file/d/1cTGeh5LwAaS3Gej9EPoc5DKksNo2JkxP/view?usp=sharing

**Comment by BadAtComputerGuy** [comment]
Were you using a certain function I'm unfamiliar with to convert the pepXML to TSV directly? If that's an option, it would probably solve my problem, since writing to pepXML works fine for me. 

The issue for me was running MSFragger on my peak picked spectra and setting the output for TSV. In that case if you would like to test it, I will email you the mzML file. This file certainly causes an issue on my end, so I don't know if additional pepXML outputs will help. On the other hand if you are able to write the output to TSV, the problem is perhaps something other than MSFragger.

**Comment by guoci** [comment]
@BadAtComputerGuy This issue is not caused by a conversion of file formats.
Did the modified FragPipe work?

**Comment by BadAtComputerGuy** [comment]
Sorry I accidentally deleted that part of my response, the modified FragPipe did not work.

If the issue is not conversion of file formats why does it work when I write to pepXML and not TSV? I suppose that's what I'm confused about. If you have any recommendations for converting from the pepXML output to TSV after Fragger that would also solve my problem.

**Comment by guoci** [comment]
@BadAtComputerGuy what was the error message you got from the modified FragPipe?

**Comment by BadAtComputerGuy** [comment]
Unless I am missing something I believe it is just the same.

Here is the copy:


DONE: slice 2 of 2
['java', '-jar', '-Dfile.encoding=UTF-8', '-Xmx162G', PosixPath('/data/Kyle/FragPipe14.0/fragpipe/tools/MSFragger-3.1.1/MSFragger-3.1.1.jar'), '--generate_expect_functions', 'test_scores_histogram.tsv']
MSFragger version MSFragger-3.1.1
Batmass-IO version 1.19.5
timsdata library version timsdata-2-7-0
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 11.0.9, OpenJDK 64-Bit Server VM, Ubuntu
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ch208774/anaconda3/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/ch208774/Downloads/fragpipe/tools/msfragger_pep_split.py", line 315, in write_pepxml
    pepxml_header, = set([get_pepxml_header(tempdir_part / (infile.stem + '.' + output_file_extension)) for tempdir_part in tempdir_parts])
  File "/home/ch208774/Downloads/fragpipe/tools/msfragger_pep_split.py", line 315, in <listcomp>
    pepxml_header, = set([get_pepxml_header(tempdir_part / (infile.stem + '.' + output_file_extension)) for tempdir_part in tempdir_parts])
  File "/home/ch208774/Downloads/fragpipe/tools/msfragger_pep_split.py", line 299, in get_pepxml_header
    ret = re_pepxml_header.match(mm).group()
AttributeError: 'NoneType' object has no attribute 'group'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ch208774/Downloads/fragpipe/tools/msfragger_pep_split.py", line 470, in <module>
    main()
  File "/home/ch208774/Downloads/fragpipe/tools/msfragger_pep_split.py", line 465, in main
    combine_results()
  File "/home/ch208774/Downloads/fragpipe/tools/msfragger_pep_split.py", line 331, in combine_results
    e.result()
  File "/home/ch208774/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/ch208774/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
AttributeError: 'NoneType' object has no attribute 'group'
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stoppingMSFragger move pepxml
java -cp /home/ch208774/Downloads/fragpipe/lib/fragpipe-14.1-build5.jar com.github.chhh.utils.FileMove /mnt/Transfer/est.tsv /data/test_for_MSFragger_troubleshooting/test.tsv

~~~~~~~~~~~~~~~~~~~~
Cancelling 7 remaining tasks
Processing interrupted, stopping MSFragger move pepxml

**Comment by guoci** [comment]
@BadAtComputerGuy I do not know why you are getting this error. It seems to come from reading the MSFragger generated `pepXML`s
Can you try the FragPipe below and show me the error message?
https://drive.google.com/file/d/1vmbqRuSZ8MJL3_a7O-YG2bV_CZCYjbqa/view?usp=sharing
