### ISSUE TITLE
MsFragger updater issue?

### ISSUE THREAD

**Issue by collins-ben** [Nesvilab/MSFragger#117]
Dear MsFraggers,

I have been trying to upgrade to 3.1 for the last few days without success. I click upgrade from FragPipe, go to the upgrader tool, fill the form and select the old jar, and when I click 'Download' it spins for a while and then I get 'The connection was reset' error.

I am just wondering if there is a server issue or maybe something is wrong on my end?

Thanks a lot
Ben

**Comment by fcyu** [comment]
Hi Ben,

Sorry to hear that. I just tried and it works well. If you still cannot upgrade, could you send us your old version, and we will upgrade it for you?

Thanks,

Fengchao
