### ISSUE TITLE
Some questions about the peptidomics search format

### ISSUE THREAD

**Issue by PatrickvanZalm** [Nesvilab/MSFragger#118]
Dear MSFragger team,

I have a few questions about the Peptidomics workflow and its result files.

1.  I run my peptidomics search (non-HLA) and when looking at the combined_peptide or single peptide.tsv files I can not find any written post translational modifications in these files. They are there for the protein level. Is this a setting I am missing?

2. I recently ran some peptidomics samples on our timsTOF where I did increase the max-charge to 9 in the methods. When searching said files, I notice that all peptides are limited to a charge of 5. Is this due to the timsTOF data? I do not seem to have this problem with Orbitrap data.

3. If I want to isolate the identified proteins from my peptidomics search, can I isolate the results of the combined_peptide file and remove duplicates? I'm not completely sure if this would be appropriate because MSFragger states that no Protein FDR filter is applied.

I have attached the configurations I use in MSFragger (although I had to change it to .txt due to Github restrictions).
[Nonspecific-peptidome_Patrick2.txt](https://github.com/Nesvilab/MSFragger/files/5630213/Nonspecific-peptidome_Patrick2.txt)

Best,
Patrick

**Comment by fcyu** [comment]
Hi Patrick,

1. It shouldn't be. Could you double check?
2. MSFragger supports charges from 1 to 7. So, if the maximum charge is 5, it may be due to the data acquisition not MSFragger.
3. In peptidomics search, the default protein FDR is 100% while PSM and peptide FDR are 1%. I am not sure about your purpose of isolating the identified proteins, but the protein may have a large FDR.

Best,

Fengchao

**Comment by PatrickvanZalm** [comment]
Hi Fengchao,

Thank you for your reply.
I have indeed figured out point 1. I will have a look at #2

About #3: While I am interested in the ID'd peptides for my peptidomics search I do like to compare it with a proteomics workflow. To do so; I take:
- ProteinID column from combined_peptide file (peptidomics search).
- ProteinID column from combined_protein file (proteomics search).

I was wondering if this would be appropriate FDR-wise.

All the best,
Patrick
