### ISSUE TITLE
Problem with MSFragger: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by cesarrivera** [Nesvilab/MSFragger#119]
Hello community, I had a problem with MSFragger:
"**java.lang.OutOfMemoryError: Java heap space**"

My computer:
**Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz
32 GB RAM**

**MSfragger version: 13.0
Philosopher version: 3.3.11 (build 1601497354)
Python version: Python 3.7.6**

Global settings:
**RAM: 0 (auto)
Parallelism: 12
timsTOF LC/MS files** 

Database:
**The Human Oral Microbiome Database (All)
http://www.homd.org/ftp/genomes/PROKKA/current/faa/ALL_genomes.faa
1.9 GB, 2.8 GB (.pepindex file)**

**Can I fix it by increasing the JAVA virtual memory?
Is the base too big for my computer?**

I added my log file.

[log_2020-12-09_10-11-41.txt](https://github.com/Nesvilab/MSFragger/files/5666064/log_2020-12-09_10-11-41.txt)

Thank you very much for your help,

César Rivera
Talca, Chile

**Comment by fcyu** [comment]
Although your computer have 32 GB RAM in total, there were only about 23 GB free memory according to FragPipe. To analyze timsTOF data, we suggest having 32 GB ~64 GB free memory available.

Best,

Fengchao
