### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'D:\\prot\\exp\\control1.d'

### ISSUE THREAD

**Issue by cesarrivera** [Nesvilab/MSFragger#120]
Hello community, I had a problem with MSFragger:
"**PermissionError: [Errno 13] Permission denied: 'D:\\prot\\exp\\control1.d'**"
I added my log file.
Thank you very much for your help,
César Rivera
Talca, Chile
[log_2020-12-12_22-43-34.txt](https://github.com/Nesvilab/MSFragger/files/5684071/log_2020-12-12_22-43-34.txt)

**Comment by fcyu** [comment]
@guoci The user ran it with split database. First search and mass calibration finished, but an error thrown by the python script after that. It looks like it was thrown during copying the .d file (why copying spectral file which is large and time consuming?). Can you take a look when you have time?

Thanks,

Fengchao

**Comment by fcyu** [comment]
BTW, @cesarrivera you are using old versions of FragPipe and MSFragger. Could you please update the tools to see if the error is still there?

Thanks,

Fengchao

**Comment by cesarrivera** [comment]
OKAY. I have updated the files.
I will try again.
César.

**Comment by danielgeiszler** [comment]
Please also make sure the file is not being used by any other application.

**Comment by cesarrivera** [comment]
Hello, the file is not being used by another application. I updated all the tools, including Python.

`Version info:
FragPipe version 14.0
MSFragger version 3.1.1
Philosopher version 3.3.11 (build 1601497354)
Python  version 3.8.5`

I configured Anaconda as the link [https://msfragger.nesvilab.org/tutorial_setup_fragpipe.html](https://msfragger.nesvilab.org/tutorial_setup_fragpipe.html) says.  For that I had to install first Microsoft Visual C++, Microsoft C++ Build Tools and  Windows 10 SDK. Installation of the msproteomicstools, numpy, pandas, matplotlib, and cython packages was bug-free.

However, the option **split database** still fails.

`Traceback (most recent call last):
  File "D:\protprog\fragpipe14\tools\msfragger_pep_split.py", line 470, in <module>
    main()
  File "D:\protprog\fragpipe14\tools\msfragger_pep_split.py", line 457, in main
    calibrate_mzBIN, params_txt_new = calibrate(fasta_path_sample, calibrate_mass)
  File "D:\protprog\fragpipe14\tools\msfragger_pep_split.py", line 433, in calibrate
    shutil.copy(orig, dest)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'D:\\prot\\exp\\control1.d'
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stoppingMsFragger move pepxml
D:\protprog\fragpipe14\jre\bin\java.exe -cp D:\protprog\fragpipe14\lib\fragpipe-14.0.jar com.github.chhh.utils.FileMove D:\prot\exp\control1.pepXML D:\results3\a_healthy\control1.pepXML`

I added my log file.
Thank you very much for your help,
César Rivera
Talca, Chile

[log_2020-12-13_07-19-02.txt](https://github.com/Nesvilab/MSFragger/files/5684464/log_2020-12-13_07-19-02.txt)

**Comment by cesarrivera** [comment]
Additionally, I gave full access to all folders. It didn't work.

`************MASS CALIBRATION AND PARAMETER OPTIMIZATION DONE IN 31.765 MIN*********
*******************************TOTAL TIME 188.503 MIN********************************
Traceback (most recent call last):
  File "D:\protprog\fragpipe14\tools\msfragger_pep_split.py", line 470, in <module>
    main()
  File "D:\protprog\fragpipe14\tools\msfragger_pep_split.py", line 457, in main
    calibrate_mzBIN, params_txt_new = calibrate(fasta_path_sample, calibrate_mass)
  File "D:\protprog\fragpipe14\tools\msfragger_pep_split.py", line 433, in calibrate
    shutil.copy(orig, dest)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'D:\\prot\\exp\\control1.d'
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stoppingMsFragger move pepxml
D:\protprog\fragpipe14\jre\bin\java.exe -cp D:\protprog\fragpipe14\lib\fragpipe-14.0.jar com.github.chhh.utils.FileMove D:\prot\exp\control1.pepXML D:\results3\a_healthy\control1.pepXML

~~~~~~~~~~~~~~~~~~~~
Cancelling 62 remaining tasks
Processing interrupted, stopping MsFragger move pepxml`

[log_2020-12-13_11-25-25.txt](https://github.com/Nesvilab/MSFragger/files/5684715/log_2020-12-13_11-25-25.txt)

**Comment by fcyu** [comment]
It looks like a split database issue. @guoci Could you take a look when you have time?

Thanks,

Fengchao

**Comment by guoci** [comment]
@cesarrivera, please try the following:
https://drive.google.com/file/d/1doVqkJQGfmw5JeHhdRc2yjw4e6zj_IkH/view?usp=sharing

**Comment by cesarrivera** [comment]
Thanks, I will try with this file.
I just downloaded it.

**Comment by BrendonSeale** [comment]
Hello,

I also experience this error and the linked file didn't resolve it.

**Comment by guoci** [comment]
@BrendonSeale please show me your log file.

**Comment by BrendonSeale** [comment]
See attached.
[log_2020-12-15_08-26-09.txt](https://github.com/Nesvilab/MSFragger/files/5696173/log_2020-12-15_08-26-09.txt)

**Comment by cesarrivera** [comment]
Hello @fcyu and @guoci 
I just finished my analysis, without errors (FragPipe V.14 buid 9).
I chose 10 for "**split database**".
I added my log file.
I am very grateful for all the cooperation and support I have received.
[log_2020-12-15_13-59-23.txt](https://github.com/Nesvilab/MSFragger/files/5697453/log_2020-12-15_13-59-23.txt)

**Comment by guoci** [comment]
@BrendonSeale according to the logs, it looks like you are not using the linked file.

**Comment by guoci** [comment]
Fixed at https://github.com/Nesvilab/FragPipe/commit/1fc7ad9f44b97d70ed166c1fa9b1b30b022aae97
