### ISSUE TITLE
Output column documentation

### ISSUE THREAD

**Issue by fabianegli** [Nesvilab/MSFragger#123]
Is there a place where the output columns in the `<run info>.tsv` file are described in some detail? I am thinking about something similar to the `tables.pdf` produces by MaxQuant. For my taste the descriptions could be even a bit more fleshed out.

**Comment by fcyu** [comment]
Here https://github.com/Nesvilab/MSFragger/wiki/Interpreting-MSFragger-Output

Best,

Fengchao

**Comment by fabianegli** [comment]
Thank you for the swift reply. I know this description, but it lacks the clear link to the column names in the tsv file.

**Comment by fcyu** [comment]
The numbers at the beginning of each row correspond to column index.

**Comment by fabianegli** [comment]
OK, so I was maybe not specifying the right file. I was in my mind thinking about the columns in the `combined_protein.tsv` and `combined_peptide.tsv` files. These files are not described and their columns don't match with the output description link above.

```
Protein Group
SubGroup
Protein
Protein ID
Entry Name
Gene Names
Protein Length
Coverage
Organism
Protein Existence
Description
Protein Probability
Top Peptide Probability
Unique Stripped Peptides
Summarized Total Spectral Count
Summarized Unique Spectral Count
Summarized Razor Spectral Count
<sample> Total Spectral Count
<sample> Unique Spectral Count
<sample> Razor Spectral Count
<sample> Total Ion Count
<sample> Unique Ion Count
<sample> Razor Ion Count
<sample> Total Intensity
<sample> Unique Intensity
<sample> Razor Intensity
```

Columns starting with `<sample>` are repeated for each sample in the analysis.

Of specific interest would be what these intensities and counts represent, i.e. how they are calculated (Which molecular ions contribute to which count? Are intensities summed? What exactly is summed up?).

The answers to these questions may seem obvious to the well trained proteomics expert, but many users will profit from them.

**Comment by fcyu** [comment]
These tables are generated by [Philosopher](https://github.com/Nesvilab/philosopher), and the descriptions are supposed to be here ([https://github.com/Nesvilab/philosopher/wiki](https://github.com/Nesvilab/philosopher/wiki)). Unfortunately, there are only `psm.tsv`, `ion.tsv`, `peptide.tsv`, and `protein.tsv`.

Sarah @hayse1 and Felipe @prvst , could you add the missing part when you have time?

Thanks,

Fengchao

**Comment by prvst** [comment]
@hayse1 is working on the file descriptions.
