### ISSUE TITLE
C-terminal modification

### ISSUE THREAD

**Issue by clairemcwhite** [Nesvilab/MSFragger#124]
Hi,

If I want to look for a c-terminal variable modification, which would be the correct syntax? 

variable_mod_01 = -0.9840 ^] 1
or
variable_mod_01 = -0.9840 ]^ 1

Similarly, for a peptide modification would it be cX or Xc? 

Thanks

**Comment by fcyu** [comment]
Should be `]^` and `cX` because `]`, `[`, `n`, and `c` are like adjectives.

Best,

Fengchao

**Comment by anesvi** [comment]
I use this for  c-term peptide amidation


c^

-0.98402

1
