### ISSUE TITLE
MSFragger on command line [UNIX] --> DB splitting

### ISSUE THREAD

**Issue by PatrickvanZalm** [Nesvilab/MSFragger#125]
Dear MSFragger team,

I am working on setting up MSFragger searches on our cloud-computing infrastructure. While I do get it running for a 'normal' search, the second I include bigger databases I run into trouble. Previously I did solve this by splitting the database, but I can not seem to find where this option exists. I follow the shell here (timsTOF) http://msfragger.nesvilab.org/tutorial_linux.html

I came across a previous post:
https://github.com/Nesvilab/MSFragger/issues/110

Would that work? And if so, what would be the appropriate location of such command within the examplary shell script ?

Thank you in advance.

Best,
Patrick

**Comment by fcyu** [comment]
Hi Patrick,

DB splitting comes with FragPipe. Can you try to run FragPipe on your server with X forwarding ([https://msfragger.nesvilab.org/tutorial_setup_x_forwarding.html](https://msfragger.nesvilab.org/tutorial_setup_x_forwarding.html))

Best,

Fengchao

**Comment by PatrickvanZalm** [comment]
Hi Fengchao,

I will ask the people in charge of the cloud-server if X-forwarding would be possible.

I will get back to you, thank you for your prompt reply.

**Comment by PatrickvanZalm** [comment]
I have inquired and the platform does not support X-forwarding by design.

I guess I would have to implemenent the splitting directly in the command line?

**Comment by fcyu** [comment]
Then, I think you can use the command from that issue [https://github.com/Nesvilab/MSFragger/issues/110#issuecomment-717250290](https://github.com/Nesvilab/MSFragger/issues/110#issuecomment-717250290).

**Comment by PatrickvanZalm** [comment]
Thank you. I have currently written the line as following:

`python3 /media/sf_Arthur_Linux/fragpipe/tools/msfragger_pep_split.py 4 "java -jar -Dfile.encoding=UTF-8 -Xmx200G" /media/sf_Arthur_Linux/fragpipe/MSFragger-20171106/MSFragger-3.1.1/MSFragger-3.1.1.jar /media/sf_Arthur_Linux/IMPACC_Phase1/PATRICK_TEST/fragger.params /media/sf_Arthur_Linux/Patrick/20200114_PvZ_Peptidomics_ResuspensionTest/BufferA2_S4-B9_1_3624.d /media/sf_Arthur_Linux/Patrick/20200114_PvZ_Peptidomics_ResuspensionTest/BufferA3_S4-C9_1_3628.d`

However, I still get an error:
`+ python3 /media/sf_Arthur_Linux/fragpipe/tools/msfragger_pep_split.py 4 'java -jar -Dfile.encoding=UTF-8 -Xmx200G' /media/sf_Arthur_Linux/fragpipe/MSFragger-20171106/MSFragger-3.1.1/MSFragger-3.1.1.jar /media/sf_Arthur_Linux/IMPACC_Phase1/PATRICK_TEST/fragger.params /media/sf_Arthur_Linux/Patrick/20200114_PvZ_Peptidomics_ResuspensionTest/BufferA2_S4-B9_1_3624.d /media/sf_Arthur_Linux/Patrick/20200114_PvZ_Peptidomics_ResuspensionTest/BufferA3_S4-C9_1_3628.d
Traceback (most recent call last):
  File "/media/sf_Arthur_Linux/fragpipe/tools/msfragger_pep_split.py", line 470, in <module>
    main()
  File "/media/sf_Arthur_Linux/fragpipe/tools/msfragger_pep_split.py", line 453, in main
    set_up_directories()
  File "/media/sf_Arthur_Linux/fragpipe/tools/msfragger_pep_split.py", line 115, in set_up_directories
    shutil.rmtree(tempdir)
  File "/usr/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.8/shutil.py", line 656, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 654, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 26] Text file busy: '0'`

Ive been trying to figure out what causes this problem and it seems it is related to multiple commands trying to access the same file?

**Comment by fcyu** [comment]
@guoci Can you take a look at this error when you have time?

Thanks,

Fengchao

**Comment by guoci** [comment]
@PatrickvanZalm The error you see occurred at the deleting of temporary files, at the last step of the program, so it shouldn't matter. You can continue as usual.
