### ISSUE TITLE
JVM stated with 0 GB memory

### ISSUE THREAD

**Issue by Romi112** [Nesvilab/MSFragger#127]
Hi,
I am trying to test msfragger open searches within philosopher in Fragpipe but am getting the following error:
(I'm new to github and posting stuff, still hope you find all the info you need to help me)

System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_242, OpenJDK 64-Bit Server VM, AdoptOpenJDK

Version info:
FragPipe version 14.0
MSFragger version 3.1.1
Philosopher version 3.4.13 (build 1611589727)

LCMS files:
  Experiment/Group: 
  - D:\JEG\Gelfree_BU\RAW\G1.raw

~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ fragpipe.config ~~~~~~~~~
# FragPipe v14.0ui state cache

crystalc.run-crystalc=false
database.db-path=D\:\\JEG\\2021-02-03-decoys_Ref_uniprot-proteome_cRAP.fasta.fas
database.decoy-tag=rev_
fragpipe-config.bin-msfragger=C\:\\Users\\Admin\\Desktop\\OLD\\FragPipe-14.0\\MSFragger-3.1.1\\MSFragger-3.1.1\\MSFragger-3.1.1.jar
fragpipe-config.bin-philosopher=C\:\\Users\\Admin\\Desktop\\fragpipe\\lib\\..\\tools\\philosopher\\philosopher.exe
fragpipe-config.bin-python=C\:\\Users\\Admin\\anaconda3\\python
freequant.mz-tol=10
freequant.rt-tol=0.4
freequant.run-freequant=true
ionquant.excludemods=
ionquant.heavy=
ionquant.imtol=0.05
ionquant.ionfdr=0.01
ionquant.light=
ionquant.mbr=0
ionquant.mbrimtol=0.05
ionquant.mbrmincorr=0
ionquant.mbrrttol=1
ionquant.mbrtoprun=10
ionquant.medium=
ionquant.minexps=1
ionquant.minfreq=0.5
ionquant.minions=1
ionquant.minisotopes=1
ionquant.mztol=10
ionquant.normalization=1
ionquant.peptidefdr=1
ionquant.proteinfdr=1
ionquant.proteinquant=1
ionquant.requantify=1
ionquant.rttol=0.4
ionquant.run-ionquant=false
ionquant.tp=3
ionquant.writeindex=0
msfragger.Y_type_masses=
msfragger.add_topN_complementary=0
msfragger.allow_multiple_variable_mods_on_residue=false
msfragger.allowed_missed_cleavage=2
msfragger.calibrate_mass=0
msfragger.clip_nTerm_M=true
msfragger.deisotope=1
msfragger.delta_mass_exclude_ranges=(-1.5,3.5)
msfragger.diagnostic_fragments=
msfragger.diagnostic_intensity_filter=0
msfragger.digest_max_length=40
msfragger.digest_min_length=7
msfragger.fragment_ion_series=b,y
msfragger.fragment_mass_tolerance=20
msfragger.fragment_mass_units=1
msfragger.intensity_transform=0
msfragger.ion_series_definitions=
msfragger.isotope_error=0/1/2
msfragger.labile_search_mode=off
msfragger.localize_delta_mass=false
msfragger.mass_diff_to_variable_mod=0
msfragger.mass_offsets=0
msfragger.max_fragment_charge=2
msfragger.max_variable_mods_combinations=5000
msfragger.max_variable_mods_per_peptide=3
msfragger.min_fragments_modelling=2
msfragger.min_matched_fragments=4
msfragger.minimum_peaks=15
msfragger.minimum_ratio=0.01
msfragger.misc.fragger.clear-mz-hi=0
msfragger.misc.fragger.clear-mz-lo=0
msfragger.misc.fragger.digest-mass-hi=5000
msfragger.misc.fragger.digest-mass-lo=500
msfragger.misc.fragger.enzyme-dropdown=trypsin
msfragger.misc.fragger.precursor-charge-hi=4
msfragger.misc.fragger.precursor-charge-lo=1
msfragger.misc.fragger.remove-precursor-range-hi=1.5
msfragger.misc.fragger.remove-precursor-range-lo=-1.5
msfragger.misc.slice-db=1
msfragger.num_enzyme_termini=2
msfragger.output_format=pepXML
msfragger.output_max_expect=50
msfragger.output_report_topN=1
msfragger.override_charge=false
msfragger.precursor_mass_lower=-200
msfragger.precursor_mass_mode=selected
msfragger.precursor_mass_units=1
msfragger.precursor_mass_upper=200
msfragger.precursor_true_tolerance=20
msfragger.precursor_true_units=1
msfragger.remove_precursor_peak=0
msfragger.report_alternative_proteins=false
msfragger.restrict_deltamass_to=all
msfragger.run-msfragger=true
msfragger.search_enzyme_butnotafter=
msfragger.search_enzyme_cutafter=KR
msfragger.search_enzyme_name=stricttrypsin
msfragger.table.fix-mods=0.000000,C-Term Peptide,true,-1; 0.000000,N-Term Peptide,true,-1; 0.000000,C-Term Protein,true,-1; 0.000000,N-Term Protein,true,-1; 0.000000,G (glycine),true,-1; 0.000000,A (alanine),true,-1; 0.000000,S (serine),true,-1; 0.000000,P (proline),true,-1; 0.000000,V (valine),true,-1; 0.000000,T (threonine),true,-1; 57.021464,C (cysteine),true,-1; 0.000000,L (leucine),true,-1; 0.000000,I (isoleucine),true,-1; 0.000000,N (asparagine),true,-1; 0.000000,D (aspartic acid),true,-1; 0.000000,Q (glutamine),true,-1; 0.000000,K (lysine),true,-1; 0.000000,E (glutamic acid),true,-1; 0.000000,M (methionine),true,-1; 0.000000,H (histidine),true,-1; 0.000000,F (phenylalanine),true,-1; 0.000000,R (arginine),true,-1; 0.000000,Y (tyrosine),true,-1; 0.000000,W (tryptophan),true,-1; 0.000000,B ,true,-1; 0.000000,J,true,-1; 0.000000,O,true,-1; 0.000000,U,true,-1; 0.000000,X,true,-1; 0.000000,Z,true,-1
msfragger.table.var-mods=15.994900,M,true,3; 42.010600,[^,true,1; 79.966330,STY,false,3; -17.026500,nQnC,false,1; -18.010600,nE,false,1; 0.000000,site_06,false,1; 0.000000,site_07,false,1; 0.000000,site_08,false,1; 0.000000,site_09,false,1; 0.000000,site_10,false,1; 0.000000,site_11,false,1; 0.000000,site_12,false,1; 0.000000,site_13,false,1; 0.000000,site_14,false,1; 0.000000,site_15,false,1; 0.000000,site_16,false,1
msfragger.track_zero_topN=0
msfragger.use_topN_peaks=150
msfragger.write_calibrated_mgf=false
msfragger.zero_bin_accept_expect=0
msfragger.zero_bin_mult_expect=1
peptide-prophet.cmd-opts=--decoyprobs --ppm --accmass --nonparam --expectscore
peptide-prophet.combine-pepxml=false
peptide-prophet.run-peptide-prophet=true
phi-report.dont-use-prot-proph-file=false
phi-report.filter=--sequential --razor --prot 0.01
phi-report.pep-level-summary=false
phi-report.print-decoys=false
phi-report.run-report=true
protein-prophet.cmd-opts=--maxppmdiff 2000000
protein-prophet.run-protein-prophet=true
ptmprophet.cmdline=--keepold --static --em 1 --nions b --mods STY\:79.966331,M\:15.9949 --minprob 0.5
ptmprophet.run-ptmprophet=false
ptmshepherd.annotation-common=false
ptmshepherd.annotation-custom=false
ptmshepherd.annotation-unimod=true
ptmshepherd.annotation_file=
ptmshepherd.annotation_tol=0.01
ptmshepherd.cap_y_ions=
ptmshepherd.diag_ions=
ptmshepherd.glyco_mode=false
ptmshepherd.histo_smoothbins=2
ptmshepherd.iontype_a=false
ptmshepherd.iontype_b=true
ptmshepherd.iontype_c=false
ptmshepherd.iontype_x=false
ptmshepherd.iontype_y=true
ptmshepherd.iontype_z=false
ptmshepherd.localization_background=4
ptmshepherd.output_extended=false
ptmshepherd.peakpicking_mass_units=0
ptmshepherd.peakpicking_promRatio=0.3
ptmshepherd.peakpicking_width=0.002
ptmshepherd.precursor_mass_units=0
ptmshepherd.precursor_tol=0.01
ptmshepherd.remainder_masses=
ptmshepherd.run-shepherd=false
ptmshepherd.spectra_maxfragcharge=2
ptmshepherd.varmod_masses=Failed_Carbamidomethylation\:-57.021464
quantitation.run-label-free-quant=false
speclibgen.easypqp.extras.rt_lowess_fraction=0.01
speclibgen.easypqp.rt-cal=noiRT
speclibgen.easypqp.select-file.text=
speclibgen.run-speclibgen=false
speclibgen.use-easypqp=false
speclibgen.use-spectrast=true
tmtintegrator.add_Ref=-1
tmtintegrator.allow_overlabel=true
tmtintegrator.allow_unlabeled=true
tmtintegrator.best_psm=true
tmtintegrator.channel_num=6
tmtintegrator.dont-run-fq-lq=false
tmtintegrator.freequant=--ptw 0.4 --tol 10 --isolated
tmtintegrator.groupby=0
tmtintegrator.labelquant=--tol 20 --level 2
tmtintegrator.max_pep_prob_thres=0
tmtintegrator.min_ntt=0
tmtintegrator.min_pep_prob=0.9
tmtintegrator.min_percent=0.05
tmtintegrator.min_purity=0.5
tmtintegrator.min_site_prob=-1
tmtintegrator.mod_tag=none
tmtintegrator.ms1_int=true
tmtintegrator.outlier_removal=true
tmtintegrator.print_RefInt=false
tmtintegrator.prot_exclude=none
tmtintegrator.prot_norm=0
tmtintegrator.psm_norm=false
tmtintegrator.ref_tag=Bridge
tmtintegrator.run-tmtintegrator=false
tmtintegrator.top3_pep=true
tmtintegrator.unique_gene=0
tmtintegrator.unique_pep=false
workdir=C\:\\Users\\Admin\\Desktop\\JEGTEST
workflow.input.data-type.im-ms=false
workflow.input.data-type.regular-ms=true
workflow.process-exps-separately=false
workflow.ram=0
workflow.threads=15

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WorkspaceCleanInit [Work dir: C:\Users\Admin\Desktop\JEGTEST]
C:\Users\Admin\Desktop\fragpipe\lib\..\tools\philosopher\philosopher.exe workspace --clean --nocheck
INFO[11:42:35] Executing Workspace  v3.4.13                 
INFO[11:42:35] Removing workspace                           
INFO[11:42:35] Done                                         
Process 'WorkspaceCleanInit' finished, exit code: 0
WorkspaceCleanInit [Work dir: C:\Users\Admin\Desktop\JEGTEST]
C:\Users\Admin\Desktop\fragpipe\lib\..\tools\philosopher\philosopher.exe workspace --init --nocheck
INFO[11:42:35] Executing Workspace  v3.4.13                 
INFO[11:42:35] Creating workspace                           
INFO[11:42:35] Done                                         
Process 'WorkspaceCleanInit' finished, exit code: 0
MsFragger [Work dir: C:\Users\Admin\Desktop\JEGTEST]
C:\Users\Admin\Desktop\fragpipe\jre\bin\java.exe -jar -Dfile.encoding=UTF-8 -Xmx249G C:\Users\Admin\Desktop\OLD\FragPipe-14.0\MSFragger-3.1.1\MSFragger-3.1.1\MSFragger-3.1.1.jar C:\Users\Admin\Desktop\JEGTEST\fragger.params D:\JEG\Gelfree_BU\RAW\G1.raw
MSFragger version MSFragger-3.1.1
Batmass-IO version 1.19.5
timsdata library version timsdata-2-7-0
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_242, OpenJDK 64-Bit Server VM, 
JVM started with 0 GB memory
Checking database...
Checking D:\JEG\Gelfree_BU\RAW\G1.raw...

************************************MAIN SEARCH************************************
Checking database...
Parameters:
num_threads = 15
database_name = D:\JEG\2021-02-03-decoys-B.t._Ref_uniprot-proteome UP000001414_cRAP.fasta.fas
decoy_prefix = rev_
precursor_mass_lower = -200.0
precursor_mass_upper = 200.0
precursor_mass_units = 1
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 20.0
fragment_mass_units = 1
calibrate_mass = 0
write_calibrated_mgf = false
isotope_error = 0/1/2
mass_offsets = 0
labile_search_mode = OFF
restrict_deltamass_to = all
precursor_mass_mode = SELECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
ion_series_definitions = 
search_enzyme_name = stricttrypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = 
num_enzyme_termini = 2
allowed_missed_cleavage = 2
clip_nTerm_M = true
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_peptide = 3
max_variable_mods_combinations = 5000
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 40
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 2
deisotope = 1
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 150
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.01
intensity_transform = 0
remove_precursor_peak = 0
remove_precursor_range = -1.500000,1.500000
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
mass_diff_to_variable_mod = 0
variable_mod_01 = 15.994900 M 3
variable_mod_02 = 42.010600 [^ 1
add_A_alanine = 0.000000
add_B_user_amino_acid = 0.000000
add_C_cysteine = 57.021464
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_D_aspartic_acid = 0.000000
add_E_glutamic_acid = 0.000000
add_F_phenylalanine = 0.000000
add_G_glycine = 0.000000
add_H_histidine = 0.000000
add_I_isoleucine = 0.000000
add_J_user_amino_acid = 0.000000
add_K_lysine = 0.000000
add_L_leucine = 0.000000
add_M_methionine = 0.000000
add_N_asparagine = 0.000000
add_Nterm_peptide = 0.0
add_Nterm_protein = 0.0
add_O_user_amino_acid = 0.000000  # O = pyrrolysine (255.15829 Da)
add_P_proline = 0.000000
add_Q_glutamine = 0.000000
add_R_arginine = 0.000000
add_S_serine = 0.000000
add_T_threonine = 0.000000
add_U_user_amino_acid = 0.000000  # U = selenocysteine (150.95363 Da)
add_V_valine = 0.000000
add_W_tryptophan = 0.000000
add_X_user_amino_acid = 0.000000
add_Y_tyrosine = 0.000000
add_Z_user_amino_acid = 0.000000
Number of unique peptides
	of length 7: 47435
	of length 8: 46618
	of length 9: 44573
	of length 10: 43569
	of length 11: 42579
	of length 12: 41507
	of length 13: 39169
	of length 14: 37814
	of length 15: 36649
	of length 16: 34868
	of length 17: 33269
	of length 18: 31867
	of length 19: 31207
	of length 20: 29301
	of length 21: 27947
	of length 22: 26638
	of length 23: 24995
	of length 24: 23340
	of length 25: 22186
	of length 26: 21110
	of length 27: 19903
	of length 28: 18772
	of length 29: 17087
	of length 30: 16232
	of length 31: 14958
	of length 32: 13975
	of length 33: 12927
	of length 34: 12157
	of length 35: 11091
	of length 36: 10586
	of length 37: 9537
	of length 38: 8991
	of length 39: 8250
	of length 40: 7610
In total 868717 peptides.
**java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at edu.umich.andykong.msfragger.M.a(Unknown Source)
	at edu.umich.andykong.msfragger.K.a(Unknown Source)
	at edu.umich.andykong.msfragger.m.a(Unknown Source)
	at edu.umich.andykong.msfragger.B.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Caused by: java.lang.OutOfMemoryError: Java heap space
Picked up _JAVA_OPTIONS: -Xmx512M**
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stoppingMsFragger move pepxml
C:\Users\Admin\Desktop\fragpipe\jre\bin\java.exe -cp C:\Users\Admin\Desktop\fragpipe\lib\fragpipe-14.0.jar com.github.chhh.utils.FileMove D:\JEG\Gelfree_BU\RAW\G1.pepXML C:\Users\Admin\Desktop\JEGTEST\G1.pepXML

~~~~~~~~~~~~~~~~~~~~
Cancelling 10 remaining tasks
Processing interrupted, stopping MsFragger move pepxml


**Im not familiar with java and cant tell, if its a problem with the java installation or msfragger. Hopefully someone of you know´s what's going on.

Best 
Romi**

**Comment by fcyu** [comment]
I guess this is because there is not much free memory available in your computer.

Best,

Fengchao

**Comment by Romi112** [comment]
In fact, I have 256 GB of DDR3 memory in this computer. I also changed the global RAM settings from 0 to higher values, but as expected this has no effect on the JVM startup memory (it is 0 GB in my runs).

**Comment by fcyu** [comment]
There are `C:\Users\Admin\Desktop\fragpipe\jre\bin\java.exe -jar -Dfile.encoding=UTF-8 -Xmx249G C:\Users\Admin\Desktop\OLD\FragPipe-14.0\MSFragger-3.1.1\MSFragger-3.1.1\MSFragger-3.1.1.jar C:\Users\Admin\Desktop\JEGTEST\fragger.params` and `Picked up _JAVA_OPTIONS: -Xmx512M` in your log, which indicates that your configuration limits the usage of the memory. Can you check if your system has the global `JAVA_OPTIONS`?

Best,

Fengchao
