### ISSUE TITLE
Request for N-terminal enzymatic digestion

### ISSUE THREAD

**Issue by TomClarkMassSpec** [Nesvilab/MSFragger#131]
Hi,

Selecting the 'custom' from enzyme selection list, user is presented with 'cuts after' and 'but not before'. Lysarginase cuts N-terminal to R and K but not after P. Please, thank you and more of a suggested addition., Tom

Tsiatsiani L, Giansanti P, Scheltema RA, van den Toorn H, Overall CM, Altelaar AF, Heck AJ.
J Proteome Res. 2017 Feb 3;16(2):852-861. doi: 10.1021/acs.jproteome.6b00825. Epub 2016 Dec 2.
PMID: 28111955
Bell PA, Solis N, Kizhakkedathu JN, Matthew I, Overall CM.
J Proteome Res. 2019 Dec 6;18(12):4167-4179. doi: 10.1021/acs.jproteome.9b00445. Epub 2019 Oct 25.
PMID: 31601107

**Comment by fcyu** [comment]
Yes, N-terminal enzymatic digestion is one of the requested features. There is already an issue ([https://github.com/Nesvilab/MSFragger/issues/9](https://github.com/Nesvilab/MSFragger/issues/9)) about it. I will close this one.

Best,

Fengchao
