### ISSUE TITLE
Best strategy for obtaining full scored unfiltered list of peptides and decoys

### ISSUE THREAD

**Issue by TomClarkMassSpec** [Nesvilab/MSFragger#133]
Hello, So I have python code as part of a project for downstream analysis. For it to work correctly, I need to obtain the list of scored peptides or PSMs including those that have been filtered out including decoys. I'd really like to leave the peptide spectrum matching and scoring to MSFragger / peptide prophet without my meddling. The output files *.tsv and such have outputs which are great but only include the filtered results. Before I continue, I'd like to ask the best strategy for obtaining the full lists of scored peptides (pepXML, mzID, or PIN??) or is this something I need to get my hands really dirty with? My project is about protein inferencing, not peptide ID which is clearly already done well by applications such as MS Fragger. Probably not the best question for Github but if you could send me in the best direction (for unfiltered PSMs including decoys), it would be most appreciated. Thanks Tom

**Comment by fcyu** [comment]
You can 1) check 'print decoys' and set all FDR threshold in FragPipe; or 2) let MSFragger output <run name>.tsv or pin file.

Best,

Fengchao

**Comment by TomClarkMassSpec** [comment]
Thanks Fengchao,
I will try just this again. I  just upgraded through several revisions of MSFragger/Fragpipe. It seemed to me setting the FDR thresholds up to an arbitrarily high number caused an issue but maybe this was propagated through to the peptide cut offs through implementation of protein prophet. When you say 'set all threshold', you mean I can should set to 0.9 or is there a command I may be unaware of?Tom

**Comment by fcyu** [comment]
Hi Tom,

You can change the FDR threshold in the ‘Filter' command:
![image](https://user-images.githubusercontent.com/6926299/108928454-2f4c0e80-7610-11eb-9ac5-8b4588bdc46d.png)

By setting 1 for PSM, peptide, ion, and protein level FDR thresholds; and 0 for peptide and protein probability thresholds, you should be able to get all PSMs.

Best,

Fengchao

**Comment by anesvi** [comment]
If you want no filtering at all, then also need to set --minprot 0 in PeptideProphet. Because by default it writes PSM with probability above 0.05

**Comment by TomClarkMassSpec** [comment]
Thank you Fengchao and Prof. Nesvizskii
