### ISSUE TITLE
Suggestions for Best Parameters for Single Cell Data?

### ISSUE THREAD

**Issue by daishavdw** [Nesvilab/MSFragger#136]
Hello,
I am trying to benchmark annotations between 2 tools for single cell data. For now, I have mostly used the standard settings in MSFragger. Do you have any suggestions for optimal parameters for your tool when working with single cell data?

Thank you!

**Comment by fcyu** [comment]
For MSFragger, probably no need to change the default settings. But for quantification using IonQuant, you may need to change the min ions from 2 to 1.

Best,

Fengchao
