### ISSUE TITLE
MSFragger change FDR in FragPipe

### ISSUE THREAD

**Issue by Helleopensearchproteomics** [Nesvilab/MSFragger#144]
Hello! I want to change peptide FDR in Fragpipe (v14.0). 
I changed —prot 0.01 to —prot 0.05 in the Filter and Report section (at the validation tab). See picture below. 

When I look into filter.log, it seems like I only changed the protein FDR to 5%, the peptide FDR seems to be 0.72% (see picture). How do I change so that also the peptide FDR is 5%?

In an issue from 2018, it says that: ”if you have 'Report Protein level FDR' box checked, you will be applying BOTH protein level FDR and PSM/ion/peptide level FDR”. But I can’t find such box in this version. 

<img width="465" alt="Skärmavbild 2021-03-30 kl  11 21 54" src="https://user-images.githubusercontent.com/79263448/112968280-6f8d3800-914c-11eb-9ca0-ebc5464567cf.png">
<img width="547" alt="Skärmavbild 2021-03-30 kl  11 24 23" src="https://user-images.githubusercontent.com/79263448/112968308-761baf80-914c-11eb-852b-9b86c1bbd6c3.png">

**Comment by fcyu** [comment]
You need to change PSM FDR, ion FDR, peptide FDR, and protein FDR. There is a tooltip when you hover your mouse over the textbox:
![image](https://user-images.githubusercontent.com/6926299/112999377-e4f10c80-913c-11eb-8825-831a3723900d.png)

Best,

Fengchao

**Comment by hboekweg** [comment]
I have a similar question: 
I'm trying to get rid of the FDR cutoff entirely, but it doesn't seem to be working. 
I'm looking at the generated psm file and I only see 30 decoy proteins (as denoted by rev_ in the protein column). 
If getting rid of the FDR cutoff had been successful then I would be seeing a lot more spectra labeled as decoys (there are about 13500 total spectra, but only 30 are labeled as decoys). 

I've tried the following parameters:
--sequential --tag rev_ --razor --prot 1 --psm 1 --pepProb 1 --protProb 1 --ion 1

--sequential --tag rev_ --razor --prot 0.99 --psm 0.99 --pepProb 1 --protProb 1 --ion .99 

I'm also making sure that it's reporting decoys (as shown in the screenshot below). 

![image](https://user-images.githubusercontent.com/25016822/113211106-421aba00-9232-11eb-9bc1-4202b578e520.png)

Any help you could give me would be really appreciated.  
Thanks!

**Comment by fcyu** [comment]
You need to have `--sequential --razor --ion 1 --pep 1 --pepProb 0 --prot 1 --protProb 0 --psm 1`

Best,

Fengchao

**Comment by Hanna-Wong** [comment]
"Why do the --prot 0.05 value and other parameters I enter in the Filter box under the Validation tab in FragPipe GUI fail to take effect, with the log still running at the default FDR of 0.01?"

**Comment by fcyu** [comment]
Duplicate of https://github.com/Nesvilab/FragPipe/issues/2852
