### ISSUE TITLE
Protein group Molecular weight column

### ISSUE THREAD

**Issue by rnirujogi** [Nesvilab/MSFragger#145]
Dear Developers,

I couldn't find a Mol. wt column in the output tables generated from MS-Frgger search. Is there any option that I am missing to get this info. If not it would be good to compute this info in the reports in future versions of MS-Fragger. Many thanks.

Best,
Raja

**Comment by fcyu** [comment]
There are observed mass, calibrated observed mass, and calculated peptide mass columns in psm.tsv. There are also similar columns in other files. So, I think you can find one of them meets your "mol. wt" definition.

Best,

Fengchao

**Comment by rnirujogi** [comment]
Hi Fengchao,

Thanks for the quick reply. Sorry, I should have mentioned it bit clear. I meant Mol. Wt (kDa) for the protein IDs in the protein table. Sequence length info is available but not the Mol. Wt [kDa] of the protein.

Thanks,
Raja

**Comment by fcyu** [comment]
Right, we don't have protein mass column. I guess it is some Philosopher should add.

Best,

Fengchao

**Comment by prvst** [comment]
Hi, @rnirujogi. I'm not planning to add the protein mass to output tables. However, this is something you can easily grab from reference databases like UniProt.
