### ISSUE TITLE
Open search of TMT-labelled phospho-enriched data

### ISSUE THREAD

**Issue by o-t** [Nesvilab/MSFragger#149]
Hi,

I have been running an open search on TMT-labelled phospho-enriched data, and have some questions about it.

1) MSFragger said the data is low resolution, but I have run a closed search on the data before, and that did not say the data is low resolution

2) In the global.profile.tsv file PTM-Shepherd generated, phosphorylation was found only in very few PSMs

Any help will be appreciated. Thanks!

**Comment by fcyu** [comment]
> MSFragger said the data is low resolution, but I have run a closed search on the data before, and that did not say the data is low resolution

Resolution detection is a function introduced recently. If you are sure that your data has high resolution MS2, could you send one of your files to us?

Best,

Fengchao

**Comment by danielgeiszler** [comment]
In order to get proper Phospho annotations for the phospho-enriched data, you probably need to change the “Failed_carbamidomethylation” to a phosphorylation event.

Also, you’ll get fewer phospho PSMs if you searched for it as a variable mod during your open search.

**Comment by o-t** [comment]
> Resolution detection is a function introduced recently. If you are sure that your data has high resolution MS2, could you send one of your files to us?

Hi Fengchao,

Hmm. Guess I will have to ask the PI if that's OK. Will get back to you if they say it's OK. Actually, would it be possible to add an option in the search parameters to tell MSFragger that the data is high or low resolution?

**Comment by o-t** [comment]
> In order to get proper Phospho annotations for the phospho-enriched data, you probably need to change the “Failed_carbamidomethylation” to a phosphorylation event.
>
> Also, you’ll get fewer phospho PSMs if you searched for it as a variable mod during your open search.

Hi Daniel,

I didn't put phosphorylation as a variable mod, but thanks, I will try setting phosphorylation in PTM-Shepherd

**Comment by fcyu** [comment]
>  Actually, would it be possible to add an option in the search parameters to tell MSFragger that the data is high or low resolution?

We add the resolution detection because many users forget to set the fragment tolerance incorrectly. If we added the option you want to FragPipe, the old issue would be back: users forget to set the fragment tolerance correctly --> MSFragger corrects it --> users forget to set the option you want correctly --> MSFragger uncorrect it.

MSFragger has an advanced option `check_spectral_files` to control if checking the resolution. If you want to use it, you can put `check_spectral_files = 0` to fragger.params.

Best,

Fengchao

**Comment by anesvi** [comment]
I only see an issue if the data is high mass accuracy, but our automated check somehow thinks it is low mass accuracy (if so, why? We would want to fix). If that can happen, we can add this option check_spectral_files (1 by default) to FragPipe/MSFragger. That way, the user can overwrite it (or if they are sure about the data and do not want to spend time checking the files).
Alexey

**Comment by fcyu** [comment]
MSFragger uses `filter string` in Thermo data (the checking only works for Thermo data) to decide if the data is from FTMS or ITMS. I cannot find any issue by looking at the code. Need to check the data. Or, @o-t could you help to check if the `filter string` in your data has `ITMS` if you cannot send your file?

Best,

Fengchao

**Comment by o-t** [comment]
Hi Fengchao,

It has `FTMS` at the `filter string`...

**Comment by fcyu** [comment]
Then, I don't know why MSFragger think it is low resolution. I need one of your mzML file to figure out.

Best,

Fengchao

**Comment by o-t** [comment]
Hi Fengchao,

Here is the file: https://gofile.io/d/sE8BES. Thank you!

**Comment by fcyu** [comment]
Thanks for your file, but are you sure that MSFragger thought it having low resolution MS2? From my testing, MSFragger successfully detects the high resolution property. If you still think MSFragger got it wrong, could you send us your log?

Best,

Fengchao

**Comment by o-t** [comment]
Hmmm, I might have deleted the log file, and strangely I couldn't reproduce the result that it was detected as low resolution... I will close the issue for now, and reopen if the problem appears later again (hopefully not!) Thanks for the help!

**Comment by hazelweeling** [comment]
Hi MSFragger team,

I'm reopening this issue as I have a similar problem.

I'm trying to use open search for a phospho-enriched dataset. However, the number of detected phosphopeptides from open search are a lot less than the number detected from closed search (Phospho-TMT10 workflow).

Are there parameters that need to be modified in the open search default workflow to optimize results?

The mzml file that I'm using for this is from MSV000083786.

Thanks and best wishes,
Hazel

**Comment by hazelweeling** [comment]
Thanks for the prompt reply.

Here it is. 
[log_2022-05-05_09-00-10.txt](https://github.com/Nesvilab/MSFragger/files/8632028/log_2022-05-05_09-00-10.txt)

BW,
Hazel

**Comment by fcyu** [comment]
If your data has TMT, you need to set TMT as fix/variable modifications. Open search is not good at capture more than one modifications on one peptide.

Best,

Fengchao

**Comment by hazelweeling** [comment]
How would I set the TMT as a fixed/variable modification? 
I'm new to this, are there guidelines for how to edit the modifications online?

Thanks for helping.

BW,
Hazel

**Comment by danielgeiszler** [comment]
Please refer to our tutorials page here:

https://fragpipe.nesvilab.org/

**Comment by hazelweeling** [comment]
Thanks Fengchao for the suggestion and tutorial link.

I've tried your suggestion by adding TMT tags to the variable modification. However, I'm running into mass calibration errors ("not enough data to perform mass calibration"). So, based on your group's suggestion in the previous post, I changed the fragment ppm tolerance to 300 ppm. I'm still facing the same issue of mass calibration error. Also, the run keeps stalling at the main search (after computing the number of unique peptides).

I'm attaching the log and workflow used.
[log_2022-05-06_05-24-34.txt](https://github.com/Nesvilab/MSFragger/files/8637520/log_2022-05-06_05-24-34.txt)
[fragger.txt](https://github.com/Nesvilab/MSFragger/files/8637536/fragger.txt)

Thanks again!

BW,
Hazel

**Comment by hazelweeling** [comment]
Thanks Daniel. I've checked the "use all mods in first search", but the program seems to stop in the midst of main search. Attached a snapshot below of where it stalls.
![image](https://user-images.githubusercontent.com/92432310/167141502-75bd35d4-6a9a-4b8d-a780-909740f02ef3.png)

Also, attaching log and workflow parameters.
[fragger.txt](https://github.com/Nesvilab/MSFragger/files/8640359/fragger.txt)
[log_2022-05-06_14-25-30.txt](https://github.com/Nesvilab/MSFragger/files/8640364/log_2022-05-06_14-25-30.txt)

Any more suggestions on how I could get this working would be helpful.

Thanks!

BW,
Hazel

**Comment by fcyu** [comment]
Hi Hazel,

Your TMT variable modifications are not correct. If you are using TMT 10, it should be something like 

![image](https://user-images.githubusercontent.com/6926299/167145716-0bf0fa78-6819-4302-a24f-5ebd8506472a.png)

You should also set 229 on K as the fixed modification.
![image](https://user-images.githubusercontent.com/6926299/167145755-7a4c0242-2e3d-4ac7-adc9-e9f8a7ffad90.png)

Please refer to https://github.com/Nesvilab/MSFragger/wiki/Setting-the-Parameters#Variable-Modifications for the format of variable modification.

After you correct the settings, please try again.

Best,

Fengchao

**Comment by hazelweeling** [comment]
Thank you very much Fengchao, for pointing that out. 

I've altered the settings and now open search has produced some useful results.

BW,
Hazel

**Comment by danielgeiszler** [comment]
It is also expected that you get fewer phospho IDs during an open search than a closed search because it’s noisier. Unless you’re looking for non-phospho peptides in your phospho data then you don’t need an open search.
