### ISSUE TITLE
Custom ion series

### ISSUE THREAD

**Issue by telekandris** [Nesvilab/MSFragger#151]
I am trying to run a search with FragPipe v15.0 including a custom ion series (defined as "y* C -249.0862"). When I include y* in fragment_ion_series, it gives the error "ion type must be one of [a, b, c, b-18, b~, x, y, z, y-18, y~, Y]". When I do not include y* (only in the definition field) the search runs until ProteinProphet is initiated, but it crashes because it does not find any PeptideProphet results. This error seems to be specific for custom ion series, because it does not happen if I do not define y* at all. Could you suggest some workaround?

Thanks in advance!

**Comment by fcyu** [comment]
Are you using the latest MSFragger? I cannot reproduce your issue.

Best,

Fengchao

**Comment by telekandris** [comment]
I am. (MSFragger 3.2)

**Comment by fcyu** [comment]
This is weird. I put my log in the attachment. As you can see, MSFragger works well with your `y* C -249.0862`. Can you double check your settings?

Best,

Fengchao

[log_2021-04-20_09-00-00.zip](https://github.com/Nesvilab/MSFragger/files/6343705/log_2021-04-20_09-00-00.zip)

**Comment by telekandris** [comment]
You just run MSFragger here, right? This also runs fur me. The error comes afterwards when initiating Protein Prophet.

**Comment by dpolasky** [comment]
Can you share your log file? It could be that the reason there aren't any results is that PeptideProphet modeling is failing

**Comment by telekandris** [comment]
Unfortunately it did not write the log into a file, but I checked and you are right, the model quality test fails for all (1+ to 7+)... What can I do about that?

**Comment by danielgeiszler** [comment]
Can you paste your PeptideProphet and ProteinProphet logs here so we can take a look?

**Comment by telekandris** [comment]
PeptideProphet [Work dir: C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion]
C:\Users\Teresa\Downloads\FragPipe-14.0\fragpipe\lib\..\tools\philosopher\philosopher.exe peptideprophet --nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel -2 --decoy rev_ --database C:\Users\Teresa\Downloads\FragPipe-14.0\fragpipe\tools\philosopher\2020-09-04-decoys-reviewed-contam-UP000005640.fas --combine 20210326_AT19_Rab_top.pepXML
INFO[15:44:06] Executing PeptideProphet  v3.4.13            
Unknown file type. No file loaded.C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion/20210326_AT19_Rab_top.raw
Unknown file type. No file loaded.C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion/20210326_AT19_Rab_top.raw
 file 1: C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion\20210326_AT19_Rab_top.pepXML
 processed altogether 75360 results
INFO: Results written to file: C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion\interact.pep.xml

  - C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion\interact.pep.xml
  - Building Commentz-Walter keyword tree...
  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

Using Decoy Label "rev_".
Decoy Probabilities will be reported.
Using non-parametric distributions
 (X! Tandem) (using Tandem's expectation score for modeling)
using search_offsets in mass mixture distr: 0/329.0525
init with X! Tandem stricttrypsin 
 PeptideProphet  (TPP v5.2.1-dev Flammagenitus, Build 201906281613-exported (Windows_NT-x86_64)) AKeller@ISB
 read in 0 1+, 31929 2+, 37630 3+, 4330 4+, 1002 5+, 469 6+, and 0 7+ spectra.
Found 36543 Decoys, and 38817 Non-Decoys
MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ... 
Initialising statistical models ...
Iterations: .........10.........20....WARNING: Mixture model quality test failed for charge (1+).
.
WARNING: Mixture model quality test failed for charge (2+).
WARNING: Mixture model quality test failed for charge (3+).
WARNING: Mixture model quality test failed for charge (4+).
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
model complete after 26 iterations
INFO[15:46:09] Done                                         
Process 'PeptideProphet' finished, exit code: 0
Rewrite pepxml [Work dir: C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion]
java -cp C:\Users\Teresa\Downloads\FragPipe-15.0\fragpipe\lib/* com.dmtavt.fragpipe.util.RewritePepxml C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion\interact.pep.xml C:\Users\Teresa\Desktop\current_analysis\AT19\20210326_AT19_Rab_top.raw
Fixing pepxml: C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion\interact.pep.xml
Writing output to: C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion\interact.pep.xml5348710383317590743.temp-rewrite
Deleting file: C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion\interact.pep.xml
Moving rewritten file to original location: [C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion\interact.pep.xml5348710383317590743.temp-rewrite] -> [C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion\interact.pep.xml]
Process 'Rewrite pepxml' finished, exit code: 0
ProteinProphet [Work dir: C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion]
C:\Users\Teresa\Downloads\FragPipe-14.0\fragpipe\lib\..\tools\philosopher\philosopher.exe proteinprophet --maxppmdiff 2000000 --output combined C:\Users\Teresa\Desktop\current_analysis\AT19\shiftion\interact.pep.xml
INFO[15:46:11] Executing ProteinProphet  v3.4.13            
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v5.2.1-dev Flammagenitus, Build 201906281613-exported (Windows_NT-x86_64))
 (no FPKM) (using degen pep info)
Reading in C:/Users/Teresa/Desktop/current_analysis/AT19/shiftion/interact.pep.xml...
did not find any PeptideProphet results in input data!  Did you forget to run PeptideProphet?
...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

WARNING: no data - output file will be empty
FATA[15:46:13] Cannot execute program. There was an error with ProteinProphet, please check your parameters and input files 
Process 'ProteinProphet' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by dpolasky** [comment]
It looks like PeptideProphet is not able to distinguish targets from decoys and can't make sense of the search results, so it does not output anything. I suspect this is happening only when using the custom y ion because it introduces too much noise into the search. Given that you are doing a mass offset search, are you trying to find a labile modification that might leave behind this remainder mass on the y ions? If so, I think what's happening is the custom y ion is searched for ALL spectra, not just those with the mass offset of the modification, and this is causing trouble in matching the rest of the unmodified spectra. Are you still including regular b/y ions in the search? If not, that would definitely cause this problem. If so, it will likely be challenging to get this to converge with the custom y ions - if that's the case, maybe you can contact us directly via email to discuss settings for a labile PTM search like this in more detail

**Comment by telekandris** [comment]
This is exactly the case, I suspected that searching every spectra for the shifted ions might cause problems, but I could not find a simple way to restrict the search. Thanks for explaining, I will come back to you after discussing it with my boss.
