### ISSUE TITLE
TIMS-Skyline library build

### ISSUE THREAD

**Issue by BR-metal** [Nesvilab/MSFragger#152]
Aim to build library in skyline from fragger output with the hope that skyline. keep getting the error:

ERROR: index 37599 out of range in mzXML file '..\hela cells_200ng.mzXML'

**Comment by fcyu** [comment]
I guess the error is from Skyline. Can you submit a ticket to https://skyline.ms/project/home/support/begin.view ?

Best,

Fengchao

**Comment by BR-metal** [comment]
Will do thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Fengchao ***@***.***>
Sent: Thursday, April 22, 2021 12:19:16 PM
To: Nesvilab/MSFragger ***@***.***>
Cc: Roberts, Blaine Russell ***@***.***>; Author ***@***.***>
Subject: [External] Re: [Nesvilab/MSFragger] TIMS-Skyline library build (#152)


I guess the error is from Skyline. Can you submit a ticket to https://skyline.ms/project/home/support/begin.view<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fskyline.ms%2Fproject%2Fhome%2Fsupport%2Fbegin.view&data=04%7C01%7Cblaine.roberts%40emory.edu%7Ccd32936c874245c9bcc908d905aa60ab%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637547051601277179%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZsQL8D%2FuP3AkGFi%2BAOa0Gms5QHCz9tbPnwrUtPUIae8%3D&reserved=0> ?

Best,

Fengchao

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNesvilab%2FMSFragger%2Fissues%2F152%23issuecomment-824986424&data=04%7C01%7Cblaine.roberts%40emory.edu%7Ccd32936c874245c9bcc908d905aa60ab%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637547051601287172%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=llMuNsRYwp21xHux9ivL%2BDqm0QOGqnGkHUjqBTNuwzg%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOPYDJ7GOF6TZSKTKQ7BTI3TKBEAJANCNFSM43MYW6JA&data=04%7C01%7Cblaine.roberts%40emory.edu%7Ccd32936c874245c9bcc908d905aa60ab%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637547051601287172%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ttxFNfj%2BCLqeXxWuQbp78Yo9vDild%2F8xlaX6%2BoXaJ2E%3D&reserved=0>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by fcyu** [comment]
You are welcome.

Best,

Fengchao
