### ISSUE TITLE
Failed in checking spectral files.

### ISSUE THREAD

**Issue by jayieh** [Nesvilab/MSFragger#155]
Hi,

I want to run an open search on 48 raw files acquired on a QE. All samples were run with the same LC-MS method right after each other on the same instrument.

I was using the shell script you provide on a CentOS 7 machine:

`+ java -Xmx175G -jar /home/j/jeirich/MSFragger-3.2/MSFragger-3.2.jar /home/j/jeirich/MSFragger-3.2/open_fragger_AT_iodoTMTzero.params /home/j/jeirich/rawfiles_on_scratch/[...] 48 raw files

MSFragger version MSFragger-3.2
Batmass-IO version 1.22.1
timsdata library version timsdata-2-7-0
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 1.8.0_282, OpenJDK 64-Bit Server VM, Red Hat, Inc.
JVM started with 155 GB memory
Checking database...
Parameter 'diagnostic_intensity_filter' was not supplied. Using default value: 0.000000
Parameter 'ion_series_definitions' was not supplied. Using default value: 
Parameter 'Y_type_masses' was not supplied. Using default value: 
Parameter 'diagnostic_fragments' was not supplied. Using default value: 
Checking spectral files...
Failed in checking /home/j/jeirich/rawfiles_on_scratch/MGA143/210409_C20_008_QHF1_TMT_Rev10_#21_012_MGA143.raw
null
/home/j/jeirich/rawfiles_on_scratch/MGA143/210409_C20_008_QHF1_TMT_Rev10_#21_012_MGA143.raw: Scans = 0
/home/j/jeirich/rawfiles_on_scratch/MGA143/210409_C20_008_QHF1_TMT_Rev10_#21_012_MGA149.raw: Scans = 7063
/home/j/jeirich/rawfiles_on_scratch/MGA143/210409_C20_008_QHF1_TMT_Rev10_#21_012_MGA161.raw: Scans = 9254
/home/j/jeirich/rawfiles_on_scratch/MGA143/210409_C20_008_QHF1_TMT_Rev10_#21_012_MGA185.raw: Scans = 8910

a few more...

Failed in checking spectral files.
Failed in checking /home/j/jeirich/rawfiles_on_scratch/MGA143/210409_C20_008_QHF1_TMT_Rev10_#21_012_MGA177.raw
UNAVAILABLE: Network closed for unknown reason
/home/j/jeirich/rawfiles_on_scratch/MGA143/210409_C20_008_QHF1_TMT_Rev10_#21_012_MGA177.raw: Scans = 0
Failed in checking /home/j/jeirich/rawfiles_on_scratch/MGA143/210409_C20_008_QHF1_TMT_Rev10_#21_012_MGA178.raw
Shutdown in progress
/home/j/jeirich/rawfiles_on_scratch/MGA143/210409_C20_008_QHF1_TMT_Rev10_#21_012_MGA178.raw: Scans = 0
Failed in checking /home/j/jeirich/rawfiles_on_scratch/MGA143/210409_C20_008_QHF1_TMT_Rev10_#21_012_MGA190.raw
UNAVAILABLE: Network closed for unknown reason
/home/j/jeirich/rawfiles_on_scratch/MGA143/210409_C20_008_QHF1_TMT_Rev10_#21_012_MGA190.raw: Scans = 0
`
The very first file is indeed empty, but all the other 47 files yield PSMs when analyzing them either with MSFragger3.0 in the same environment, or another quantitative proteomics software package...

Do you have any advice?

Best

Jürgen

**Comment by fcyu** [comment]
Does your Linux have mono installed. If yes, then some configurations in your computer prevent MSFragger from communicating with its RAW data loading module. If you cannot find out a solution, you can convert your raw files to mzML according to the tutorial [tutorial](https://msfragger.nesvilab.org/tutorial_convert.html).

Best,

Fengchao

**Comment by jayieh** [comment]
Hi Fengchao,

thanks for the quick reply!

Yes, there is mono running in order to work with the raw files directly.

As I pointed out, a search on the same files was working fine with MSFragger 3.0 on the same computer with mono, too.

I just deleted the faulty, "empty" raw file, where no MS2 was acquired and now also MSFragger3.2 is working fine.

Maybe the new "Check MS2 resolution before the search" caused the problem in this particular case?

Best

Jürgen

**Comment by fcyu** [comment]
Hmm, interesting. Could you send me your "empty" raw file? Here ([https://www.dropbox.com/request/tOcnjDRrVuSr2OeUl1Yi](https://www.dropbox.com/request/tOcnjDRrVuSr2OeUl1Yi)) is the link to upload the file.

Best,

Fengchao

**Comment by jayieh** [comment]
Sure - I put it in your dropbox :)

To give you a bit of background: it was 48 files in total, I was trying to analyze. This empty one was the first, in alphabetical order, and MSFragger was continuing to check additional 35 files, before actually returning "Failed in checking spectral files." on the rest of the set of actually fine files...

I hope this is helpful :)

Best

Jürgen

**Comment by fcyu** [comment]
Hi Jürgen,

Thanks for your file. I found a tiny issue in checking files in parallel: when there is one file failed, the whole process stops at a random time point causing incorrect error messages for other files.


> MSFragger was continuing to check additional 35 files, before actually returning "Failed in checking spectral files." on the rest of the set of actually fine files...

This is what we wanted in case there are more than one corrupted files: we can locate all corrupted files by running it once.

Best,

Fengchao

**Comment by jayieh** [comment]
Thanks for the explanation.
