### ISSUE TITLE
Change in way MGF file is written in 3.2?

### ISSUE THREAD

**Issue by jacoblippincott** [Nesvilab/MSFragger#156]
This is Jacob from Proteome Software with more of a question than a bug report. 

I was working with a user who had connected Scaffold 5 to MSFragger 3.2 and was not seeing spectra in Scaffold like expected. After some troublehshooting of different MSFragger versions I have a question. The **write_calibrated_mgf = 1** parameter was used and I did this testing by running MSFragger via the CLI

When processing the raw file in question it did not have enough data to go through mass calibration and thus was not writing an MGF file. When I process the data using MSFragger 3.0 the calibration still did not complete but the program wrote an uncalibrated MGF file. 

My question is whether the behavior between 3.0 and 3.2 is intentional. Is MSFragger 3.2 not supposed to write an uncalibrated MGF file when the **write_calibrated_mgf** is set to 1 and the file does not go through calibration in the same way that MSFragger 3.0 did? If so, is there an option to write an uncalibrated MGF in the case that there is not enough data to calibrate?

**Comment by fcyu** [comment]
Hi Jacob,

Yes, we stopped writing uncalibrated.mgf when calibration fails for spectral files which is not either `.d` or `.raw`. But, uncalibrated.mgf will always be written with .d and .raw.

Best,

Fengchao

**Comment by jacoblippincott** [comment]
Hi Fengchao, 

Thanks for following up. The file in question is a Thermo file in the .raw format and I am still not seeing an uncalibrated.mgf file. I can perhaps share it with you if it will help but I would need to get permission from our end user first.

**Comment by fcyu** [comment]
Hi Jacob,

I just did a test with a raw file and let the mass calibration fail. There is a uncalibrated.mgf written. If you are sure that the uncalibrated.mgf is not written for you, can you send me your raw file, fragger.params, and fasta file?

Best

Fengchao

**Comment by jacoblippincott** [comment]
Hi Fengchao, 

Sure, let me contact the customer and make sure I can share the raw file. Do you have a link for uploading the raw file? It is not too big but might be too big to attach. Or can I upload larger files by attaching them?

Thanks, 

Jacob

**Comment by fcyu** [comment]
Sure. Here ([https://www.dropbox.com/request/NMcAWyeeE9xAemderbB0](https://www.dropbox.com/request/NMcAWyeeE9xAemderbB0)) is the link to upload the files.

Best,

Fengchao

**Comment by jacoblippincott** [comment]
Uploaded the FASTA, raw file and the params file. Thanks for looking into this. I am using Windows 10 Pro version 10.0.19041 Build 1904 and was running it through the regular Windows command prompt. If you need any more system information please let me know. 

Thanks,
Jacob

**Comment by fcyu** [comment]
Hi Jacob,

I reproduced your issue. I accidently used the latest dev version in my previous test. After checking the git history, it turns out that version 3.2 writes uncalibrated mgf only for `.d` format. Writing uncalibrated.mgf for raw format was added after the release. I apologize that I didn't remember it correctly and all the trouble. For now, I guess the easiest solution is keeping using version 3.1.1. We will release a new version in the near future. Please feel free to let us know if you have any request.

Best,

Fengchao

**Comment by jacoblippincott** [comment]
Hi Fengchao, 

No worries, I am glad you reproduced it. We will have our users use 3.1.1 until you are able to put out a new release with the fix so the uncalibrated.mgf files are written for .raw as well. 

Thanks for looking into this. 

Jacob

**Comment by fcyu** [comment]
No problem.

Best,

Fengchao

**Comment by HijaziHassan** [comment]
Hello Fengchao,

Is the `write_calibrated_mgf` not available in the GUI. I can only see `Write calibrated mzML`. It is easy then to convert to `mgf` but since it is possible using the CLI I wondered why it is not integrated to the GUI.  

Thank you. 
Hassan

**Comment by fcyu** [comment]
It has been deprecated because MGF is bad formatted and not supported by any downstream modules in FragPipe.

Best,

Fengchao
