### ISSUE TITLE
loading of .d bruker files

### ISSUE THREAD

**Issue by PatrickvanZalm** [Nesvilab/MSFragger#157]
Dear MSFragger team,

Today I was keeping track of MSFragger using the 'top-command' on a linux system. I noticed that when it is loading .d bruker files only a single CPU is used, while MSFragger uses multiple. 

If I am correct MSFTBX is used to load those files. Is there a setting I am missing? Or is it automatically set to one? And could this make the loading step quicker?

Best,
Patrick

**Comment by fcyu** [comment]
Hi Patrick,

Yes, you are right. We intentionally use single thread in loading .d because using multi-threading slows it down according to our test.

Best,

Fengchao

**Comment by PatrickvanZalm** [comment]
Hi Fengchao,

Alright. Good to know. Thank you.

Best,
Patrick
