### ISSUE TITLE
mgf is not supported

### ISSUE THREAD

**Issue by singhsk2622** [Nesvilab/MSFragger#161]
Hi 
I am trying to generate spec library from tims-flex DDA raw file. As in manual it says we can use msf file is supported but when i am running DIA-umpire-SpecLib following error is showing 
[log_2021-06-22_10-06-17.txt](https://github.com/Nesvilab/MSFragger/files/6692482/log_2021-06-22_10-06-17.txt)
We  are new to DIA analysis with MSFargger and We are trying to setup DIA analysis in our lab.

**Comment by fcyu** [comment]
DDA analysis without quantification support MGF file, but MS1 scans are required in analyzing DIA data but MGF normally does not have it. You need to convert your raw file to mzML.

Best,

Fengchao

**Comment by anesvi** [comment]
To build the library from DDA files, just select SpecLib workflow. DIA-Umpire_SpecLib workflow is for DIA data, not DDA. And currently it does not support diaPASEF DIA data
Alexey
