### ISSUE TITLE
404 on link in help docs

### ISSUE THREAD

**Issue by nicorellius** [Nesvilab/MSFragger#166]
> MSFragger can search Thermo/Sciex .mzML (conversion tutorial here), Thermo .raw, and Bruker timsTOF .d spectral file formats. For compatibility with complete analysis workflows, see the table on **this page.**

Points to https://msfragger.nesvilab.org/tutorial_fragpipe.html

**Comment by fcyu** [comment]
Fixed.

Best,

Fengchao
