### ISSUE TITLE
Workflows missing

### ISSUE THREAD

**Issue by Dmorgen** [Nesvilab/MSFragger#168]
Hi,

I've downloaded v16, and it's missing the workflow files. could you send the files, please?

Thanks!
David.

**Comment by fcyu** [comment]
Hi David,

I am sorry that I cannot follow it. Are you saying that there is no workflow file in workflow folder? Can you download version 16 and try again? If this issue is still there, can you click the "clear cache and close" button in the "config" tab and try again?

Thanks,

Fengchao

**Comment by Dmorgen** [comment]
Hi,

Yes, I’ve downloaded ver 16, and upon launching the software it says it can’t find the workflows. I’ve check the workflows folder and it’s empty.
Will try.

Thanks!
David.
