### ISSUE TITLE
Protein grouping in protein.tsv output file

### ISSUE THREAD

**Issue by KR-15** [Nesvilab/MSFragger#175]
Hi,

First of all, thanks again for the great work done ! I am a new user of FragPipe so maybe I have missed something:

Is it normal that when I performed a FragPipe analysis using either the "Default" workflow or the "Speclib" workflow, I do not have "protein groups" in the protein.tsv file as we could get with protein_group.txt file output with MaxQuant for instance? Each line is assigned to a unique protein ID.

Thank you in advance for your response.

Kind regards.

KR

**Comment by fcyu** [comment]
We do not have protein groups. Instead, we list the proteins after razor assignment in our file. Each line has one protein.

Best,

Fengchao

**Comment by anesvi** [comment]
Indistinguishable proteins are listed at the end of the raw for each entry. Subsumed proteins that are a part of a larger protein group are not listed in that file. That would be misleading.
