### ISSUE TITLE
Only one enzyme at at time is supported 

### ISSUE THREAD

**Issue by slimyMS** [Nesvilab/MSFragger#176]
Hello,

In my experiment, I use multiple enzymes in my experiment, and some of them were combined in one sample to find the enzyme (combination) that works best.
Unfortunately, it is not possible to define multiple enzymes for one experiment or ideally even groups in which different enzymes are used (as it is possible in other software such as MaxQuant). It would be great if you could add this as a feature.

Best

**Comment by fcyu** [comment]
If all of your enzymes have sense C (cutting at the C-terminal), you can setting the cutting rules by combining your enzymes. For example, if you have trypsin + chymotrypsin, you need to set the `search_enzyme_cutafter` to `KRFLWY`, `search_enzyme_butnotafter` to `P`, and `search_enzyme_name` to `nonspecific`.

Best,

Fengchao

**Comment by slimyMS** [comment]
Thank you for your answer! And sorry for not specifying this before:
Unfortunately, not all of them are cutting at the C-terminal. I do use Trypsin but I also use other enzymes and which cut N-terminal. And I think there is no solution for N-terminal cutting enzymes in general, right?

Best

**Comment by fcyu** [comment]
Added in MSFragger 3.4.
