### ISSUE TITLE
Corrupt Spectra Issue -- Error executing MSFragger: process exited with non-zero status!

### ISSUE THREAD

**Issue by nicorellius** [Nesvilab/MSFragger#177]
Getting an error with Q Exactive HF raw data searched in MSFragger:

```
(ERR) Caused by: io.grpc.StatusRuntimeException: UNKNOWN: Exception was thrown by handler.
(ERR) 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
(ERR) 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
(ERR) 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
(ERR) 	at com.dmtavt.batmass.io.ms.api.ISvcMsFramesIndexedGrpc$ISvcMsFramesIndexedBlockingStub.getFramesByIndex(ISvcMsFramesIndexedGrpc.java:282)
(ERR) 	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.parseRange(ThermoRawFile.java:536)
(ERR) 	at umich.ms.fileio.filetypes.thermo.ThermoRawFile.parse(ThermoRawFile.java:575)
(ERR) 	at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:807)
(ERR) 	at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:791)
(ERR) 	at edu.umich.andykong.msfragger.b.a(Unknown Source)
(ERR) 	at edu.umich.andykong.msfragger.b.a(Unknown Source)
(ERR) 	at edu.umich.andykong.msfragger.E.a(Unknown Source)
(ERR) 	at edu.umich.andykong.msfragger.B.<init>(Unknown Source)
(ERR) 	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
(ERR) 	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
(ERR) 	... 6 more
```

I can search these raw data with Proteome Discoverer and they succeed with the following errors:

```
Warning There were 21 corrupt spectra in the file F1: E:\ticket_44251\FIA13459X002_MS-55_Pleura_surface_92-206343.raw.
Error reading scan no. 41349
```

Is there a workaround I can use to get these data to search in MSFragger but skip the corrupt spectra?

**Comment by fcyu** [comment]
You can try to convert it to mzML (tutorial here: https://fragpipe.nesvilab.org/docs/tutorial_convert.html) to see if the corrupted spectra is still there.

Best,

Fengchao

**Comment by nicorellius** [comment]
I was hoping for an option in MSFragger so I can still load raw files directly.

But, yes, when I run MSConvert to generate mzML, it succeeds but also skips lots of scans (as expected).

However, converting to mzML is not a viable workaround for my workflow in general. Is there not a skip corrupt spectra option in MSFragger?

**Comment by fcyu** [comment]
No, the current version of MSFragger cannot skip corrupted scans. I am not sure if it is a good idea to skip/ignore corrupted scans because something wrong is in the data and skipping them could cause misinterpreted results. We will discuss this suggestion internally.

Best,

Fengchao
