### ISSUE TITLE
Intensity = 0 in the combined_protein.tsv and combined_peptide.tsv

### ISSUE THREAD

**Issue by Sarah-Lennon** [Nesvilab/MSFragger#178]
Dear all,

I have recently downloaded MSFragger 16.0 and upgraded to MSFragger-3.3.jar and philospher 4.0.0. 
I have processed 4 files and all my intensities are 0 in the combined_protein.tsv and combined_peptide.tsv. I am not sure why.
[combined_protein.txt](https://github.com/Nesvilab/MSFragger/files/7204534/combined_protein.txt)

I did the same processing with MSFragger 15.0, MSFragger-3.2.jar and philosopher 3.4.13 and did not encounter this issue. 
[combined_protein.txt](https://github.com/Nesvilab/MSFragger/files/7204547/combined_protein.txt)

Please find enclosed:
- the log file for MS fragger 15
[log_2021-09-21_09-42-29.txt](https://github.com/Nesvilab/MSFragger/files/7204522/log_2021-09-21_09-42-29.txt)
- the config file for MSFragger.15
[Fragpipe_MSFragger15.txt](https://github.com/Nesvilab/MSFragger/files/7204519/Fragpipe_MSFragger15.txt)
- The log file for MSFragger 16
[Uploading log_2021-09-17_17-28-51.txt…]()
- the config file for MSFragger 16
[Fragpipe_16.txt](https://github.com/Nesvilab/MSFragger/files/7204529/Fragpipe_16.txt)

Thank you very much for your help !

Sarah

**Comment by fcyu** [comment]
Hi Sarah,

The key information, the log file for MSFragger 16, is not included in your message. Could you please send us the log?

Thanks,

Fengchao

**Comment by Sarah-Lennon** [comment]
oh yes sorry for that. Here we go
[log_2021-09-17_17-28-51.txt](https://github.com/Nesvilab/MSFragger/files/7204659/log_2021-09-17_17-28-51.txt)
Thank you very much !
Sarah

**Comment by fcyu** [comment]
Hi Sarah,

This is a known bug (https://github.com/Nesvilab/FragPipe/issues/420#issuecomment-894802875). The solution for now is unchecking `print decoys` in `FDR filter and report` panel. It is unchecked by default, could you tell us the reason of checking this box?

Best,

Fengchao

**Comment by Sarah-Lennon** [comment]
Hi Fengchao,

Thank you very much for your fast answer ! I have just tried and indeed it has worked. 
No particular reason to leave the decoys, I checked the box, the first time I used MsFragger to have a closer look at the results and kept it on since. I imported my method from MSFragger 15.0.

Thank you again,

Sarah

**Comment by fcyu** [comment]
You are welcome.

Best,

Fengchao
