### ISSUE TITLE
Not enough memory to MSFragger

### ISSUE THREAD

**Issue by uonnet** [Nesvilab/MSFragger#180]
Hi,

I am getting this error message when running MSFragger
```
Not enough memory allocated to MSFragger.
If running using FragPipe: in MSFragger tab, increase the amount of memory allocated using RAM (Gb) parameter. If your computer does not have enough memory, use “Split database” option (requires python; see Configuration page of FragPipe). Set “Split database” parameter to 2. If the program continues to crash, gradually increase the “Split database” value (e.g. to 4, then to 8, etc.) until the program runs successfully.
Alternatively, or in combination with the “Split database” option, consider the following options: reduce the number of variable modifications specified; reduce the range of allowed peptide length (from 7-50 to e.g. 7-35).
For users running the stand-alone version of MSFragger (i.e. not through FragPipe):  try allocating more memory using the `-Xmx` option.
```
I tried giving MSFragger 350GB of RAM on a cluster and this message still popped up. I just wonder if split database is possible in command-line MSFragger.

Thanks.

**Comment by fcyu** [comment]
We recommend using FragPipe if you want to use split database.

Best,

Fengchao

**Comment by anesvi** [comment]
The Split script comes with FragPipe, so you can take that and run command line too
Just see what command FragPipe runs. I think it should work, Fengchao and Guo Ci?

**Comment by guoci** [comment]
yes, you can click on the `Print Commands` button on the `Run` tab in FragPipe to see the command used.

**Comment by fcyu** [comment]
Yes, it will work.

Best,

Fengchao

**Comment by uonnet** [comment]
Hi,

Thanks for all the suggestion. I found the command in FragPipe and tried running it in command line, but then I saw this error
```
Traceback (most recent call last):
  File "/home/tenn/tools/FragPipe-16.0/fragpipe/tools/msfragger_pep_split.py", line 53, in <module>
    params_txt = param_path.read_bytes().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 50: invalid start byte
```

I checked the fragger.params file and it is in UTF-8. Here is the file in case you need it. Am I missing something? Thanks again.
[fragger.params.txt](https://github.com/Nesvilab/MSFragger/files/7276280/fragger.params.txt)

**Comment by guoci** [comment]
@uonnet can you show me the command you used? The `fragger.params.txt` is fine.

**Comment by guoci** [comment]
try running:
`/home/user01/anaconda3/bin/python3.8 /home/groups/wwlab/user01/tools/FragPipe-16.0/fragpipe/tools/msfragger_pep_split.py 4 "java -jar -Dfile.encoding=UTF-8 -Xmx125G" /home/groups/wwlab/user01/tools/MSFragger-3.3/MSFragger-3.3/MSFragger-3.3.jar /home/groups/wwlab/user01/Data201217-DMS-5564/params/fragger.params <full_path_to_mzML_files>`

**Comment by uonnet** [comment]
Yes this worked! Thanks Fengchao and @guoci !
