### ISSUE TITLE
How to make plain text in-silico digest  by MSFragger

### ISSUE THREAD

**Issue by asepsiswu** [Nesvilab/MSFragger#184]
Hi, I want to use this tool to get some protein in-silico digest sequence and m/z value with kinds of modification. 

I think the pepindex file might contain such infomation, but is not human readable.

Is there any way to to get this?

thanks

**Comment by fcyu** [comment]
No, but I think you can try MS-Digest (https://prospector.ucsf.edu/prospector/cgi-bin/msform.cgi?form=msdigest).

Best,

Fengchao
