### ISSUE TITLE
Error: "Could not create the Java Virtual Machine"

### ISSUE THREAD

**Issue by paolocifani** [Nesvilab/MSFragger#19]
Hi all,

I'm trying to test MSFragger on a single mzML file (1.5GB) and a reference human database from Uniprot (55 MB, including decoys) but MSFragger keeps failing giving the following error:
 Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Invalid maximum heap size: -Xmx10G
The specified size exceeds the maximum representable size.
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stopping MsFragger

I'm using Java 1.8.0_201_b09 (X64). The PC has 512Gb RAM and 23 logical cores. I set MSFragger to perform a closed search with 10Gb RAM and 10 cores. I also set Java runtime parameters as -Xmx100G (so everything should be in large excess compared to the MSFragger settings).

Here is our configuration:
System info:
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_201, Java HotSpot(TM) Client VM, Oracle Corporation
Below I'm copying the log.

Any suggestion to solve this issue?

Thank you,

Paolo Cifani

System info:
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_201, Java HotSpot(TM) Client VM, Oracle Corporation

Version info:
FragPipe version 9.1
MSFragger version 20190222
Philosopher version 20190301 (build 201903011453)

LCMS files:
  Experiment/Group: 
  - C:\Users\KentsisLab\DATA\MSfragger\190220_PC_microR_1E6_a.mzML

9 commands to execute:
Workspace [Work dir: C:\Users\KentsisLab\DATA\MSfragger\Results]
C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\philosopher_windows_amd64.exe workspace --clean
Workspace [Work dir: C:\Users\KentsisLab\DATA\MSfragger\Results]
C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\philosopher_windows_amd64.exe workspace --init
MsFragger [Work dir: C:\Users\KentsisLab\DATA\MSfragger\Results]
java -jar -Dfile.encoding=UTF-8 -Xmx20G C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\MSFragger-20190222.jar C:\Users\KentsisLab\DATA\MSfragger\Results\fragger.params C:\Users\KentsisLab\DATA\MSfragger\190220_PC_microR_1E6_a.mzML
MsFragger
java -cp C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\FragPipe.exe umich.msfragger.util.FileMove C:\Users\KentsisLab\DATA\MSfragger\190220_PC_microR_1E6_a.pepXML C:\Users\KentsisLab\DATA\MSfragger\Results\190220_PC_microR_1E6_a.pepXML
ReportDbAnnotate [Work dir: C:\Users\KentsisLab\DATA\MSfragger\Results]
C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\philosopher_windows_amd64.exe database --annotate C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\171023_UPR_homo_cRAP_withdecoy.fasta --prefix #DECOY#
PeptideProphet [Work dir: C:\Users\KentsisLab\DATA\MSfragger\Results]
C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\philosopher_windows_amd64.exe peptideprophet --decoyprobs --ppm --accmass --nonparam --expectscore --decoy #DECOY# --database C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\171023_UPR_homo_cRAP_withdecoy.fasta 190220_PC_microR_1E6_a.pepXML
ProteinProphet [Work dir: C:\Users\KentsisLab\DATA\MSfragger\Results]
C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\philosopher_windows_amd64.exe proteinprophet C:\Users\KentsisLab\DATA\MSfragger\Results\interact-190220_PC_microR_1E6_a.pep.xml
ReportFilter [Work dir: C:\Users\KentsisLab\DATA\MSfragger\Results]
C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\philosopher_windows_amd64.exe filter --sequential --prot 0.01 --tag #DECOY# --pepxml C:\Users\KentsisLab\DATA\MSfragger\Results --protxml C:\Users\KentsisLab\DATA\MSfragger\Results\interact.prot.xml
ReportReport [Work dir: C:\Users\KentsisLab\DATA\MSfragger\Results]
C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\philosopher_windows_amd64.exe report
~~~~~~~~~~~~~~~~~~~~~~


Workspace [Work dir: C:\Users\KentsisLab\DATA\MSfragger\Results]
C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\philosopher_windows_amd64.exe workspace --clean
INFO[14:45:15] Executing Workspace 20190301                 
INFO[14:45:16] Removing workspace                           
INFO[14:45:16] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: C:\Users\KentsisLab\DATA\MSfragger\Results]
C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\philosopher_windows_amd64.exe workspace --init
INFO[14:45:16] Executing Workspace 20190301                 
INFO[14:45:19] Creating workspace                           
INFO[14:45:19] Done                                         
Process 'Workspace' finished, exit code: 0

MsFragger [Work dir: C:\Users\KentsisLab\DATA\MSfragger\Results]
java -jar -Dfile.encoding=UTF-8 -Xmx20G C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\MSFragger-20190222.jar C:\Users\KentsisLab\DATA\MSfragger\Results\fragger.params C:\Users\KentsisLab\DATA\MSfragger\190220_PC_microR_1E6_a.mzML
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Invalid maximum heap size: -Xmx20G
The specified size exceeds the maximum representable size.
Process 'MsFragger' finished, exit code: 1

Process returned non-zero exit code, stopping
MsFragger
java -cp C:\Users\KentsisLab\DATA\MSfragger\MSFragger-GUI_v3.0\FragPipe.exe umich.msfragger.util.FileMove C:\Users\KentsisLab\DATA\MSfragger\190220_PC_microR_1E6_a.pepXML C:\Users\KentsisLab\DATA\MSfragger\Results\190220_PC_microR_1E6_a.pepXML

**Comment by andytyk** [comment]
Hi Paolo,

That seems strange... that message seems to indicate that you are using a 32-bit Java but your Java version is 64-bit.  Could it be that there are multiple versions of Java installed on your machine and FragPipe is using the wrong one? Try removing 32-bit Java if you don't have software that are dependent on that.

@chhh Dmitry, how does FragPipe determine which Java to use with MSFragger?  Are there any checks to determine if it is 64-bit Java?

Andy

**Comment by chhh** [comment]
@andytyk No, there aren't any checks for 32/64bit. But there's also no good reason to have a 32 bit jvm on a machine with >4GB of memory.

**Comment by paolocifani** [comment]
Actually, a fresh reinstall of Java did the trick. Thanks for pointing me in the right direction!

And by the way, a QC run (90 minutes gradient, whole human cell line tryptic digest) went in about 1 minute. Unbelievable.

Thank you for making the tool available!

Paolo

**Comment by anesvi** [comment]
Good. Note that you can lower precursor tolerance if using QE-HF or Fusion/Lumos data high mass accuracy MS/MS to 20ppm normally

Although 50ppm is Ok as well

If you start doing open searches, or anything less common like timsTOF data  and need assistance, let us know

Best
Alexey
