### ISSUE TITLE
Make precursor_mass_lower == precursor_mass_upper an error

### ISSUE THREAD

**Issue by chambm** [Nesvilab/MSFragger#194]
Or at least a big fat warning. I've probably wasted an hour on 2 separate occasions when I accidentally didn't make precursor_mass_lower negative. The search looks like it's proceeding normally but produces empty output. Thanks in advance for protecting my sanity. :)

**Comment by fcyu** [comment]
Sure, will add an error in the next version.

Best,

Fengchao
