### ISSUE TITLE
How to change localize_delta_mass

### ISSUE THREAD

**Issue by emojica2** [Nesvilab/MSFragger#199]
Hello! I am trying to use FragPipe to run MSFragger and PTM-Shepherd. In Fragpipe, I set the workflow to "open," added my mzML files and database, and changed a couple of parameters (i.e. enzyme, max variable mods on a peptide (5), and precursor mass tolerance (-30 to 30 ppm)). When I run the program, I get the error "It is a closed search while localize-delta-mass = 1. Please change localize_delta_mass to 0." However, I do not see where I can change this value. I would appreciate any help you could give me with this. Thank you!

**Comment by fcyu** [comment]
> precursor mass tolerance (-30 to 30 ppm))

This is what causing the problem. The `precursor mass tolerance` for open search should be like -150 to 500 Da. If you want to change the "real" precursor tolerance, you can adjust `precursor true tolerance` in the `advanced peak matching options` panel. But we don't recommend to do so.

Best,

Fengchao

**Comment by emojica2** [comment]
That is so helpful. Thanks for such a quick reply!

**Comment by fcyu** [comment]
No problem.

**Comment by emojica2** [comment]
So I just tried running the program again, this time with everything set to the normal "open" workflow parameters aside from the enzyme (GluC-bicarb) and the max variable mods on a peptide (5). Now I get the error "FATA[12:48:18] Cannot execute program. there was an error with ProteinProphet, please check your parameters and input files."

The "Run ProteinProphet" line is checked, and the Cmd line opts reads "--maxppmdiff 2000000". Do you have any recommendations for this problem?

**Comment by fcyu** [comment]
Can you send the log file to me? You need to zip the file in case GitHub truncate the text file.

Thanks,

Fengchao

**Comment by emojica2** [comment]
[log_2021-11-24_12-48-18.zip](https://github.com/Nesvilab/MSFragger/files/7598686/log_2021-11-24_12-48-18.zip)

**Comment by fcyu** [comment]
There is no data from the open search:
```
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
 001 | Not enough data to perform mass calibration. Using the uncalibrated data.
-----|---------------|---------------|---------------|---------------
Finding the optimal parameters:
-------|-------|-------|-------|-------|-------|-------|-------|-------
  MS2  |    5  |    7  |   10  |   15  |   20  |   25  |   30  |   50  
-------|-------|-------|-------|-------|-------|-------|-------|-------
 Count |      1|      3|      0| skip rest
-------|-------|-------|-------|-------|-------|-------|-------|-------
-------|-------|-------|-------|-------|-------|-------
 Peaks | 300_0 | 200_0 | 175_0 | 150_1 | 125_1 | 100_1 
-------|-------|-------|-------|-------|-------|-------
 Count |      0|      0|      3|      3|      1| skip rest
-------|-------|-------|-------|-------|-------|-------
-------|-------
 Int.  |    1  
-------|-------
 Count |      0
-------|-------
-------|-------
 Rm P. |    0  
-------|-------
 Count |      2
-------|-------
```
and
```
did not find any PeptideProphet results in input data!  Did you forget to run PeptideProphet?
...read in 0 1+, 0 2+, 0 3+, 0 4+, 0 5+, 0 6+, 0 7+ spectra with min prob 0.05

WARNING: no data - output file will be empty
```

Does your data have chemical labelling or PTM enrichment? Is your data from DDA? Or, can you briefly describe your data so that we can guess why there is no ID from the open search.

Best,

Fengchao

**Comment by emojica2** [comment]
Thanks so much for your help. The data is from DDA. We did not do chemical labelling or PTM enrichment. We enriched the sample for histone proteins though, so we believe that most of the proteins in the sample will be histones that contain PTMs.

**Comment by fcyu** [comment]
Thanks for the info. But these cannot explain getting no ID. 

Is your data from high resolution MS2 (Orbitrap or high-res tof)? If appropriate, can you send one of your mzML to us to take a look?

Best,

Fengchao

**Comment by emojica2** [comment]
I believe so, we used a UHR-qTOF mass spectrometer. I am waiting to hear back from my advisor to see if it is alright to share the mzML file, but if so, could I send that to you over email instead?

**Comment by fcyu** [comment]
Sure. I can give you a link to upload the file if you need one. And we will keep it confidential.

Best,

Fengchao

**Comment by emojica2** [comment]
Hello again, I have permission to send the file! Could we use the link the upload it? (Thanks so much, again!)

**Comment by fcyu** [comment]
Sounds good. Here is the link: https://www.dropbox.com/request/4Nh5u9daHhkqXJeR7if7

Thanks,

Fengchao

**Comment by fcyu** [comment]
Hi @emojica2 ,

Thanks for your file. I tried both 20 ppm and 0.6 Da for the open search, but still cannot get many IDs from your data. Have you tried any other tools that can give a reason amount of IDs?

Best,

Fengchao

**Comment by emojica2** [comment]
Hi Fengchao, 

Thanks so much for looking into that. I am surprised to hear that there were not many IDs. I have used PEAKS XPRO with these files and was able to detect hundreds of PTMs per sample. I dropped a couple more files about that in the link you sent. Do you have any other recommendations for what I might be able to fix here? I really appreciate all of your help.

**Comment by fcyu** [comment]
Wait a minute. The proteins in your uploaded files are not from human.... Can you also upload your fasta file?

Thanks,

Fengchao

**Comment by emojica2** [comment]
Absolutely, I just uploaded it! These samples come from Oreochromis niloticus.

**Comment by fcyu** [comment]
I see that there are two mzML files with the same run name. One seems from mzconverter but is not centroided. This one also have various isolation window, and the largest one is > 4 Th. Currently, MSFragger will not search the DDA data with such a large isolation window because it thinks the data is from DIA.

Best,

Fengchao

**Comment by emojica2** [comment]
Thank you so much for all of your help and for identifying this problem. We will fix that problem.
