### ISSUE TITLE
Updater website link

### ISSUE THREAD

**Issue by chhh** [Nesvilab/MSFragger#2]
We should probably put the updater website download link in the readme here. Any objections?

**Comment by anesvi** [comment]
no

**Comment by chhh** [comment]
@anesvi *No* - as in we shouldn't do that, or *no* - there are no objections?

**Comment by prvst** [comment]
+1

**Comment by anesvi** [comment]
No objection.

We should also start moving MSFragger related questions from FragPipe to there.

Andy was going to write a short description for the MSFragger github site.

Guo Ci needs to list all updates to the code for each version.

Alexey

**Comment by prvst** [comment]
we can migrate the existing open and closed msfragger tickets from fragpipe repo to msfragger repo

**Comment by fcyu** [comment]
I think we should also deal with this one [https://github.com/chhh/MSFragger-GUI](https://github.com/chhh/MSFragger-GUI)
