### ISSUE TITLE
Documentation. End-to-end examples for command line users.

### ISSUE THREAD

**Issue by ivandatasci** [Nesvilab/MSFragger#202]
Hi everyone.

Could anybody point me to end-to-end examples to run MSFragger and/or FragPipe **entirely at the command line**?

End-to-end would be from .mzML files to .csv files that I could feed into MSstats.

I am interested in both label-free quantification and TMT.

Thank you.

Ivan

**Comment by fcyu** [comment]
Hi Ivan,

Here (https://github.com/Nesvilab/MSFragger/wiki) is the doc for MSFragger parameters. 
Here (https://fragpipe.nesvilab.org/) contains tutorials for FragPipe.

If you are interested in running FragPipe in command line, here (https://github.com/Nesvilab/FragPipe/issues/560#issuecomment-999748399) is the headless FragPipe.

Best,

Fengchao
