### ISSUE TITLE
Bruker libraries not found

### ISSUE THREAD

**Issue by Munchic** [Nesvilab/MSFragger#205]
Hello! I'm trying to run MSFragger inside a Docker container based on Ubuntu 16.04. The command I'm running:
```
java -Xmx16g -jar /MSFragger-3.4/MSFragger-3.4.jar /MSFragger-3.4/closed_fragger.params /data/20180924_50ngHeLa_1.0.25.1_Hystar5.0SR1_S2-A1_1_2042.d
```

The error that I get:
```
ERROR Timsdata - The ext folder with timsdata-2-8-7-1.dll (Win) or libtimsdata-2-8-7-1.so (Linux) is needed. If you are using an old ext folder, please upgrade.
```

I am aware that there was a similar ticket before and that the `ext` folder should be at the same level with the `.jar` executable which is what I have:
```
root@293ff0d813a4:/MSFragger-3.4# ls 
MSFragger-3.4.jar                MSFragger-LICENSE.pdf      RawFileRdr_License_Agreement_RevA.pdf  closed_fragger.params  nonspecific_fragger.params  redist.txt
MSFragger-LICENSE-3RD-PARTY.txt  Nglyco-HCD_fragger.params  THIRD-PARTY-LICENSE-README.txt         ext                    open_fragger.params         version.txt
```

Inside `ext/bruker` folder it looks like this:
```
root@293ff0d813a4:/MSFragger-3.4/ext/bruker# ls
THIRD-PARTY-LICENSE-README.txt  libtimsdata-2-7-0.so  libtimsdata-2-8-7-1.so  redist.txt  timsdata-2-8-7-1.dll  timsdata-2-8-7-1.lib
```

The file `libtimsdata-2-8-7-1.so` is just a duplicate of `libtimsdata-2-7-0.so` I made in case that's the version that's checked, with or without it I still get the same error. I also tried to duplicate and name `libtimsdata.so` (which is what `redist.txt` seems to be asking for). Please let me know if I am doing something wrong.

In the future, do you think it's possible to configure the location of `ext` folder from within `fragger.params`? I feel like that would eradicate issues with finding path to the libraries. Thank you so much for your help!

**Comment by fcyu** [comment]
Do you have mono installed?

Best,

Fengchao

**Comment by Munchic** [comment]
Hi Fengchao @fcyu,

Installing `mono` solved the issue, thank you so much for your help!
