### ISSUE TITLE
MGF files size/spectra count limit

### ISSUE THREAD

**Issue by andzajan** [Nesvilab/MSFragger#209]
Hi, I have MGF file with deisotoped spectra and file size is 2.5GB (93610755 lines). Msfragger refuses to process this file and reports 0 spectra found. If I copy few spectra from this file to the smaller file it does proceed with processing this subset.

Is there any limit on  MSFragger for mgf file size or spectra count?

```
MSFragger [Work dir: D:\Br\CE_mgf_msfragger_out]

Checking spectral files...
Failed in checking D:\Br\CE_merged_spectra.mgf
-2096118620
Failed in checking spectral files.
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
D:\Br\CE_merged_spectra.mgf: Scans = 0

~~~~~~~~~~~~~~~~~~~~
Cancelling 11 remaining tasks

```

**Comment by fcyu** [comment]
Yes, there is a 2GB limit in current version.

Best,

Fengchao

**Comment by andzajan** [comment]
Thank you for a quick response, can I just confirm that if I split my file in multiple mgf's and then in `PSM validation` with PeptideProphet activate chekcbox `Single combined pepxml file per experiment / group` it will apply FDR correction correctly?

BW,
Andris

**Comment by fcyu** [comment]
Yes, if you put your mgf files in one experiment/group.

Best,

Fengchao
