### ISSUE TITLE
Poor results on HLA-II file, possibly user error?

### ISSUE THREAD

**Issue by zrolfs** [Nesvilab/MSFragger#21]
Hello!
I'm attempting to analyze a DDA HLA-II immunopeptide file using FragPipe (v9.1) with MSFragger (v20190222) and Philosopher (v20190405). It wasn't clear on what executable to include for Python (or if that was needed), so I left that blank. 
I was able to make it through the run in record time, but the results weren't quite what I was expecting. Specifically, over half of the reported identifications in psm.tsv, peptide.tsv, and protein.tsv were reverse/decoy sequences with high scores. When I analyze the same file with MetaMorpheus, I got ~6000 PSMs, ~4000 peptides, and ~700 proteins at a 1% FDR, so I don't think it's an issue with the MS file. Am I interpreting the output correctly, or is there anything wrong with my fragger.params? I had simply clicked the "Non-specific Search" option and then changed the precursor mass tolerances to +-5 ppm. 
I've uploaded the relevant files [here](https://uwmadison.box.com/s/kc0oh51u9o4no9ax52c6ez6e5eioafjl).
Thank you for your help!

**Comment by anesvi** [comment]
I think your database was formatted in a way that caused a problem. The ID numbers (from filter.log) look OK. But I will check myself too what I get for your file.

I asked Felipe to take a look at your database

Best,
Alexey

**Comment by fcyu** [comment]
Hi,

Could you change the "Decoy tag" under "Sequence DB" tab to "rev_"?

I tried with the following codes under your folder, I got 8830 PSMs without any decoy protein in the "Protein" column. While I can reproduce your error by replacing "rev_" with "rev_sp".
```shell
philosopher_windows_amd64.exe workspace --clean
philosopher_windows_amd64.exe workspace --init
philosopher_windows_amd64.exe database --annotate 180904_Human_Uniprot_Reviewed_CanonicalFORWARDandREVERSED.fasta --prefix rev_
philosopher_windows_amd64.exe filter --sequential --razor --mapmods --prot 0.01 --tag rev_ --pepxml interact-20170609_qeh1_lc1_chch_fama_sa_hlaiip_jy_210417_2_r1.pep.xml --protxml interact.prot.xml
philosopher_windows_amd64.exe report
```

Bests,

Fengchao

**Comment by prvst** [comment]
@zrolfs 

You defined the decoy tag as being `rev_sp`, so basically everything in your database was flagged as decoy. You can still you your file as it is but try with `--decoy rev_sp` instead.

if you are using a standard database from UniProt or NCBI, I suggest getting the sequences with the standard header, this way your report file will have more information about the proteins.

**Comment by chhh** [comment]
@zrolfs If you use [FragPipe](https://github.com/Nesvilab/FragPipe) GUI to run MSFragger, its Dabatase definition section has a button to auto-detect prefixes/suffixes in your DB identifiers that might potentially mark decoys (it'll tell you the percentage of entries that share a suffix or a prefix). When unsure what to use in the command line version of MSFragger, you can use that tool first to check.

**Comment by anesvi** [comment]
Ok, it looks like the issue is resolved. Thanks everybody.

@Zrolf note that you do not need python unless you need to do database splitting.  If you allow more modifications or longer peptides for nonspecific searches, you will need that.

Best
Alexey

**Comment by zrolfs** [comment]
Thanks everyone for your help! The "rev_sp" was definitely the issue. 
@chhh I was using the FragPipe GUI and it recommended "rev_sp" (see attached). Not sure if that's something that can be easily fixed. 
![image](https://user-images.githubusercontent.com/16883585/56066115-7262a880-5d3c-11e9-8c70-f7e6f172a6bf.png)

**Comment by chhh** [comment]
@zrolfs Interesting, I just downloaded your DB and that looks to be correct - all decoys do start with "rev_sp|..." and regular ones with just "sp|...". So the broken logic must be somewhere further downstream.

**Comment by anesvi** [comment]
Dmitry, I emailed Felipe to check why philosopher had an issue. It worked fine until the final report generation step in philosopher.

**Comment by prvst** [comment]
Nothing broken here. By definition the decoy is a prefix added to a header
to mark it as artificial, parts of the protein header should not be used as
decoy prefix.

Internally, philosopher will strip the prefix from the header when
processing the database during the annotation indexing, so just stick with
rev_ (or similar) and don't use the database name as decoy flag.
