### ISSUE TITLE
output_report_topN adjusted when data_type = 0

### ISSUE THREAD

**Issue by asalt** [Nesvilab/MSFragger#214]
Hello. I am running a search with `data_type = 0` (I did not set this variable, set by default). I notice this message with regard to output:

`data_type = 0 and output_report_topN > 1. Change output_report_topN to 1.`

Is this intended behavior? The changelog says this adjustment is performed for DIA, but does this also apply to DDA (data_type 0) ?

**Comment by fcyu** [comment]
Yes, this is an intended behavior in 3.4. We will stop changing it to 1 in the future release.

Best,

Fengchao
