### ISSUE TITLE
.pepXML not found using PD-node (PD 2.4 ) with MsFragger-3.3

### ISSUE THREAD

**Issue by seongminlab** [Nesvilab/MSFragger#218]
Dear Developers

i  endeavor to running MsFragger through our PD-2.4 server with PD-node. 
The only problem is when trying a search (using ThermoRawFiles, with 24 Fractionation files), the processing workflow is stopping and errors out as it cannot find the .pepXML file.
pepXML format files cannot found in my temporary directory.

I think it's same problems like this issues
https://github.com/Nesvilab/MSFragger/issues/31

PD 2.4 running on Window 10, 64bit  with PD-node 1.1.0 and MsFragger3.3
JAVA version is 18.0.1.1  2022-04-22
.Net version 4.8.4084.0

I was solve the java problem " Could not create the Java Virtual Machine?" by java updates
And i can see running message of MsFragger But workflow is stopping when the spectrum selector process at finished.

**Comment by seongminlab** [comment]
I solve that problem with .NET update!! 

But PD stopped on consensus step (88%,  during spectrum quantification..)

**Comment by fcyu** [comment]
Please switch to FragPipe if there are any issues using the MSFragger PD-node.

Best,

Fengchao
