### ISSUE TITLE
num_enzyme_termini = 3 documentation

### ISSUE THREAD

**Issue by Skourtis** [Nesvilab/MSFragger#219]
Hi, 

I'm trying to figure out Semi_N_Term Cleavage does, as I'm trying to identify peptides without enzyme specific cleavage in the nterminal of proteins, but specific in the c-term. 

My params files gives num_enzyme_termini = 3, where as the documentation gives these options: Number of enzyme termini (0 for non-enzymatic, 1 for semi-enzymatic, and 2 for fully-enzymatic).

Is there a resource where I can find what num_enzyme_termini = 3 does or a better way to search for n-term unspecific cleavage protein products?

Thank you

**Comment by Skourtis** [comment]
Thank you for letting me know!

Last question, looking at the natural occuring n-term peptides, they all contain the [42.0106] actyl modification after Methionine removal. 
The peptides which are identified with the semi_n_term and are non-specific trypsin cleaved, almost never have this n-term actyl modification. 

Does MSFragger treat these non-specific n-term peptides, as possible novel protein n-term (which should also have the n-term 
 [42.0106]  actyl modification) or it doesn't consider  [42.0106]  for those peptides?
 
 Thank you,
Savvas

**Comment by fcyu** [comment]
Hi Savvas,

The new protein N-term after clipping the first Methionine is treated as natural protein N-term, so there will be acetylation if you set the variable modification.

As to the new protein N-term after non-specific cleavage, I don't think we treat it as the natural protein N-term. 

In a word, acetylation happens on the original protein N-term and the new protein N-term after clipping the first Methionine, no matter what enzyme you are using.

Best,

Fengchao

**Comment by Skourtis** [comment]
Hi Fengchao,

I thought I could use this feature to detect novel protein N-termini (which would have the N-acetyl) but this sounds more useful for detect enzymatic, not biological n-termi. So I not use it. 

Thank you for the reply!

**Comment by fcyu** [comment]
I am not sure if I follow it. Protein N-term acetylation is set as a variable modification (not all protein N-terms have acetylation) by default, so, you will still get novel protein N-term without acetylation.

If you really want to detect acetylated novel protein N-termini, you can set acetylation to peptide N-term using the mark `n^`.

Best,

Fengchao
