### ISSUE TITLE
Unimod / PSI Mod ontology support

### ISSUE THREAD

**Issue by prvst** [Nesvilab/MSFragger#23]
Add support for different modifications ontologies and make it possible to define modifications names on the parameter file.

**Comment by Nazrath10R** [comment]
I am planning to do an "exhaustive" search with many PTMs. Is there any way to add or specify variable mods using UniMod id, PSI Mod or import from SearchGUI etc.?

**Comment by anesvi** [comment]
MSFragger is not the best tool for exhaustive” PTM search. It will run out of memory.
Instead, you can do open search, and then see what mass shifts you identify and what entries in UniMod they map to
