### ISSUE TITLE
Scan type HCD not recognized

### ISSUE THREAD

**Issue by JB91451** [Nesvilab/MSFragger#235]
Dear all,

in order to use the very same peaklist files for different search engines, I had to convert some of my files to mzXML before searching them. When I use these files with MSFragger 3.5 I get a warning message during file checking and calibration saying: 
"Activation type HCD not recognized, activation filtering may be inconsistent! Please contact the developers to fix and/or disable activation type filtering"
The files originate from a QExactive plus measurement in DDA mode and were converted via msconvert. Within the mzXML files, msLevel=2 scans have a tag 'activationMethod="HCD"' along with the precursor information. Also, the number of scans displayed during parameter optimization for each file seems valid. Therefore I would like to ask, whether it is save to ignore this warning (I have not mixed activation schemes etc.)?

Best regards,
Juergen

Please find the used parameter file here. 'activation_types = HCD' had to be specified as without this information the searches immediately stopped.:
[PPutida_Proteogenomics_semiLysC_MSFragger.params.txt](https://github.com/Nesvilab/MSFragger/files/9584219/PPutida_Proteogenomics_semiLysC_MSFragger.params.txt)

Below is an example for a MS2 scan in the mzXML files:

    <scan num="3702"
          scanType="Full"
          centroided="1"
          msLevel="2"
          peaksCount="366"
          polarity="+"
          retentionTime="PT1688.78S"
          collisionEnergy="27.5"
          lowMz="100.076606750488"
          highMz="1009.432556152344"
          basePeakMz="120.0816037"
          basePeakIntensity="5.7522012e05"
          totIonCurrent="2.891132e06"
          msInstrumentID="1">
      <precursorMz precursorScanNum="3700" precursorIntensity="8.67563701931e05" precursorCharge="3" activationMethod="HCD" windowWideness="3.0">334.5353245056</precursorMz>
      <peaks compressionType="none"
             compressedLen="0"
             precision="64"
             byteOrder="network"
             contentType="m/z-int">QFkE5yAAAABAjU1iwAAAA...</peaks>
    </scan>

**Comment by fcyu** [comment]
Hi Juergen,

Can you send on of the mzXML file to us?

Thanks,

Fengchao

**Comment by JB91451** [comment]
Hi Fengchao,

if you would open me a box folder, I can try to do so. However, the files are really large (8-12 Gb).

**Comment by fcyu** [comment]
Sure, here it is: https://www.dropbox.com/request/WG7nJrF13dPr22XpthE4

Best,

Fengchao

**Comment by JB91451** [comment]
Thanks, it should upload. I also added the mzbin, search results (which seem good to me) and the fasta.

Best,
Juergen

**Comment by fcyu** [comment]
Hi Juergen,

FYI, the dropbox folder is still empty. Are you still uploading the files?

Best,

Fengchao

**Comment by JB91451** [comment]
Hi Fengchao,

thank you for informing me. There was a web-connection error with our server and thus the upload failed. Meanwhile it should be finished as I repeated it and got a confirmation.

Best,
Juergen

**Comment by fcyu** [comment]
Hi Juergen,

Thanks for your files. I couldn't reproduce the warning message. Everything looks good from my test. Attached please find the log file.

Best,

Fengchao
[log.txt](https://github.com/Nesvilab/MSFragger/files/9599728/log.txt)

**Comment by JB91451** [comment]
Dear Fengchao,

Thank you for checking this. I still get the same error but as the number of spectra is the same as in your log file I guess I can simply ignore it?!

Best,
Juergen

**Comment by fcyu** [comment]
I don't know if it is safe to ignore it. I think you need to troubleshoot from your side.

Best,

Fengchao

**Comment by dpolasky** [comment]
Hi Juergen,
If you remove the `activation_types=HCD` parameter from the MSFragger parameters file (or change it to `activation_types=all`), the message should go away. Unless you need to filter in a file with multiple activation types, this parameter shouldn't be needed, and any unexpected behavior from trying filtering an mzXML file can be avoided. 
Best,
Dan

**Comment by JB91451** [comment]
Thank you both for your recommendations. I will try to run it with activation_types=all (I added the HCD as leaving this parameter blank did not work at the beginning) and try in parallel with the original raw files. However, I am quite optimistic that the results will be identical or close.

Thanks again,
Juergen

**Comment by dpolasky** [comment]
Yes for activation type filtering we probably won't support mzXML (unless there's a lot of demand for it), but can change it so that it doesn't try to filter rather than giving this scary error message

**Comment by fcyu** [comment]
@danielgeiszler Actually, the mzXML format has the activation method information:
```
<precursorMz precursorScanNum="839" precursorIntensity="3.544250343306e06" precursorCharge="2" activationMethod="HCD" windowWideness="3.0">324.172088534973</precursorMz>
```

I guess we can do something to recognize it.

Best,

Fengchao

**Comment by dpolasky** [comment]
yes the info is there in mzXML so we could support it, just need to test to find all the different ways it can be reported by different instruments/vendors

**Comment by fcyu** [comment]
I tested it with `activation_types = HCD`. MSFragger actually can recognize the activation type from mzXML format. And there are still no error messages. Then, I am not sure why @JB91451 got it,

Best,

Fengchao

**Comment by JB91451** [comment]
Dear all,

I tried with `activation_types = all` over night and there is no warning anymore. As the files are identical to the ones produced with HCD filtering I think it was safe in my case to ignore the warning (at least in my case). Nonetheless I will use the files created without filtering to be sure.

Many thanks again,
Best,
Juergen
