### ISSUE TITLE
PRM-PASEF data

### ISSUE THREAD

**Issue by tobimaile** [Nesvilab/MSFragger#238]
Hi all,

Quick question: How would you run PRM-PASEF files on MSFragger? DDA settings or no?

Thanks,
Tobi

**Comment by fcyu** [comment]
Hi Tobi,

I think you can use the DDA settings. 

We have made MSFragger support the prmPASEF data format, but didn't thoroughly test it. Please feel free to contact if you have any questions and feedback.

Thanks,

Fengchao
