### ISSUE TITLE
Issue with reading files for analysis

### ISSUE THREAD

**Issue by RonenGabizon** [Nesvilab/MSFragger#240]
I am trying to analyze DDA data from file but I keep having problems reading the files and it seem to be memory related. 
[log_2022-10-20_11-58-01.txt](https://github.com/Nesvilab/MSFragger/files/9828176/log_2022-10-20_11-58-01.txt)

**Comment by RonenGabizon** [comment]
Does that refer to hard drive memory or RAM? Because we analyzed data sets of similar sizes in the same day without any issues with the same allocated memory.

**Comment by fcyu** [comment]
It is related to RAM. There were only 8 GB free memory available to MSFragger. Maybe the computer had other programs running that used part of the memory. 

As to you could run it with another dataset with the similar size, could you send us the log file if you want me to take a look?

Best,

Fengchao
