### ISSUE TITLE
Custom ion series

### ISSUE THREAD

**Issue by carlomartins** [Nesvilab/MSFragger#242]
Hi everyone!
I have an issue similar, but not the same, as in the thread #151.
I suspect that one particular PTM leaves behind fragments that are losing a specific mass (it is not the precursor losing the mass - as in an offset search, but the fragments).
So, I decided to define a custom ion series, which would be 't0 N -33'.
However, Fragpipe launches an error saying that 'ion type must be one of [a, b, c, b-18, b~, x, y, z, y-18, y~, Y]' before starting any search. Then, I add this name 't0' to the 'Fragment ion series'.
I use FragPipe (v18.0), with MSFragger (v3.5).
Maybe there is a mistake that I cannot see in my settings?
Thank you,

**Comment by fcyu** [comment]
Where did you put the custom ion type"? It should be "define custom ion series", not "fragment ion series".

Best,

Fengchao

**Comment by carlomartins** [comment]
Hi Fengchao,
Thank you for your reply.
I defined the ion type under 'Define ion series', but I also added the name
of this fragment to 'Fragment ion series'.
Even if I don't add this name to the ion series, or use another name for
it, such as 't*', the search crashes.
Best,
Carlo

**Comment by carlomartins** [comment]
Many thanks for this!
It is working now, using your Params file. I am not sure why, but the
difference is that in my 'Peak matching', I had set 'Fragment mass
tolerance' to 0.2 Da, because I am fragmenting in an IonTrap. It crashes
with this setting. When I change to 20 ppm, the search goes through.
Thank you,
Carlo

**Comment by fcyu** [comment]
Can you send me your log file from your crashed task?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Also, please DO NOT directly use my parameter file because that is a fake one. Some of the settings are not correct.

You also need to give the precise mass values rather than `-33` in your `t0 N -33`.

Best,

Fengchao

**Comment by fcyu** [comment]
Thank you for your log file. The issue is actually due to a bug in FragPipe. I have fixed it in https://github.com/Nesvilab/FragPipe/commit/83349d70e9b4cef2e57e4a88a064c3b137ba8282

Best,

Fengchao

**Comment by ankittjain89** [comment]
Hi
I have been trying to do a similar search with (z* N -56.9976; c* N +58.0054) custom fragments to specifically locate isoAspartate containing peptides using ETD/ECD data. I am unable to generate a spectral library so that I can used the results to view the peptides and the fragments in Skyline. Or is there a way to specifically look for peptides identified with the custom fragment.

Thanks
Ankit
[log_2023-08-01_12-02-28.txt](https://github.com/Nesvilab/
[IsoAsp_ECDfragments.zip](https://github.com/Nesvilab/MSFragger/files/12232141/IsoAsp_ECDfragments.zip)
MSFragger/files/12232122/log_2023-08-01_12-02-28.txt)

**Comment by fcyu** [comment]
Hi Ankit @ankittjain89 ,

The error was from IonQuant but you do not need to run IonQuant if you just want to build a spectral library.

BTW, the spectral library won't have customized fragment ions although you used it in the MSFragger search.

Best,

Fengchao
