### ISSUE TITLE
Define custom ion series

### ISSUE THREAD

**Issue by gocome** [Nesvilab/MSFragger#248]
I tried to run MSFragger-3.6 on FraPipe (v19.0) with a custom ion type. If the custom ion type is added to 'Fragment ion series', I would obtain the following error message:
![image](https://user-images.githubusercontent.com/9533387/207440356-22324bdc-b3af-463c-baf1-ed6c170189ab.png)
![image](https://user-images.githubusercontent.com/9533387/207440270-45cd41e8-6ff3-4cc4-a152-ab78003a665c.png)

Alternatively, if the custom ion type is not added to 'Fragment ion series', a different error message would appear:
![image](https://user-images.githubusercontent.com/9533387/207440045-705b5776-7a87-478b-a09d-758ba37f9330.png)
![image](https://user-images.githubusercontent.com/9533387/207439865-2b655bfb-8e9c-44b5-8846-fff66bc95a3c.png)

If N-terminal is used in the custom ion type instead of C-terminal, MSFragger still cannot make through. Is there any problem in my custom ion type setup? Any help would be greatly apppreciated.

**Comment by fcyu** [comment]
HI @gocome ,

Can you change `z1` to `z`, and try again?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Hi @gocome ,

Actually, I was wrong. I think a bug was introduced after version 3.5, which caused the crash. Stay tuned.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi @gocome ,

I have fixed the bug. If you want to use the fixed version, could you send an email to yufe AT umich.edu?

Best,

Fengchao

**Comment by gocome** [comment]
Hi Fengchao,

Thank you very much for quick response.

Best,
Xin
