### ISSUE TITLE
Batmass-IO binaries for Thermo support and/or Thermo native libraries not found

### ISSUE THREAD

**Issue by qussai96** [Nesvilab/MSFragger#249]
Dear Fengchao,

I am trying to run MSFragger on my Linux machine (Rocky Linux 8.6) using the following command:

` java -Xmx64g -jar ~/Tools/MSFragger-3.6/MSFragger-3.6.jar /home/AT/0-raw_data/Proteomes/closed_fragger.params /home//AT/0-raw_data/Proteomes/01898_A01_P019768_S00_I00_N01_R1.raw`

I am getting the following error:

```
MSFragger version MSFragger-3.6
Batmass-IO version 1.28.8
timsdata library version timsdata-2-21-0-4
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
timdTOF .d reading tool. Copyright (c) 2022 by Bruker Daltonics GmbH & Co. KG. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 11.0.13, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
JVM started with 64 GB memory
Checking database...
Parameter 'diagnostic_intensity_filter' was not supplied. Using default value: 0.000000
Parameter 'activation_types' was not supplied. Using default value: 
Parameter 'ion_series_definitions' was not supplied. Using default value: 
Parameter 'Y_type_masses' was not supplied. Using default value: 
Parameter 'diagnostic_fragments' was not supplied. Using default value: 
Checking spectral files...
Failed in checking /home/AT/0-raw_data/Proteomes/01898_A01_P019768_S00_I00_N01_R1.raw. Will ignore it.
Batmass-IO binaries for Thermo support and/or Thermo native libraries not found
/home/AT/0-raw_data/Proteomes/01898_A01_P019768_S00_I00_N01_R1.raw: Scans = 0
There are corrupted files. Please remove those files and re-start the task.
```

I checked the MSFragger folder and it contains 'MSFragger-3.6.jar' and the 'ext' folder (with two subfolders: thermo and bruker).
I tried with two versions of MSFragger but still got the same error. Can you please let me know if you have any ideas why is that happening?

best,
Qussai

**Comment by fcyu** [comment]
Hi Qussai,

Have you installed mono?

Best,

Fengchao

**Comment by qussai96** [comment]
No, I had not installed it before. I just installed it and that fixed the problem.
Thank you very much.

best,
Qussai

**Comment by fcyu** [comment]
You are welcome.

Best,

Fengchao
