### ISSUE TITLE
MSFragger CLI Parameter File Issue

### ISSUE THREAD

**Issue by thinkle12** [Nesvilab/MSFragger#254]
Hi all, I am using the CLI version of MSFragger (Version 3.7). I have a slight issue with the `decoy_symbol` parameter.
The database I am using has decoy symbol of ## double pound sign. However, It doesnt appear that this is an acceptable symbol as "#" in the parameter file is a comment.

I have tried many options:
1. ##
2. "##"
3. '##'
4. \\#\\#
5. '\\#\\#'

None of these work to actually input the proper decoy symbol into MSFragger itself. Is there a way to actually have the parameter parser be able to read the # symbol?

I was wondering is there any way to get this to work? If not how important is the decoy symbol? Per the parameters it says this:
`decoy_prefix = rev_                         # Prefix of the decoy protein entries. Used for parameter optimization only.` So is it only used for parameter optimization?

However, I noticed that if we write out `.pin` that all PSMs are labeled as target and nothing gets labeled as decoy. Makes sense but this is rather unfortunate because we want to use the the `.pin` and we dont want to rewrite our databases. Any thoughts?

**Comment by fcyu** [comment]
You should use other string as the decoy prefix. Replacing all `#` with others should be quite easy. And as you already found out, setting the correct decoy prefix matters for the pin file.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi @thinkle12 ,

We have fixed this issue. Could you send an email to yufe AT umich.edu if you want to test the pre-released version?

Thanks,

Fengchao

**Comment by thinkle12** [comment]
Hi @fcyu Thanks a lot. Is there an ETA for the next release? We have been running 3.7 IIRC. Will this next release be 3.8? We package things up into a docker image to run MSFragger so we might need to just wait for the release

**Comment by fcyu** [comment]
There is no ETA for now.

Best,

Fengchao

**Comment by fcyu** [comment]
The new released MSFragger 3.8 fixes this bug: https://msfragger.arsci.com/upgrader/

Best,

Fengchao
