### ISSUE TITLE
Problem when running MSFragger on Mac

### ISSUE THREAD

**Issue by nttvy** [Nesvilab/MSFragger#258]
Hi authors,

Thanks for MSFragger. But I get the following error when trying to run MSFragger on my Mac (M1 pro, Ventura 13.3):

`java -jar MSFragger-3.7.jar open_fragger.params_edited data/W_N18/*.d
`

> MSFragger version MSFragger-3.7
> Batmass-IO version 1.28.9
> [main] ERROR umich.ms.fileio.filetypes.bruker.Timsdata - JNA could not load native Bruker library
> [main] ERROR umich.ms.fileio.filetypes.bruker.Timsdata - The ext folder with timsdata-2-21-0-4.dll (Win) or libtimsdata-2-21-0-4.so (Linux) is needed. If you are using an old ext folder, please upgrade.
> timsdata library version 
> (c) University of Michigan
> RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
> timdTOF .d reading tool. Copyright (c) 2022 by Bruker Daltonics GmbH & Co. KG. All rights reserved.
> System OS: Mac OS X, Architecture: x86_64
> Java Info: 11.0.18, OpenJDK 64-Bit Server VM, Eclipse Adoptium
> JVM started with 8 GB memory
> Checking database...
> Parameter 'diagnostic_intensity_filter' was not supplied. Using default value: 0.000000
> Parameter 'ion_series_definitions' was not supplied. Using default value: 
> Parameter 'Y_type_masses' was not supplied. Using default value: 
> Parameter 'diagnostic_fragments' was not supplied. Using default value: 
> Checking spectral files...
> Failed in checking /Users/vy/Downloads/MSFragger-3.7/data/W_N18/wash_homemade_column0812_one_column_Slot1-02_1_1861.d. Will ignore it.
> Bruker native libraries not found. If you are using Windows, please make sure that Visual C++ Redistributable for Visual Studio 2017 (https://aka.ms/vs/16/release/VC_redist.x64.exe) is installed. If you are using Linux, please maks sure that all dependencies are installed (can check using ldd command).
> Failed in checking /Users/vy/Downloads/MSFragger-3.7/data/W_N18/wash_homemade_column0812_one_column_Slot1-02_1_1861.d. Will ignore it.
> Bruker native libraries not found. If you are using Windows, please make sure that Visual C++ Redistributable for Visual Studio 2017 (https://aka.ms/vs/16/release/VC_redist.x64.exe) is installed. If you are using Linux, please maks sure that all dependencies are installed (can check using ldd command).
> Failed in checking /Users/vy/Downloads/MSFragger-3.7/data/W_N18/W_N18_20220916_Neoantigen_HM0812_one_column_Slot1-45_1_1864.d. Will ignore it.
> Bruker native libraries not found. If you are using Windows, please make sure that Visual C++ Redistributable for Visual Studio 2017 (https://aka.ms/vs/16/release/VC_redist.x64.exe) is installed. If you are using Linux, please maks sure that all dependencies are installed (can check using ldd command).
> Failed in checking /Users/vy/Downloads/MSFragger-3.7/data/W_N18/wash_homemade_column0812_one_column_Slot1-02_1_1862.d. Will ignore it.
> Bruker native libraries not found. If you are using Windows, please make sure that Visual C++ Redistributable for Visual Studio 2017 (https://aka.ms/vs/16/release/VC_redist.x64.exe) is installed. If you are using Linux, please maks sure that all dependencies are installed (can check using ldd command).
> /Users/vy/Downloads/MSFragger-3.7/data/W_N18/wash_homemade_column0812_one_column_Slot1-02_1_1863.d: Scans = 0
> /Users/vy/Downloads/MSFragger-3.7/data/W_N18/wash_homemade_column0812_one_column_Slot1-02_1_1862.d: Scans = 0
> /Users/vy/Downloads/MSFragger-3.7/data/W_N18/wash_homemade_column0812_one_column_Slot1-02_1_1861.d: Scans = 0
> /Users/vy/Downloads/MSFragger-3.7/data/W_N18/W_N18_20220916_Neoantigen_HM0812_one_column_Slot1-45_1_1864.d: Scans = 0
> There are corrupted files. Please remove those files and re-start the task.
> 

I got to know that MSFragger can run on Mac, but it seems that the Bruker library is not available (in the zip) for MacOS. And the software can really detect MacOS but it keeps giving instructions for Windows users.

In the same folder: 
`ls -la`

> total 139016
> drwxrwxr-x@   17 vy  staff       544 Apr  6 17:47 .
> drwx------@ 8203 vy  staff    262496 Apr  6 17:40 ..
> -rw-r--r--@    1 vy  staff      6148 Apr  6 17:36 .DS_Store
> -rwxrwxr-x@    1 vy  staff  57084253 Jan 12 16:17 MSFragger-3.7.jar
> -rw-rw-r--@    1 vy  staff     68024 May 14  2022 MSFragger-LICENSE-3RD-PARTY.txt
> -rw-rw-r--@    1 vy  staff     69467 Jan 28  2020 MSFragger-LICENSE.pdf
> -rw-rw-r--@    1 vy  staff     14018 Jan 12 10:44 Nglyco-HCD_fragger.params
> -rw-rw-r--@    1 vy  staff    107720 Sep  2  2019 RawFileRdr_License_Agreement_RevA.pdf
> -rw-rw-r--@    1 vy  staff     41725 Sep  2  2019 THIRD-PARTY-LICENSE-README.txt
> -rw-rw-r--@    1 vy  staff      9957 Jan 12 10:44 closed_fragger.params
> drwxr-xr-x     4 vy  staff       128 Apr  6 17:13 data
> drwxrwxr-x@    5 vy  staff       160 Apr  6 17:36 ext
> -rw-rw-r--@    1 vy  staff      9957 Jan 12 10:44 nonspecific_fragger.params
> -rw-rw-r--@    1 vy  staff      9956 Jan 12 10:44 open_fragger.params
> -rw-rw-r--@    1 vy  staff      9791 Apr  6 17:47 open_fragger.params_edited
> -rw-rw-r--@    1 vy  staff       342 Sep  2  2019 redist.txt
> -rw-r--r--@    1 vy  staff  13714782 Mar  1 09:43 uniprot-dna-rna-zmc054.fasta
> 

May I have any suggestions for this?
Thanks in advance!

Bests,
Vy

**Comment by fcyu** [comment]
I don't think Bruker's timsTOF data reading library supports Mac. 

Just in case, converting from .d to .mzML is also not recommended. It is suboptimal. And tools after MSFragger are still not compatible with Mac.

Best,

Fengchao
