### ISSUE TITLE
The delat mass of the modification is not consistent with the setting in the spectrum library 

### ISSUE THREAD

**Issue by atesora** [Nesvilab/MSFragger#259]
Hi,
I am using the built-in workflow“DIA_SpecLib_Quant” to build a spectral library on the tims .d file. The delat masses set to occur on selenocarysteine(U) are 414.1937 and 57.021465, respectively, as well as cysteine(C). However, the delat mass on U in library.tsv is 565.14734, and the delat mass on C are right. I don't understand this. I used the same parameters to perform a DDA search on the .d file, and the result is that there are delat mass modifications of 414.1937 and 57.021465 occurring on U. I would like to ask why the delat mass of the modification is not consistent with the setting in the spectral library. Here is the parameters when constructing the spectral library. Looking forward to your reply, thank you very much!
[fragger.params.txt](https://github.com/Nesvilab/MSFragger/files/11280419/fragger.params.txt)

**Comment by fcyu** [comment]
If the "delta mass" you mentioned is the number in the `[]`, then it equals modification mass + amino acid mass.

Best,

Fengchao

**Comment by fcyu** [comment]
>  in the library.tsv generated by the construction of the spectral library, except the modification in UniMod, other custom modifications appear in [] as the value of modification mass + amino acid mass, right?

Correct.

> Modifications include custom modifications in other workflows other than the spectral library building workflow, while the modification column in the results is modification mass, right?

Correct. Except for the "modified sequence" column in the tsv files. They are modification mass + amino acid mass. It is just how the tools report the modifications due to historical reasons.

Best,

Fengchao
