### ISSUE TITLE
DIA calibrate_mass = 1 error

### ISSUE THREAD

**Issue by charlin90** [Nesvilab/MSFragger#263]
Hi,

I am using MSFragger for DIA data analysis. I found it can work well when set calibrate_mass = 0, while it can fail when set calibrate_mass = 1 or 2. 
![bug](https://github.com/Nesvilab/MSFragger/assets/11549300/f881c426-d138-4057-af52-211d64fab73a)

Best wishes,
Charlin

**Comment by fcyu** [comment]
Hi Charlin,

It seems that your data is from DDA. Did you assign the `DDA` data type to it?

Best,

Fengchao
