### ISSUE TITLE
Experimental RT and predicted RT data

### ISSUE THREAD

**Issue by blucherxeus** [Nesvilab/MSFragger#266]
Hi
MSFragger works pretty well on my TIMS-TOF data, i find MSFragger can generate "MSBooster_RTplot" and may i find original data of RTplot so that i can re-draw RTplot.

Thanks!

**Comment by fcyu** [comment]
You can find the MS2 precursor RT from the uncalibrated.mzML file. There is also MS1 apex RT in the combined_ion.tsv file.

Best,

Fengchao

**Comment by blucherxeus** [comment]
Hi Fengchao

Thanks for your precious help, i have another question about the generation of predicted spectra in PDV viewer. how does MSFragger generate these predicted spectra?

Thanks!
Fangzhou

**Comment by fcyu** [comment]
MSBooster does it. 

Best,

Fengchao
