### ISSUE TITLE
Write the output to a new folder

### ISSUE THREAD

**Issue by qussai96** [Nesvilab/MSFragger#267]
Hello,

I want to run MSFragger on a Linux machine, it works fine, but I want to write the output to a new folder other than the original directory as I only have read permissions to the raw data folder, is there any way to make the tool writes the output to a different folder other than the directory of the raw files?

Thanks

**Comment by fcyu** [comment]
There is an old parameter `output_location` that might work. Haven't tested it for a long time. If you saw any weird results or error messages, just stop using that parameter.

Best,

Fengchao

**Comment by qussai96** [comment]
Thanks a lot, I will try that.

best,
Qussai

**Comment by qussai96** [comment]
Unfortunately, the `output_location` parameter didn't work.
