### ISSUE TITLE
EasyPQP convert error

### ISSUE THREAD

**Issue by gcrynen** [Nesvilab/MSFragger#276]
Hi,
we have been using FragPipe without issues until recent updates. Now we are getting errors at EasyPQP step. I have tried  to make spectral library from 60 fractions based on human whole blood samples. Then I tried again with a single file (not fractionated), but similar errors pop up, i was wondering if we need to change the versions of one or more tools.
we are using Fragpipe v18, Msfragger 3.8, Ionquant 1.9.8, Philosopher 5.0.0, Python 3.9.12, EasyPQP 0.1.39
The database is a uniprot database with contaminants and decoys all handled by fragpipe.
I attached the log file for the single file based analysis. Ideally we would like to create spectral library from the fractions we ran.
thank you for all your help.
gogce

[log_2023-08-07_12-57-09.txt](https://github.com/Nesvilab/MSFragger/files/12283815/log_2023-08-07_12-57-09.txt)

**Comment by dpolasky** [comment]
Yes, you need to update FragPipe itself to the latest version (20.0) to use with the updated tools. 

Best,
Dan
