### ISSUE TITLE
Various Workflow for DIA data

### ISSUE THREAD

**Issue by TeckYewLow** [Nesvilab/MSFragger#279]
Hi,

I am reading with great interest your paper on "analysis of DIA proteomics data using MSFragger-DIA and FragPipe computational platform". There were many combinations of methods within the Fragpipe that we could use for DIA data. For example, I am very interested in applying the MSFragger-DIA method. I am wondering if Fragpipe provides step-by-step protocols for analyzing DIA data.

In that paper, methods like FP-MSF, FP-MSF hybrid, FP-DIAU, FP-DIAU hybrid, and DIA-NN library-free were used. I am confused as to how I can ensure the parameters that I choose are correct: (i) which workflow? (ii) should I use a decoy database? (iii) what to select under the Validation tab (iv) Do I need to configure the Advanced Output Options within MSFragger? etc etc.

 It would be great if you could enlighten me.

Best,

Teck

**Comment by fcyu** [comment]
Hi Teck,

Here is the tutorial: https://fragpipe.nesvilab.org/docs/tutorial_DIA.html

Answers to your questions:

1. Using the DIA_SpecLib_Quant workflow
2. Should have both target and decoy similar to the DDA analysis
3 and 4. The workflow will take care of them.

Best,

Fengchao

**Comment by rnirujogi** [comment]
Hi fcyu,

Thanks for the latest MS-Fragger DIA. It's superfast with thermo.raw files. However, with bruker.d files it does require to convert them to mzml's. Using MS-convert from Proteowizard is very painful in converting diaPASEF files, each file taking >10 hours or most times it crashes. Any suggestions for an alternative to this? any other tool or Does Fragpipe can take care of this in future. I clearly see for timsTOF data MS-Fragger dia isn't going to be a useful or GO to tool without solving this issue. I am particulary interested to process phospho dia data. Many thanks in advance.

Best,
Raja
