### ISSUE TITLE
SpectralSim value

### ISSUE THREAD

**Issue by patrick-willems** [Nesvilab/MSFragger#280]
Dear FragPipe team,

First of all thank you for this great tool, I am very satisfied with FragPipe for various searches. I had a small question regarding a field in the 'psm.tsv' outputs, there is the 'SpectralSim' column - this reflects a cosine angle or pearson correlation or something similar of the experimental spectrum with a prediction? This is however not used for scoring in the percolator input file - or am I misinterpreting this column header? MSBooster does of course add 'unweighted_spectral_entropy' which sort of a similar scoring metric. 

Thanks
Patrick

**Comment by fcyu** [comment]
If I remember it correct, the `SpectralSim` is the same as the `unweighted_spectral_entropy`, and used in the Percolator rescoring.

Best,

Fengchao

**Comment by patrick-willems** [comment]
Ok thanks!
