### ISSUE TITLE
MS-Fragger dia for timsTOF diaPASEF

### ISSUE THREAD

**Issue by rnirujogi** [Nesvilab/MSFragger#281]
Hi fcyu,

Thanks for the latest MS-Fragger DIA. It's superfast with thermo.raw files. However, with bruker.d files it does require to convert them to mzml's. Using MS-convert from Proteowizard is very painful in converting diaPASEF files, each file taking >10 hours or most times it crashes. Any suggestions for an alternative to this? any other tool or Does Fragpipe can take care of this in future. I clearly see for timsTOF data MS-Fragger dia isn't going to be a useful or GO to tool without solving this issue. I am particulary interested to process phospho dia data. Many thanks in advance.

Best,
Raja

**Comment by fcyu** [comment]
Similar to https://github.com/Nesvilab/FragPipe/issues/1212. MSFragger-DIA currently does not support diaPASEF because the data has additional ion mobility dimension. New algorithm needs to be developed to support that. We are working on it. Stay tuned.

Best,

Fengchao

**Comment by rnirujogi** [comment]
[like]  Raja Nirujogi (Staff) reacted to your message:
________________________________
