### ISSUE TITLE
B -Z amino acid fixed modifications

### ISSUE THREAD

**Issue by DesAmsh** [Nesvilab/MSFragger#282]
Hi Fengchau,

I would like to search for a  peptide containing artificial amino acids using MS fragger. Can I set the B, J, O, U, X, Z  amino acids, on the fixed modifications tab, as my artificial amino acid masses? And consequently use these amino acids in my peptide sequence in my FASTA file? If this is true, would I input the residue or amino acid mass?

Thanks, 

Austin

**Comment by fcyu** [comment]
Hi Austin,

Yes, you can. Should put the monoisotopic residue mass. 

Note that O and U are two special amino acids with masses 237.14773 Da and 150.95363 Da, respectively.

Best,

Fengchao

**Comment by DesAmsh** [comment]
Thanks for the response! I will carry on ahead.

**Comment by fcyu** [comment]
No problem.

Best,

Fengchao
