### ISSUE TITLE
Program stopping with 1 Remaining Task

### ISSUE THREAD

**Issue by kgraham96** [Nesvilab/MSFragger#283]
Hello, When I start to run the program I am able to get to a certain point and then the program stops running with one remaining task. I can't seem to figure out what is going wrong. Attached is the log. Thank you!
[log_2023-09-25_10-55-48.txt](https://github.com/Nesvilab/MSFragger/files/12718147/log_2023-09-25_10-55-48.txt)

**Comment by fcyu** [comment]
You skipped many steps between MSFragger and PTMShepherd:
```
Execution order:

    Cmd: [START], Work dir: [C:\Users\katherinegraham\Desktop\20230921000062.d]
    Cmd: [CheckCentroid], Work dir: [C:\Users\katherinegraham\Desktop\20230921000062.d]
    Cmd: [MSFragger], Work dir: [C:\Users\katherinegraham\Desktop\20230921000062.d]
    Cmd: [PTMShepherd], Work dir: [C:\Users\katherinegraham\Desktop\20230921000062.d]
```

Please read our tutorials (https://fragpipe.nesvilab.org/) and use the build-in workflows as beginning.

Best,

Fengchao
