### ISSUE TITLE
Coverage results missing 

### ISSUE THREAD

**Issue by Xindong-Sun** [Nesvilab/MSFragger#284]
Hi,

Many thanks for providing such an useful tool! I am now using MSFragger for quantitative glycopeptides analysis. I can't really find the coverage reults in protein.tsv is (which is shown on your results guidance page on github). I am using the N-glycopeptide search, hybrid activation (glyco-N-Hybrid) workflow together with IonQuant, and here is the log: 

System OS: Windows 10, Architecture: AMD64
Java Info: 20.0.2, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
.NET Core Info: N/A

Version info:
FragPipe version 20.0
MSFragger version 3.8
IonQuant version 1.9.8
Philosopher version 5.0.0

Thanks a lot!
Xindong

**Comment by fcyu** [comment]
No sure if I get the question correctly, but my protein.tsv has the coverage column:

![image](https://github.com/Nesvilab/MSFragger/assets/6926299/dc0ccdc6-785d-4d5b-abdf-0200514fa4ae)

Best,

Fengchao

**Comment by Xindong-Sun** [comment]
Dear Fengchao,
Thanks so much for your fast reply. I have just figured out that coverage is presented in individual experiment output but not in the combined one. Thanks again for clarification! 
Cheers,
Xindong
