### ISSUE TITLE
TIMSTOF DDA TypeError: list indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by Wolfy0111** [Nesvilab/MSFragger#285]
Dear colleagues,
I am running TIMSTOF dda files. Research goes through until the end an above mentioned error appears.
Could you give me a hint, please?
Thank you
Wolfgang

Attached log:
[log_2023-10-05_09-39-01.txt](https://github.com/Nesvilab/MSFragger/files/12815041/log_2023-10-05_09-39-01.txt)

**Comment by fcyu** [comment]
Hi Wolfgang,

Could you share the `S1_1_w6_32_2A_MHCI_approx15mioCells_Slot2-47_1_780.d` and `2023-09-04-decoys-SwissProt_autoup_20201202.fasta.fas` with us to debug? Here is the link to upload the files: https://www.dropbox.com/request/WjiJWVHKHNLmWVky054U

Thanks,

Fengchao

**Comment by fcyu** [comment]
Hi Wolfgang,

It has been fixed in https://github.com/Nesvilab/FragPipe/commit/b065a4002af9665d3263d74b506cfcaaecbe34dc.

Best,

Fengchao
