### ISSUE TITLE
.wiff convert to .mzML but non-centroid scans

### ISSUE THREAD

**Issue by Ruby0416W** [Nesvilab/MSFragger#287]
Hello, I'm getting this error when running MSFragger. Here is the error message:

"ctrl.mzML has non-centroid scans. Please re-convert it with peakPeaking (https://fragpipe.nesvilab.org/docs/tutorial_convert.html)."

I used msconvert converted ctrl.wiff to ctrl.mzML , the command lines are here:

On Linux: 
msconvert --mzML *.wiff -o ../mzML 

On Windows(in bat file): 
echo off
set conv="E:\ProteoWizard\ProteoWizard 3.0.19331.dddfea8af\msconvert.exe"
for %%f in (*.wiff) do %conv% --mzML  --outdir  .\ .\ %%f 
pause

...but both got the same error message. Has anyone else encountered this issue before?

**Comment by fcyu** [comment]
You need to add the `peakPicking` filter to centroid the data. I believe the tutorial showed that filter in the GUI.

Best,

Fengchao
