### ISSUE TITLE
another stand-alone version

### ISSUE THREAD

**Issue by hxxhust163** [Nesvilab/MSFragger#288]
Hi Mr Yu:

Happy  to meet here, I am Xiaoxiang Huang from Wenguang Shao's lab. I wonder if there is a stand-alone version of MSFragger with 'Split database' option enabled? I ran MSFragger in command line with a large customized protein sequence database, but failed for no enough space.
Thanks!

best regards
xiaoxiang

**Comment by fcyu** [comment]
Hi Xiaoxiang,

The split database option is part of FragPipe, not MSFragger. You need to download FragPipe from https://github.com/Nesvilab/FragPipe/releases/latest and running MSFragger inside FragPipe.

Best,

Fengchao

**Comment by hxxhust163** [comment]
OK, thanks very much!

best regards
xiaoxiang
