### ISSUE TITLE
No sequences with localized modification in report when using new released MSFragger

### ISSUE THREAD

**Issue by Cheng111** [Nesvilab/MSFragger#29]
Hi, I am using MSFragger-20190530 and newly released philosopher to do an open-window search on my data. The header of the output psm.tsv file is like follow:
![image](https://user-images.githubusercontent.com/16903151/59612070-7ae3b080-90ea-11e9-8753-857465944749.png)
I didn't find the column of sequences with localized modification which is mentioned as a new feature of the new version MSFragger
![image](https://user-images.githubusercontent.com/16903151/59612155-9e0e6000-90ea-11e9-85bd-69c46111481c.png)
Is there anything I did wrong? Thank you so much

**Comment by guoci** [comment]
That refers to the TSV generated by MSFragger. `psm.tsv` is generated by Philosopher, not MSFragger.

**Comment by fcyu** [comment]
The file you are looking for should be something like `<run name>.tsv`.

Bests,

Fengchao
