### ISSUE TITLE
Cannot perform open search with precursor tolerance lower than -230 Da

### ISSUE THREAD

**Issue by jossmi** [Nesvilab/MSFragger#290]
Hi all,

I am trying to search the Chick 2015 dataset to benchmark some of our workflows and so I wanted to reproduce the search settings from that paper, which included a -500 to +500 Da precursor window. I wouldn't normally want to go so low on the precursor tolerance, but doing so this time just to reproduce the published dataset for an apples-to-apples comparison. However, I got an error that states: "The precursor_mass_lower is smaller than -230. Please change it to -230. Process 'MSFragger' finished, exit code: 1". I have attached the log. I was surprised by this error, because the 2019 DeltaMass paper by Dmitry Avtonomov also used MSFragger and the -500 to +500 settings to search the Chick dataset, and that clearly worked. 

I ran the search with a precursor window of -230 to +500 just fine, but I would love to recreate the original parameters for comparison. Is this possible? 

Thanks,
Josh

[log_2023-12-14_18-30-02.txt](https://github.com/Nesvilab/MSFragger/files/13718744/log_2023-12-14_18-30-02.txt)

**Comment by fcyu** [comment]
We added this cap because PeptideProphet seemed to have issues with some datasets when we searched it from -500 to 500 Da.

Best,

Fengchao

**Comment by anesvi** [comment]
Plus, there is not any reason really to go beyond that as far as open PTM searches are concerned. If really needed, we can give you a version that can go to -500

**Comment by jossmi** [comment]
I see, thanks. Agreed, we don't normally want to go that low, I just wanted to do it to get an apples-to-apples comparison between our workflow tools and previously published data. I appreciate the offer for the -500 capable version, but I think for right now we don't need to.
