### ISSUE TITLE
FragPipe (v20.0) error following updates

### ISSUE THREAD

**Issue by hcadre** [Nesvilab/MSFragger#291]
Dear All, 

After updating MSFragger (4.0), IonQuant (1.10.12) and Philosopher (5.1.0) from within FragPipe (v20.0), I tried to re-analyze a QC file (Thermo .raw format) that I had successfully analyzed already before the updates (default method), however, now I receive the following error message and FragPipe stops:

![image](https://github.com/Nesvilab/MSFragger/assets/16349515/65f22693-c947-4450-b3d2-55413cb8317a)
Any idea about what´s going on? I am grateful for any comment or suggestion!

Sincerely,
 
Hannes

The corresponding log file is also attached:

[log_2023-12-21_13-25-04.txt](https://github.com/Nesvilab/MSFragger/files/13741932/log_2023-12-21_13-25-04.txt)

**Comment by dpolasky** [comment]
Hi Hannes,
You need to upgrade Fragpipe as well to work with the other updated tools. You can download the updated version 21.1 here: https://github.com/Nesvilab/FragPipe/releases/tag/21.1

Best,
Dan

**Comment by hcadre** [comment]
Hi Dan, 
Many thanks for your quick reply! You made my day! Merry Christmas and a happy new year!
Best, 
Hannes
