### ISSUE TITLE
Question: Extraction of scannumber

### ISSUE THREAD

**Issue by JannikSchneider12** [Nesvilab/MSFragger#294]
Hello everyone,

I have a question about the extraction of the scannumber that finally lands in the msfragger output file. My spectra have the title format "filename.scan_start.scan_end.charge". Is it right that the scannr that lands in the output is actually extracted from there or is some kind of positional index used? (I just wanted to make sure)

Thanks for your time and help

Have a nice weekend

**Comment by fcyu** [comment]
What is your input format? If MGF, then yes. If mzML, need to see your native scan ID.

Best,

Fengchao

**Comment by JannikSchneider12** [comment]
Hello,

Yes those are mgf files. Thanks for your help:)
