### ISSUE TITLE
Are processed MS/MS spectra decharged before database search carried out by MSFragger?

### ISSUE THREAD

**Issue by HijaziHassan** [Nesvilab/MSFragger#298]
Hello,

I'm using Fragpipe to do a closed DDA search. 

This article, "[A fast deisotoping algorithm and its implementation in the MSFragger search engine](https://pubs.acs.org/doi/10.1021/acs.jproteome.0c00544)", mentions details on spectral processing. 

I would like to recover the peak list after such processing which MSFragger uses for searching and identification and scoring. Is it the same as the uncalibrated MGF file that could be saved as an option? if yes, then I don't see any decharging for 3+ and 4+ peptides. Please correct me if I'm wrong.

**Comment by fcyu** [comment]
It should be the _**calibrated**.mzML file.

Best,

Fengchao
