### ISSUE TITLE
Use a pre-digested database for close/open search

### ISSUE THREAD

**Issue by yonghanyu** [Nesvilab/MSFragger#299]
Hi,

I am wondering whether there is a way to use a predigested peptide database when conducting close or open search with msfragger?

**Comment by yonghanyu** [comment]
> Yes, you can. Just prepare your own fasta file and make sure that the header is in good format.
> 
> Best,
> 
> Fengchao

Hi Fengchao,

Thank you for your quick reply. However, the msfragger will always perform in silico digestion even with philosopher pre annotated database. Is there a way to avoid such behaviour as my peptide database is pre-digested.

**Comment by fcyu** [comment]
You could set the enzyme cuts to something like `X` so that there is no sites to cut (assuming there are no `X` in your proteins).

Best,

Fengchao

**Comment by yonghanyu** [comment]
> You could set the enzyme cuts to something like `X` so that there is no sites to cut (assuming there are no `X` in your proteins).
> 
> Best,
> 
> Fengchao

Thank you very much! I will give it a shot.
