### ISSUE TITLE
Repo and organization permissions

### ISSUE THREAD

**Issue by chhh** [Nesvilab/MSFragger#3]
I think it'd be helpful to:
1) Have more than 1 account assigned **owner** permissions for the Nesvilab org - currently there's only 1 (Felipe). I guess Alexey's account should be.
2) Make @anesvi at least a member of the org, not just a collaborator and set his membership visibility to *public*. That's also needed to assign him as an owner.
3) Grant admin rights to members who maintain repositories in the org.

**Comment by prvst** [comment]
1 and 2 - @anesvi  was invited to be part of the organization as owner but haven't accepted yet.
3 - OK

**Comment by prvst** [comment]
Just a note, I think by making everyone admin we all can see each others private work

**Comment by chhh** [comment]
@prvst if anyone needs a private repo there's no need for it to be in the org...
