### ISSUE TITLE
nonspecific search

### ISSUE THREAD

**Issue by Mohee66** [Nesvilab/MSFragger#302]
Dear Nesvilab, 

I am doing a nonspecific search. I have converted my raw file to mzml file based on the tutorial on MSFragger website that you sent me. Now I am repeating this for some other file and I get this error. I really appreciate it if you help me. 
In total 12675699 peptides.
Generated 19732068 modified peptides.
Number of peptides with more than 5000 modification patterns: 0
Insufficient memory!
Traceback (most recent call last):
  File "C:\Program Files (x86)\FragPipe-jre-20.0\fragpipe\tools\msfragger_pep_split.py", line 630, in <module>
    main()
  File "C:\Program Files (x86)\FragPipe-jre-20.0\fragpipe\tools\msfragger_pep_split.py", line 616, in main
    run_msfragger(calibrate_mzBIN if calibrate_mass in [1, 2] else infiles_name)
  File "C:\Program Files (x86)\FragPipe-jre-20.0\fragpipe\tools\msfragger_pep_split.py", line 133, in run_msfragger
    subprocess.run(list(map(os.fspath, cmd)), cwd=cwd, check=True)
  File "C:\Users\46658831\Anaconda3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program', 'Files', '(x86)\\FragPipe-jre-20.0\\fragpipe\\jre\\bin\\java.exe', '-jar', '-Dfile.encoding=UTF-8', '-Xmx2G', 'C:\\Users\\46658831\\Downloads\\FragPipe-jre-20.0\\fragpipe\\tools\\MSFragger-3.8\\MSFragger-3.8.jar', 'fragger.params', 'C:\\output\\3333\\230926_5k3_1.mzML', 'C:\\output\\3333\\230926_5k3_2.mzML', 'C:\\output\\3333\\230926_5k3_3.mzML', '--partial', '0']' returned non-zero exit status 1.
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment]
> Insufficient memory!

>  '-Xmx2G'

Please set the mass calibration to "None" and increase the number of "split database". Considering that your computer only has 2 GB free memory, I doubt it can handle any searches. I suggest you find another computer with more memory.

Best,

Fengchao
