### ISSUE TITLE
Are DDA+ IDs of different ranks equal?

### ISSUE THREAD

**Issue by candidaorelmex** [Nesvilab/MSFragger#304]
I love the new DDA+ feature to deal with chimeric MS2 spectra.
 
I do have a couple of questions though:
**1)** I now wonder if I take a PSM that passed the FDR from the rank 1 raw file-extract and a PSM from the rank 5 raw file-extract: is there any difference in ID quality there? 
**2)** Can I just merge all of the IDs found in the different ranks of a raw file to one large list of all identifications for that raw file? 
**3)** Do I need to introduce an additional kind of quality check for PSMs made with DDA+ that I don't have to do when analyzing with the DDA workflow?
**4)** Also, is there any literature out for DDA+? I've seen the indication that DDA+ takes into account the entire acquisition window, unlike the regular DDA file processing - I don't really understand what that means. To identify a PSM with regular DDA, not DDA+, we look at the peaks present in an MS2 spectra without mass restriction, as far as I understood.

Thanks in advance!

**Comment by fcyu** [comment]
Thanks for your interest in the new feature.

> I now wonder if I take a PSM that passed the FDR from the rank 1 raw file-extract and a PSM from the rank 5 raw file-extract: is there any difference in ID quality there? 

I don't think so, because they are treated equally in the scoring and FDR filtering.

> Can I just merge all of the IDs found in the different ranks of a raw file to one large list of all identifications for that raw file?

Yes, you can.

> Do I need to introduce an additional kind of quality check for PSMs made with DDA+ that I don't have to do when analyzing with the DDA workflow?

No, you do not.

> Also, is there any literature out for DDA+?

Not yet, but stay tuned.

Best,

Fengchao

**Comment by candidaorelmex** [comment]
Thank you for the quick response - looking forward to the DDA+ paper with wide-window acquisition:)

Best,
Ilja

**Comment by ds2268** [comment]
@fcyu the above holds only if taken from the final `psm.tsv` file right? The individual `filename_rank_X.pepXML` are not FDR filtered right?

**Comment by fcyu** [comment]
Correct, `*.pepXML` or `interact-*.pep.xml` files are not FDR filtered no matter if they are from DDA, DDA+, DIA.

Best,

Fengchao
