### ISSUE TITLE
Error During pepxml Rewrite: Unable to Find Correct Mapping for Raw File Path

### ISSUE THREAD

**Issue by Schwarzeneggerjune** [Nesvilab/MSFragger#305]
Hello MSFragger team,

I've encountered an issue while using MSFragger, where the software is unable to successfully rewrite the pepxml file. Below is the error message I received during the process:

Fixing pepxml: D:\FXX\MS\interact.pep.xml
Didn't find correct mapping for raw file path in pepxml: D:\FXX\MS/1
Writing output to: D:\FXX\MS\interact.pep.xml17777269503134426981.temp-rewrite
Process 'Rewrite pepxml' finished, exit code: 1
Process returned non-zero exit code, stopping
Here are the details of my workflow:

I ran MSFragger (mention your version here) with the usual parameters (you might want to list the key parameters or attach your configuration file).
The process seems to fail during the pepxml rewriting phase, specifically at finding the correct mapping for the raw file path.
I ensured that the file paths are correct, and the files are accessible and not corrupted.
I am running this on (mention your operating system and version, e.g., Windows 10).
I would appreciate any guidance or suggestions you could provide to resolve this issue. Could this be related to the file path syntax, or is there something else I might be missing?

Please find the attached runtime log file below. I would appreciate it if you could review it to help diagnose the issue I am encountering.
[log_2024-03-05_00-01-52.txt](https://github.com/Nesvilab/MSFragger/files/14489818/log_2024-03-05_00-01-52.txt)

Thank you for your assistance.

**Comment by fcyu** [comment]
Something from the folder name looks weird: 
```shell
D:\FragPipe-jre-18.0\fragpipe\jre\bin\java.exe ... -cp D:\FragPipe-jre-18.0\fragpipe\lib\fragpipe-21.1.jar;D:\FragPipe-jre-18.0\fragpipe\tools\batmass-io-1.30.0.jar....
```

I guess you unzip FragPipe 21.1 to the FragPipe 18.0 folder? Could you download a new FragPipe, unzip it to a separated folder, and try again?

Thanks,

Fengchao

**Comment by Schwarzeneggerjune** [comment]
> Something from the folder name looks weird:
> 
> ```shell
> D:\FragPipe-jre-18.0\fragpipe\jre\bin\java.exe ... -cp D:\FragPipe-jre-18.0\fragpipe\lib\fragpipe-21.1.jar;D:\FragPipe-jre-18.0\fragpipe\tools\batmass-io-1.30.0.jar....
> ```
> 
> I guess you unzip FragPipe 21.1 to the FragPipe 18.0 folder? Could you download a new FragPipe, unzip it to a separated folder, and try again?
> 
> Thanks,
> 
> Fengchao

I have indeed extracted the latest version of FragPipe into the 18.1 version folder. I will download the newest version again and provide you with further feedback.

**Comment by Schwarzeneggerjune** [comment]
I recreated the folder and downloaded the latest version of FragPipe, and also checked that there are no illegal characters in the path. Despite this, I still encountered the following errors during the execution process. 
INFO[15:52:41] Parsing D:\FXX\frager_glyco\interact.pep.xml 
ERRO[15:52:41] Cannot read file. Error parsing the file     
Process 'PhilosopherFilter' finished, exit code: 1
Process returned non-zero exit code, stopping


Below is the runtime log.
[log_2024-03-05_15-52-41.txt](https://github.com/Nesvilab/MSFragger/files/14493402/log_2024-03-05_15-52-41.txt)

**Comment by danielgeiszler** [comment]
Is D: an external drive? If so, is it possible to try putting your output folder on your C: drive?

**Comment by fcyu** [comment]
Hi @Schwarzeneggerjune ,

There is a temp file `D:\FXX\frager_glyco\interact.pep.xml3250671875624846659.temp-rewrite` broke the program. It is either from your previous failed task or not deleted due to the file system issue in the current task. Could you re-run the task in a new folder on a local drive from scratch?

Thanks,

Fengchao

**Comment by Schwarzeneggerjune** [comment]
> Hi @Schwarzeneggerjune ,
> 
> There is a temp file `D:\FXX\frager_glyco\interact.pep.xml3250671875624846659.temp-rewrite` broke the program. It is either from your previous failed task or not deleted due to the file system issue in the current task. Could you re-run the task in a new folder on a local drive from scratch?
> 
> Thanks,
> 
> Fengchao

Thank you very much for your prompt response. I changed the file result path to the C drive, and that resolved the bug. Your guidance was incredibly helpful, and I appreciate your assistance

**Comment by Schwarzeneggerjune** [comment]
> Is D: an external drive? If so, is it possible to try putting your output folder on your C: drive?

Thank you very much for your prompt response. I changed the file result path to the C drive, and that resolved the bug. Your guidance was incredibly helpful, and I appreciate your assistance

**Comment by fcyu** [comment]
Thanks for the positive feedback.

I will close this ticket, but feel free to contact us if you have any questions in the future.

Best,

Fengchao
