### ISSUE TITLE
Low resolution MS database search

### ISSUE THREAD

**Issue by Baopusr** [Nesvilab/MSFragger#307]
Hi,

I'm interested in using the Labile search mode in MSFragger, but the tutorials mainly focus on high-resolution MS data. Could you please give some advice on setting validation and PTM module parameters for analyzing low-resolution MS data, specifically from OT-IT raw files? Thanks!
![Screenshot 2024-03-07 201237](https://github.com/Nesvilab/MSFragger/assets/151601763/8e249897-022d-443c-b66e-a281900494de)
![Screenshot 2024-03-07 201449](https://github.com/Nesvilab/MSFragger/assets/151601763/eac263a1-0976-489e-a354-a12719ac0dad)

**Comment by Baopusr** [comment]
Thank you for clarifying this! I still have a few detailed questions:

1) I'm still very interested in understanding why low-resolution MS isn't as suitable for Labile mode database search as high-resolution MS. Could you please provide some references or evidence to support this?

2) Regarding the database search parameters for OT-IT data, do I only need to modify the "fragment mass tolerance" and "PTMProphet" parameters? I noticed that for ion trap MS with a resolution of 0.5 Da, the parameters seem to be set in PPM only. Could you please tell me how I should set these parameters?

Best wishes
Baopu

**Comment by fcyu** [comment]
Hi Baopu,

> I'm still very interested in understanding why low-resolution MS isn't as suitable for Labile mode database search as high-resolution MS. Could you please provide some references or evidence to support this?

Because the fragment resolution is too low to have a good separation of different peaks and peptides. Labile mode normally has more fragment peaks to match. But maybe OK since it is a mass-offset search not an open search. 

> Regarding the database search parameters for OT-IT data, do I only need to modify the "fragment mass tolerance" and "PTMProphet" parameters? I noticed that for ion trap MS with a resolution of 0.5 Da, the parameters seem to be set in PPM only. Could you please tell me how I should set these parameters?

You can set in either Da or ppm unit. 0.5 Da or 300 ppm is fine as far as I know.

Best,

Fengchao

**Comment by Baopusr** [comment]
I really appreciate your explanation! I've got it now.

Best wishes
Baopu
