### ISSUE TITLE
Setting up variable modifications

### ISSUE THREAD

**Issue by luizalmeida93** [Nesvilab/MSFragger#308]
Hi,

This is not an issue per se, but more a lack of confidence in properly setting up variable modification in MSfragger. I did search for other topics and read the wiki and FAQ but I did not find a clear answer.

If I use "n^K", does it mean (1) I will be searching for lysines located **at** the peptide n-terminus? Or does it mean (2) I will be searching for **any** n-terminus modification **plus** lysine at any position?

I am leaning more toward option number (1). Hence, if I want to search for dimethyl labeling on any peptide n-term **AND** any lysine (K), then I would have to split this modification into two, as such:
dimethyl_on_any_n-term = 28.0313 n* 1
dimethyl_any_lysine = 28.0313 K 3

Question 1: Is the example above correct?

Question 2: Notice that on "dimethyl_on_any_n-term" I used "*" instead of "^". Is this correct? At first, I thought that whenever I used "^" an amino acid must follow it, while "*" does not require any amino acid, as it will search for all amino acids. However, in your tutorial section, you add modifications on the n-terminus without using "^", as seen by pyro-Glu "nQnC", so I am also unsure when and why to use "^" or "*".

Thanks for your patience.

Best,
Luiz

**Comment by fcyu** [comment]
> If I use "n^K", does it mean (1) I will be searching for lysines located at the peptide n-terminus? Or does it mean (2) I will be searching for any n-terminus modification plus lysine at any position?

It means (2).

> if I want to search for dimethyl labeling on any peptide n-term AND any lysine (K),

Should be `28.0313 n^K 3`

Basically, `A-Z*^` are "amino acids", and `nc[]` are "modifier" for the "amino acid" following it. `^` is a "special amino acid" representing a terminus, and `*` means all A-Z.

Hope my answers clarify your questions.

Best,

Fengchao

**Comment by luizalmeida93** [comment]
Thanks for the quick reply, Fengchao, as usual!

I think your answer is crystal clear. I will share it with my lab and will re-open if people have any other questions.
