### ISSUE TITLE
Does MSFragger allow two modifications on the same residue?

### ISSUE THREAD

**Issue by HijaziHassan** [Nesvilab/MSFragger#309]
Hello,

When derivatizing peptides with propionic anhydride, peptide N-termini, unmodified and monomethylated lysines get propionylated. Then digesting with trypsin leads to Arg-C like peptide fragments. 

I wonder if MSFragger can allow two modifications in case a peptide starts with K (a propionyl group at K side chain and another one at its N-terminus).
Though it can be treated as a fixed modification but I would like to have it as variable mod to study the efficiency of the reaction. 

So here is how I set up the variable modification table:

`K 56.026215 3`
`K 70.04186 3`
`n^ 56.026215 1`

All the fixed mod table was set to zero (including N-term peptide).

If this does not work, I have to make custom mods for N-terminal K (e.g., propionyl + acetyl, ...).

Thank you.

**Comment by fcyu** [comment]
There is a parameter `allow_multiple_variable_mods_on_residue` (https://github.com/Nesvilab/MSFragger/wiki/Setting-the-Parameters#allow_multiple_variable_mods_on_residue) that can enable it. But some downstream tools don't support two variable modifications on the same side, so we disabled it in FragPipe. But you can edit the `fragger.params` and run MSFragger in command line.

Best,

Fengchao

**Comment by HijaziHassan** [comment]
Thank you very much. This works.  Actually, the aim is to also generate a spectral library, so I think I should also use EasyPQP from the command line then, right?

**Comment by fcyu** [comment]
Although I am not 100% sure, I don't think EasyPQP support multiple variable modifications on the same site. 

Also, Philosopher won't support it. So before getting to EasyPQP, you will already see weird outputs from Philosopher.

Best,

Fengchao

**Comment by HijaziHassan** [comment]
Thanks you Fengchao for the elaborate comments. 
I will see how to walk my way through.
