### ISSUE TITLE
Question about multiple PTMs on same residue

### ISSUE THREAD

**Issue by JannikSchneider12** [Nesvilab/MSFragger#312]
Hello,

I have a question about the "allow_multiple_variable_mods_on_residue" parameter. I noticed on my output file that there occur masses in the modifications that are not explicitly specified, so I assume those are cases where multiple mods are found on the same residue. However I ask myself whether I can distinguish them, so how to know which modifications took place and made up the resulting mass?
So is there a way to find this out or would I need to specfiy extra modifications for this?

Thanks for your time and help

**Comment by fcyu** [comment]
Given the specified variable modifications and the mass you found, it is not hard to figure out which two form the total masses in most cases.

Best,

Fengchao
