### ISSUE TITLE
Peptides with and without modficiation

### ISSUE THREAD

**Issue by tanjagosnjak** [Nesvilab/MSFragger#315]
Hi, 

I am performing searches with different modifications. In my searches, whenever there's a modification present, only the modified peptide is reported, and the exact same peptide without modifications is never found. I am comparing results with other softwares and they sometimes find the same peptides with and without modifications. Is there a setting that I might be missing that could produce reports showing both modified and unmodified peptides?

Thank you,
Tanja

**Comment by danielgeiszler** [comment]
Please post your log.

**Comment by tanjagosnjak** [comment]
[log_2024-03-29_21-18-52.txt](https://github.com/Nesvilab/MSFragger/files/14965934/log_2024-03-29_21-18-52.txt)

**Comment by danielgeiszler** [comment]
You're doing an open search. The only modifications you're searching for directly are variable oxidation of M and fixed alkylation of C.

Can you please upload an example of the issue you're having?

**Comment by tanjagosnjak** [comment]
Yes, that's right.

For example, MS Fragger reports about this peptide with modification 
<img width="677" alt="MSFragger" src="https://github.com/Nesvilab/MSFragger/assets/117011290/5f168ef9-1bec-401f-a691-09be0743a7ec">

but MaxQuant reports about the same peptide with and without modification
<img width="946" alt="MaxQuant" src="https://github.com/Nesvilab/MSFragger/assets/117011290/3c46c2e0-7167-46b8-8f92-1924df4c8abf">

I understant that results can't be the same, but I can't find an example where MSFragger has found beside the peptide with modification also one without it. 

So I would like to know if there is a possibility to enable the software to also report an unmodified sequence if there is one.

**Comment by danielgeiszler** [comment]
Are you looking at the combined_peptide.tsv table or the combined_modified_peptide.tsv table?

The combined_peptide.tsv collapses all modification states into a single row.

https://fragpipe.nesvilab.org/docs/tutorial_fragpipe_outputs.html

**Comment by tanjagosnjak** [comment]
I am looking at peptide.tsv files. I can't find those files with prefix 'combined'.

**Comment by anesvi** [comment]
You should be looking at PSM.tsv file

**Comment by tanjagosnjak** [comment]
thank you for your help
