### ISSUE TITLE
Index out-of-bound error when perform open search

### ISSUE THREAD

**Issue by yonghanyu** [Nesvilab/MSFragger#317]
Hi there,

I recently encountered this error when running MsFragger with open search. MsFragger failed when building the index and gave me the following message:

> There was an error in analyzing spectrum.
> Index 3474 out of bounds for length 2048

I am using MsFragger4.0 with command line on linux. The program works fine when doing narrow-window search on the same file. I am using predigested database and I attached my param file
[fragger.params.txt](https://github.com/Nesvilab/MSFragger/files/15015753/fragger.params.txt)
 with this post. 

Any idea on how to fix this?
Thanks in advance!

**Comment by fcyu** [comment]
Some settings don't make any sense. Please using the FragPipe and the `Open` workflow for the open search: https://fragpipe.nesvilab.org/docs/tutorial_open.html

Best,

Fengchao

**Comment by yonghanyu** [comment]
> Some settings don't make any sense. Please using the FragPipe and the `Open` workflow for the open search: https://fragpipe.nesvilab.org/docs/tutorial_open.html
> 
> Best,
> 
> Fengchao

Hi Fengchao,

Thanks for replying. Would you mind telling me which setting doesn't make sense?

**Comment by fcyu** [comment]
> I changed these params for consistency across other search engines

It also doesn't make any sense to disable premium functions that only MSFragger can do and say that "it is a fair comparison". Just like you won't compare the speed of a plane and a car by running both on the ground just because the car can't fly.

For the following one, I don't think there are any search engines use such setting

> minimum_peaks = 64	

Can you change it to 15, and try again?

Good luck,

Fengchao

**Comment by yonghanyu** [comment]
> Fengchao

I changed min peaks to 15 and get the following error:

> Index -2147172625 out of bounds for length 4867221

I suppose there is an integer overflow. 

I turned off deisotoping and deneutralloss simply for a higher identification rate, at least on my dataset that's the case. And I don't think calibrate_mass matters if you don't need PTM localization, as suggested by the MsFragger paper.

**Comment by fcyu** [comment]
> I changed min peaks to 15 and get the following error:
> Index -2147172625 out of bounds for length 4867221

Thanks for the update. If you like, I can debug using your fasta and mzML file. Here is the link to upload the files https://www.dropbox.com/request/lUsu9pqpq268rB3JGW7m

> I turned off deisotoping and deneutralloss simply for a higher identification rate, at least on my dataset that's the case

It is quite uncommon that turning off the deisotoping and deneutrallossing results in more IDs. Probability your data is something different considering the integer overflow you got.

> And I don't think calibrate_mass matters if you don't need PTM localization, as suggested by the MsFragger paper.

If you are doing open search, there are "PTM localization" (LOS).

Best,

Fengchao
