### ISSUE TITLE
Follow-up to my question from Jun 14th; Recalibration with sliced database (#28)

### ISSUE THREAD

**Issue by JB91451** [Nesvilab/MSFragger#32]
Dear Fengchao or whoever it may concern,

First of all thank you again for your fast help with my previous error. The fixed version worked quite well for me. However, on a few specific mzXML files MSFragger allway stops with the "out of memory" error after finishing the actual search. Thus it completes the search for all spectra and returns already the time used for all spectra but than does not finish writing the pep.xml file. Instead there are files with the extention ".fragtmp" which are about 20Gb in size (about twice as much as the mzXML). The concerned files are from one batch with other files that do not produce this error.

Could this error be somehow related to the previous one or do you have any suggestion, what I could try with theese files?

Best regards,
Juergen

**Comment by fcyu** [comment]
Hi Juergen,

Thank you very much for your feedback. Could you please send me your logger? It would be better if you could share one of your mzML file with me.

Thanks,

Fengchao

**Comment by JB91451** [comment]
Dear Fengchao,

Is the logger just the comand line output? This I could send to you.
For the mzXML file it might be a bit problematic since it is about 10Gb and I am not sure, where we could exchange it.

**Comment by fcyu** [comment]
Hi Juergen,

Yes, the command line output. 

Could you please give me your email address. My email address is yufe@umich.edu. I can share an empty BOX folder with you so that you can upload your mzML file.

Thanks,

Fengchao

**Comment by JB91451** [comment]
Dear Fengchao,

I started the upload of the files and it should finish soon.

Thanks,
Juergen

**Comment by fcyu** [comment]
Hi Juergen,

Great! Looking forward to it.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Juergen,

We fixed this bug which is caused by an overflow when the fragtemp file is too large. You may download the fixed version from [https://umich.box.com/s/b0porhqxqsbsl0iqxv62n3ee6p9v92ru](https://umich.box.com/s/b0porhqxqsbsl0iqxv62n3ee6p9v92ru)

BTW, there is a small issue in your parameter file:
`variable_mod_03 = 43.005814 n*KRCM` can be changed to `variable_mod_03 = 43.005814 n^KRCM`, which will result in the same result but far less peptides to be searched.

Best,

Fengchao

**Comment by JB91451** [comment]
Dear Fengchao,

Thank for the bugfix. I downloaded it will try with this as soon as our server has free capacity (likely tomorrow afternoon) and keep you updated.

Thank you also for the hint about the modification. I always get a bit confused by the system, how the modifications are defined in which search engine.

Best,
Juergen

**Comment by JB91451** [comment]
Dear Fengchao,

The files that failed before run through over night. Thus I think everything works nicely now.

Thank you again,
Juergen

**Comment by fcyu** [comment]
You are welcome.

Best,

Fengchao
