### ISSUE TITLE
MSBooster shows an error for non-specific HLA peptidomics - timsTOF data

### ISSUE THREAD

**Issue by mshahbazy** [Nesvilab/MSFragger#321]
Dear MSFragger team, 

I encountered an error when trying to use FragPipe to search a timsTOF DDA dataset for immunopeptidomics, as follows: 

**Loading predicted spectra
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 91 remaining tasks**

The log is attached. Would you please let me know how I can resolve the issue? 

Thanks and regards, 
Moh

[log_2024-06-06_18-51-57_Bjoren_AB_run1-25_06062024_test01.txt](https://github.com/user-attachments/files/15688680/log_2024-06-06_18-51-57_Bjoren_AB_run1-25_06062024_test01.txt)

**Comment by fcyu** [comment]
Duplicated issue https://github.com/Nesvilab/FragPipe/issues/1616
