### ISSUE TITLE
Windows Java Configuration in Command Prompt

### ISSUE THREAD

**Issue by kostrouc** [Nesvilab/MSFragger#326]
May you confirm which Java installation is required to run fragpipe from a Windows command prompt?

The java version 1.8.0_421 included with FragPipe-jre-22.0 does not appear to work.

`C:\Users\Administrator\Desktop\FragPipe-jre-22.0\fragpipe\bin>set JAVA_HOME="C:\Program Files (x86)\Java\jre1.8.0_421"`
`C:\Users\Administrator\Desktop\FragPipe-jre-22.0\fragpipe\bin>set PATH=%JAVA_HOME%\bin;%PATH%`
`C:\Users\Administrator\Desktop\FragPipe-jre-22.0\fragpipe\bin>java -version`
`java version "1.8.0_421"`
`Java(TM) SE Runtime Environment (build 1.8.0_421-b09)`
`Java HotSpot(TM) Client VM (build 25.421-b09, mixed mode, sharing)`

`C:\Users\Administrator\Desktop\FragPipe-jre-22.0\fragpipe\bin>.\fragpipe.bat --headless --workflow "D:\fragpipe\katie\saileeconfig.workflow" --manifest "D:\fragpipe\katie\saileemanifest.fp-manifest" --workdir "D:\fragpipe\katie\testdatasets"`
`Exception in thread "main" java.lang.UnsupportedClassVersionError: com/dmtavt/fragpipe/FragPipeMain has been compiled by a` `more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file` `versions up to 52.0`
        `at java.lang.ClassLoader.defineClass1(Native Method)`
        `at java.lang.ClassLoader.defineClass(Unknown Source)`
        `at java.security.SecureClassLoader.defineClass(Unknown Source)`
        `at java.net.URLClassLoader.defineClass(Unknown Source)`
        `at java.net.URLClassLoader.access$100(Unknown Source)`
       ` at java.net.URLClassLoader$1.run(Unknown Source)`
       ` at java.net.URLClassLoader$1.run(Unknown Source)`
        `at java.security.AccessController.doPrivileged(Native Method)`
        `at java.net.URLClassLoader.findClass(Unknown Source)`
       ` at java.lang.ClassLoader.loadClass(Unknown Source)`
        `at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)`
        `at java.lang.ClassLoader.loadClass(Unknown Source)`
        `at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)`

**Comment by fcyu** [comment]
Something must have been messed up because what [FragPipe-jre-22.0.zip](https://github.com/Nesvilab/FragPipe/releases/download/22.0/FragPipe-jre-22.0.zip) included is OpenJDK 17.

I guess you could delete all files, and re-download FragPipe, MSFragger, IonQuant, and IonQuant.

Best,

Fengchao
