### ISSUE TITLE
4.1 writing _uncalibrated.mzML for RAW files

### ISSUE THREAD

**Issue by chambm** [Nesvilab/MSFragger#327]
I'm doing a data_type=2 GPF search. Is it supposed to always write the uncalibrated mzML even though I have:
write_calibrated_mzml = 0
write_uncalibrated_mgf = 0

**Comment by fcyu** [comment]
It always write the `*_uncalibrated.mzML` if the input is in `.raw` and `.d` because some downstream tools can't read them.

Best,

Fengchao

**Comment by chambm** [comment]
Can you make that an option? Not only are those files big but BiblioSpec currently prefers _uncalibrated.mzML over .RAW, even though it's capable of reading RAW. In this case for performance and space-savings we'd would want to prefer RAW. It would be easiest to achieve that by just not making the mzML in the first place, but in the short term I can just delete it before running BlibBuild.

**Comment by fcyu** [comment]
TBH, I don't want to add this option. We had this option before if I remembered it correctly, but there were just too many options, and we always need `_uncalibrated.mzML` with raw as input.

Best,

Fengchao

**Comment by chambm** [comment]
No problem, I can just the delete the files. I feel like since it's in the same vein as the other two options it would fit right in and it doesn't matter if there's 120 options or 121 options. :)

**Comment by chambm** [comment]
Wait what happens if the RAW location is read-only? Does it error or just skip the writing?

**Comment by fcyu** [comment]
That's correct, it prints something like `Could not write XXX_uncalibrated.mzML. It will not affect MSFragger's result.`.

And I agree that it will be an issue because MSFragger also writes `*.pepXML` and `*.pin` files to that directory. I always want to change MSFragger to write the files to the result folder, but don't have time to do that.

Best,

Fengchao

**Comment by fcyu** [comment]
Hi Matt,

After a second thought, I decided to add the `write_uncalibrated_mzml` and removed the `write_uncalibrated_mgf` that is used nowhere. Let me know if you want to test the new version. Maybe can wait until https://github.com/Nesvilab/MSFragger/issues/324 is also done.

Best,

Fengchao

**Comment by chambm** [comment]
Hi @fcyu what version did `write_uncalibrated_mgf` stop working in? Or by "used nowhere" did you mean MSFragger users?

**Comment by fcyu** [comment]
Hi Matt,

> what version did write_uncalibrated_mgf stop working in? 

Start from the next version.

> Or by "used nowhere" did you mean MSFragger users?

I am not sure about the users, but the mgf file is not used nowhere in the downstream steps in FragPipe. The reason for MSFragger generating mgf or mzML file is that the downstream tools need it (because they can't read raw or .d).

Best,

Fengchao
