### ISSUE TITLE
Orbitrap FAIMS 2CV

### ISSUE THREAD

**Issue by babsillo** [Nesvilab/MSFragger#330]
Hi,

I recently got an orbitrap. And I want to analyse a DDA dataset.
It was aquired using two different CV-values.
I know at this point working with DIA and 2 CV values (by using the FAIMS) creates problems during quantification.
There is a tutorial to still get a nice and reliable quantification. (with using DIANN stand alone)
But with DDA data, I wanted to ask;
Is there a problem using DDA data from thermo.raw files aquired with 2 differnt CVs?
And does it affect the quantitation in a wrong way?
Or do I need to extract the 2CV traces and save them separately as raw and to separte quan?

I am sorry for my more "beginners" question. I just started using thermo data.
so far 2CVs data gets more ID than 1CV - so if possible I would stick to it.

Thanks for your help in advance.
Best
Barbara

**Comment by fcyu** [comment]
Hi Barbara,

> Is there a problem using DDA data from thermo.raw files aquired with 2 differnt CVs?
> And does it affect the quantitation in a wrong way?

No, there is no problem. FragPipe support the multiple CVs DDA data natively.

> Or do I need to extract the 2CV traces and save them separately as raw and to separte quan?

No, you don't need to.

Best,

Fengchao

**Comment by babsillo** [comment]
Thank you so much for your fast reply.
Best
Barbara
