### ISSUE TITLE
About msfragger fdr control

### ISSUE THREAD

**Issue by Heisenburger2020** [Nesvilab/MSFragger#331]
In the output file pepXML, psm.tsv and peptide.tsv, there seems to be no qvalue, I wish to recalculate it and I wonder if hyperscore is the final score used to do fdr control(assuming use msbooster)?

**Comment by fcyu** [comment]
Hyperscore is not the final score used to do FDR control. Please use FragPipe to run MSFragger: https://fragpipe.nesvilab.org/. It can run the whole workflow from MSFragger to FDR control.

Best,

Fengchao

**Comment by Heisenburger2020** [comment]
Dear Prof. Yu,

I tried fragpipe, but I still cannot find the fdr for each peptide or psm in all output files. I am currently doing some evaluation, I wish to get this information.

Best,
Jiale Zhao

**Comment by anesvi** [comment]
I think you need to read our papers and tutorials. FDR of what? Peptides, PSM, protein? If just protein, then use best peptide probability column for sorting and filtering. You would need to check ' print decoys' box and relax the FDR filter to print more IDs. Looking at PSM it peptide files more complicated since they are also protein FDR filtered.

**Comment by Heisenburger2020** [comment]
Thank you for your reply. I need fdr of the peptide level. I could not find it in the output files.

**Comment by anesvi** [comment]
There is Probability column in PSM and peptide , that's what you need to use. And remember to turn off all filters in validation tab (Percolator min threshold set to 0) and set --prot to 1 to apply protein FDR. And print decoys

**Comment by Heisenburger2020** [comment]
Thank you for your help!

Best,
Jiale

**Comment by anesvi** [comment]
Alternatively use percolator PIN files and redo the filtering based on those files. For that, check " write intermediate percolator files".

**Comment by Heisenburger2020** [comment]
Dear Profs,

Thank you for your detailed instructions.

I have another minor question: how can I get the number of identified peptides(not sequence, with different modification) of msfragger directly/officially. Since it seems that in peptide.tsv files, the first column only appears once(only record sequence). I am confused about the records of modification. I assume that modifications separated by a comma are modifications on a peptide at the same time. How about different modifications on peptides not at the same time case.(eg: C(+57)CCCC, CC(+57)CCC)

Best,
Jiale

**Comment by fcyu** [comment]
You could post-process psm.tsv to get the peptides with modificaitons.

Best,

Fengchao

**Comment by Heisenburger2020** [comment]
Dear Profs,

For a specific experiment, I tried to stat the number of peptides(without mod) with psm.tsv(45000). But it is significantly larger than the line number of peptide.tsv(39000). Is this because psm.tsv results are filtered by psm level fdr, and results from peptide.tsv are filtered by peptide level fdr?

Best,
Jiale

**Comment by Heisenburger2020** [comment]
Dear Profs,

Also, It seems that msfragger used protein level information to filter peptide level results. I wonder this step affect which files. Are PIN/psm.tsv/peptide.tsv all affected? I understand this can be useful in some cases. This does not seem to be statistically proper for evaluation with the trap database to assess fdr control and accuracy. Is there a way to get results without protein-level information?

Best,
Jiale

**Comment by anesvi** [comment]
Correct, PSM and peptide files are filtered at their own PSM/peptide level. Protein information is NOT used in MSFragger for filtering.

**Comment by Heisenburger2020** [comment]
Sorry about my misunderstood. I thought this step uses protein information. Quite curious what does this step do:
<img width="1143" alt="image" src="https://github.com/user-attachments/assets/55beb69e-6633-487b-99d9-7c547eca6abe">

I have done a experiment:
raw: Human Hela
fasta: Human+Arabidopsis thaliana proteins()
tryptic peptide number: human/Arbidopsis = 3/2
fdr: 0.01(peptide.tsv)
Statistically there should be about 0.4% peptides in peptide.tsv belongs to Arabidopsis(0.01 * 0.4)
However I got 0.082%

Also proteins from peptide.tsv is identical to protein.tsv.

Maybe I made a mistake somewhere, files are attached to this message. I renamed the extension because github do not support tsv.
[peptide.txt](https://github.com/user-attachments/files/17617900/peptide.txt)
[protein.txt](https://github.com/user-attachments/files/17617902/protein.txt)

**Comment by anesvi** [comment]
You asked about MSFragger. I answered. Your screenshot is the output from philosopher, not MSFragger. I am sorry but you need to understood the entire process better.

**Comment by Heisenburger2020** [comment]
Sorry about my mistake, I should have read doc more carefully. Thank you for your patient explanation :) !

**Comment by Heisenburger2020** [comment]
I am sorry that I do not know how to close philosopher in frag-pipe. I tried to avoid any prophet but I still got philosopher in log.

![image](https://github.com/user-attachments/assets/676db626-782f-433c-a971-b7e4640a2049)

**Comment by fcyu** [comment]
> Do these steps use high level information to correct low level reports?

Without enable protein inference, it no longer calculate or apply the protein FDR.

The reason of not getting 1% FDR is because of the "min probability 0.5" in the Percolator panel. It looks like your targets and decoys are well separated so that the probability threshold should be lower.

Best.

Fengchao
