### ISSUE TITLE
Razor Intensity is missing.

### ISSUE THREAD

**Issue by adrian-kri** [Nesvilab/MSFragger#333]
I performed an analysis on Fragpipe/MS Fragger. Once I transfer the data to Perseus, I cannot find "razor intensity", but only "intensity" for the combined_protein.tsv. Can I assume that these are simply the same and that just labelling within MS Fragger changed? Thank you!

Best,
Adrian

**Comment by fcyu** [comment]
Yes, we renamed the "razor intensity" to "intensity".

Best,

Fengchao
