### ISSUE TITLE
Processing interrupted, stopping MsFragger

### ISSUE THREAD

**Issue by Golden-proteogenomics** [Nesvilab/MSFragger#35]
Hello,
 I am sorry to distrube you again about my task to search used the FragPipe.exe. The specific dataset and log files of my searching task  are placed in the below link.
please give me a hand in  your leisure time to help me to use it.
thanks again!
jinshuai Sun 
[log-fragpipe-run-at_2019-07-30_17-30-46.log](https://github.com/Nesvilab/MSFragger/files/3447239/log-fragpipe-run-at_2019-07-30_17-30-46.log)
[CHPP_Seq.zip](https://github.com/Nesvilab/MSFragger/files/3447241/CHPP_Seq.zip)

**Comment by chhh** [comment]
Most likely causes and solutions:
 - The mzML file might have become corrupt. That often happens when you store lots of data non-redundantly on hard drives. A single bit flipped somewhere and now the file is unreadable. In that case re-converting the file from original RAW to mzML can help.
 - You have some weird symbol in the meta-information section (e.g. some Chinese glyph that is not in ASCII part of UTF8). The original RAW file path, for example, might have contained some illegal characters and now that breaks the parser.

I will need to see the file `LysC3.mzML` to investigate further.

In the meantime you can also temporarily exclude the `LysC3.mzML` from your analysis to see if the processing yields expected results downstream.

**Comment by Golden-proteogenomics** [comment]
there is a problem that the LysC3.mzML file is biger for submission of gethub limitation, Could I send it for your email?

**Comment by anesvi** [comment]
Not by email, please!!!!

**Comment by Golden-proteogenomics** [comment]
if not by email, which way I can chose to transmit the file you need to you?

**Comment by fcyu** [comment]
@Golden-proteogenomics Could you please give me an email address so that I can share a Box folder with you? You can upload your file to the folder.

**Comment by Golden-proteogenomics** [comment]
email: sjsshuai@126.com



At 2019-07-31 01:53:51, "Fengchao" <notifications@github.com> wrote:


@Golden-proteogenomics Could you please give me an email address so that I can share a Box folder with you? You can upload your file to the folder.

**Comment by fcyu** [comment]
@Golden-proteogenomics Invitation sent. Please check your email.

**Comment by Golden-proteogenomics** [comment]
The email sjsshuai@126.com is not error and I can receive your invitation to use BOX, However, I canont open the reasponding interlinkage, which maybe the interlinkage was off for our country, In the another hand, I try to do it in all new *.mzML files again, if I have any new probelms about this, I guess I will distrube you. thanks again.

**Comment by Golden-proteogenomics** [comment]
There is still a new error which is different from before when I used the new *mzML files to research again. please what can I do for this error？
[log-fragpipe-run-at_2019-07-31_10-05-01.log](https://github.com/Nesvilab/MSFragger/files/3449485/log-fragpipe-run-at_2019-07-31_10-05-01.log)

**Comment by fcyu** [comment]
@Golden-proteogenomics Your log said: `Cannot find MS file at I:\Shuai\2019-CHPP\One_reveice\mzML\GluC\GluC3.mzML`

**Comment by Golden-proteogenomics** [comment]
Thanks, The problem why always to arise the errors was solved, whose reasons is runing three MSFragger.exe at the same times. I used the three windows to run the software in the time lead to error. Now, I have a the new problem that I want to know what modifications in my datasets  can be idenficated in this tools, However, the peptide files only find some usually modifications,  I don't know why this is a problem or how to find unconventional modifications.

**Comment by anesvi** [comment]
If you do open search, you will find peptides with mass shifts. Those are the peptides with potential modifications.

I think at this point you need to read the literature (MSFragger manuscript, other papers) on various strategies for PTM searches,

This site is for technical support.

**Comment by fcyu** [comment]
The open modification should be listed in the `Observed Modifications` column. If it is empty, could you please double check your fragger.param file?

**Comment by Golden-proteogenomics** [comment]
Yes, The following links are my search results. Could  you valid the param which i want to set up the open-search? 
1)  I also want to if I want to know which and what peptides with potential modifications, I will see the peptide.tsv files or other files? 
2) The modification is only have the mass shift not to give the specific modification, So, How to confirm the specific modification with the peptides?Could you give me  a  more detail example to tell me?
[fragger.zip](https://github.com/Nesvilab/MSFragger/files/3451992/fragger.zip)
[modifications.zip](https://github.com/Nesvilab/MSFragger/files/3451993/modifications.zip)
[peptide.zip](https://github.com/Nesvilab/MSFragger/files/3451994/peptide.zip)
