### ISSUE TITLE
Bioconda distribution

### ISSUE THREAD

**Issue by MiguelCos** [Nesvilab/MSFragger#38]
Hello,

I am planning to start using MSFragger in my research and I would like to know more about the type of licence associated with the software. Specifically, I am interested to know if it would be possible to distribute it via Bioconda. It would be very useful for me and I would be glad to execute the implementation. 

Kind regards.

**Comment by anesvi** [comment]
Dear Miguel,

Thank you for your interest in using the software.

At present, MSFragger cannot be distributed in Bioconda or other ways – each user needs to sign the license agreement and download the original binary at
https://umich.flintbox.com/?embed=true#technologies/a8dd00a2-c057-4125-823b-adffac748490
where you can see the license the agreement form

After that, you can get new versions (under the same license agreement) as described on our webpage
https://github.com/Nesvilab/MSFragger/wiki/Preparing-MSFragger#Downloading-MSFragger

Best,
Alexey

Alexey I. Nesvizhskii, Ph. D.
Professor of Pathology
Professor of Computational Medicine and Bioinformatics
Director, Proteomics Resource Facility
Director, Proteome Informatics of Cancer Training Program
University of Michigan
4237 Med Sci I, 1301 Catherine Road
Ann Arbor, MI  48109-0602
USA

Ph: (734) 764-3516
Fx: (734) 936-7361
Email:  nesvi@med.umich.edu<mailto:nesvi@med.umich.edu>
Web:   www.nesvilab.org<http://www.nesvilab.org/>
