### ISSUE TITLE
MFragger example files

### ISSUE THREAD

**Issue by Golden-proteogenomics** [Nesvilab/MSFragger#39]
Hello, 
   I want to know how to set MSGFPlus_Params.txt file when I use the MSFragger software to open search data and I do not find the example files about open search Params. Could you give me some suggestions to try open search?

**Comment by chhh** [comment]
I don't understand, is this a question about setting up MSGF+ parameters?

**Comment by fcyu** [comment]
Please read the [documents](https://msfragger.nesvilab.org/) carefully before asking any question. There are **MSFragger** parameter examples. 

In terms of MSGF+, please go to another GitHub repo [https://github.com/MSGFPlus/msgfplus](https://github.com/MSGFPlus/msgfplus). And again, please read the documents before asking any question there.

Good luck,

Fengchao

**Comment by Golden-proteogenomics** [comment]
Thank you for your suggestion, Now, it work. But here's another problem which details description as the follow displayed. 
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.NullPointerException
	at b.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Process 'MsFragger' finished, exit code: 1

Process returned non-zero exit code, stopping
MsFragger
java -cp I:\Shuai\2019-CHPP\One_reveice\mzML\FragPipe.exe umich.msfragger.util.FileMove C:\Users\Xu-Lab-30\Desktop\linshi\shi\Trypsin31.pepXML C:\Users\Xu-Lab-30\Desktop\linshi\shi\RESULT\Trypsin31.pepXML

~~~~~~~~~~~~~~~~~~~~
Stopping 16/19 processes (3 already finished)
Processing interrupted, stopping MsFragger

~~~~~~~~~~~~~~~~~~~~
Stopping 0/0 processes (0 already finished)

**Comment by fcyu** [comment]
Could you please send us the log or fragger.params.

Best,

Fengchao

**Comment by Golden-proteogenomics** [comment]
Thanks，the fragger.params and the log were attached
[log-fragpipe-run-at_2019-10-09_10-19-54.log](https://github.com/Nesvilab/MSFragger/files/3705296/log-fragpipe-run-at_2019-10-09_10-19-54.log)

**Comment by Golden-proteogenomics** [comment]
Although I have reinstalled the latest version of MSFragger software, the problem still arises.

**Comment by fcyu** [comment]
Looks like something wrong happened in mass calibration. Could you please share the first mzML file to us?

Thanks,

Fengchao

**Comment by Golden-proteogenomics** [comment]
Yes, the first mzML file is not attached because thst's still a large file after compression. However, this problem that you think something wrong in mzMZL files, I do not follow your point due to when I use 36 mzML files containing that three files to search and it work.

**Comment by Golden-proteogenomics** [comment]
Hello, there are some problems when using the MSFragre to search the LysC samples data. The log file of engine was attached below. 
[log_2019-10-09_13-41-52.txt](https://github.com/Nesvilab/MSFragger/files/3705756/log_2019-10-09_13-41-52.txt)

**Comment by fcyu** [comment]
I apologize if I didn't explain it clearly. I need your file to reproduce the error so that I can find the reason. It doesn't mean that something is wrong with your mzML files.

If you cannot provide your files, we cannot locate the error and find the reason. So, you are on your own now.

Best,

Fengchao
