### ISSUE TITLE
PeptideProphet + msfragger opensearch issue 

### ISSUE THREAD

**Issue by GeorgesBed** [Nesvilab/MSFragger#47]
Hello dev team,
I am currently using msfragger v2.2 (non-specific digestion  + open search) in combination with philosopher v2. I noticed that the Mixture model quality test is failing for most of my searches for all charges (1+ to 7+) when the msfragger option 'localize_delta_mass' is on. 

I attached my msfragger config file below and I would like to mention again that it's not an experiment specific issue.

[Fragger_Params.txt](https://github.com/Nesvilab/philosopher/files/3837310/Fragger_Params.txt)

Are you aware of any explanation for this behaviour ?

--------------------------
# software versions:
- msfragger v2.2
- philosopher v2
- MSConvert (peak picking on) proteowizard version = 3.0.19304.503cb4044
--------------------------
Best.

**Comment by anesvi** [comment]
Georges

Yes, it is a problem we are well aware of.

What +- Da window are you using? Please reduce to -150 to 500 (of you are using -500 to 500)
It helped with the same problem for trypsin-specific open searches.

If you still get PeptideProphet failing for 2+/3+/4+ , then you may have to uncheck localize delta mass. We do not have a good solution now.
And non-specific +open searching in general is not something that is easy to do and requires some playing with advanced options. So we do not support it as a standard application, only as part of collaborative studies.

Best,
Alexey

**Comment by GeorgesBed** [comment]
Hello Alexey,
I am using a -300 +300  range but MSFragger is changing the negative one to -150 automatically.
Do you think, turning off the localization and then using PTMProphet with MASSDIFFMODE afterward would yield good results ?
I was using PTMProphet before the localization support. However, the results were not discriminative after looking back at the sites probablilites.

Best,
Georges

On Nov 12 2019, at 6:37 pm, Alexey Nesvizhskii <notifications@github.com> wrote:
Georges

Yes, it is a problem we are well aware of.

What +- Da window are you using? Please reduce to -150 to 500 (of you are using -500 to 500)
It helped with the same problem for trypsin-specific open searches.

If you still get PeptideProphet failing for 2+/3+/4+ , then you may have to uncheck localize delta mass. We do not have a good solution now.
And non-specific +open searching in general is not something that is easy to do and requires some playing with advanced options. So we do not support it as a standard application, only as part of collaborative studies.

Best,
Alexey

**Comment by fcyu** [comment]
Looks like turning off `localize_delta_mass` is the only option.

Best,

Fengchao
