### ISSUE TITLE
How to get higher precision on expectation scores?

### ISSUE THREAD

**Issue by shawn-peng** [Nesvilab/MSFragger#49]
Currently, I'm using the TSV format outputs and the expectation scores are with 4 digits after the decimal point. To analyze the scores I need higher precision, say with scientific notation. How can I get such precision?

Thanks,
Yisu

**Comment by prvst** [comment]
I believe you are talking about Philosopher's output, not MSFragger, right ?

**Comment by shawn-peng** [comment]
No, I'm only used msfragger on linux system with command line.

**Comment by fcyu** [comment]
Hi Yisu,

Thanks for your feedback. We will let MSFragger print the whole decimal points in the next release.

Best,

Fengchao

**Comment by shawn-peng** [comment]
Awesome! Thanks!
