### ISSUE TITLE
Bruker native libraries not found

### ISSUE THREAD

**Issue by magnuspalmblad** [Nesvilab/MSFragger#53]
Hi there!

I'm trying to run MSFragger on a TIMS-TOF dataset. However, MSFragger cannot seem to find the Bruker native libraries. I have ProteoWizard with the vendor libraries, DataAnalysis 5.0 and pretty much the entire Bruker software tree in the machine. I updated MSFragger to the latest version (2.2), and also have the latest timsdata.dll with the other Bruker DLLs (in C:\Program Files\Common Files\Bruker Daltonik\DLLs), as well as in the local folder. Which "native libraries" are needed, and where does MSFragger expect them? 

Many thanks in advance!

Magnus

The output from the command line:

H:\<folder with .d directory and MSFragger>java -jar MSFragger-2.2.jar closed_fragger.params <.d directory>
MSFragger version MSFragger-2.2
Batmass-IO version 1.17.1
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_231, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 14 GB memory

Checking <.d data directory>
Failed in checking <.d directory path>
Bruker native libraries not found

**Comment by fcyu** [comment]
Hi Magnus,

Thanks for your interest in MSFragger. You need to download and unzip the whole `MSFragger-2.2.zip` from [https://msfragger.arsci.com/upgrader/](https://msfragger.arsci.com/upgrader/). There is an `ext` folder, which contains needed libraries, in it. Keeping MSFragger.jar and the `ext` folder in the same folder and MSFragger will be able to find the libraries.

Best,

Fengchao

**Comment by magnuspalmblad** [comment]
Thanks - that helped! I had moved the JAR file leaving the ext folder behind, but now it runs.

FragPipe already worked, but I wanted to run it on the command line too.


Cheers,

Magnus

**Comment by chhh** [comment]
@magnuspalmblad Just a note: the same requirement holds for FragPipe, it does use those libraries and extra programs in the `ext` folder (sitting next to MSFragger.jar).
