### ISSUE TITLE
Calibration leads to out-of-memory error

### ISSUE THREAD

**Issue by magnuspalmblad** [Nesvilab/MSFragger#55]
For very large databases (10M+ sequences), the (re)calibration is the limiting step. MSFragger runs out of memory even if splitting the database in 99 chunks and making 300 GB memory available. Disabling "Calibrate masses" prevents this, and much less memory is required. But of course, then the masses are not recalibrated. The data is PASEF from timsTOF Pro.

Example output:

Traceback (most recent call last):
  File "C:\Users\NMPALM~1\AppData\Local\Temp\fragpipe\msfragger_pep_split.py", line 447, in <module>
    main()
  File "C:\Users\NMPALM~1\AppData\Local\Temp\fragpipe\msfragger_pep_split.py", line 435, in main
    calibrate_mzBIN, params_txt_new = calibrate(fasta_path_sample, calibrate_mass)
  File "C:\Users\NMPALM~1\AppData\Local\Temp\fragpipe\msfragger_pep_split.py", line 349, in calibrate
    raise AssertionError(p)
AssertionError: <subprocess.Popen object at 0x0000018BF31899C8>

**Comment by fcyu** [comment]
Thanks for reporting this error. Could you please share the whole log with us?

Thanks,

Fengchao

**Comment by magnuspalmblad** [comment]
System info:
System OS: Windows Server 2012 R2, Architecture: AMD64
Java Info: 1.8.0_231, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

Version info:
FragPipe version 12.1
MSFragger version 2.2
Philosopher version 2.0.0 (build 1573250062)


LCMS files:
  Experiment/Group: 
  - C:\TPP\data\080120_NISTcrowBrain_JH25colNoTrp_mlpl12_60m_Slot1-38_1_653.d

10 commands to execute:
Workspace [Work dir: C:\TPP\data]
C:\TPP\data\philosopher.exe workspace --clean
Workspace [Work dir: C:\TPP\data]
C:\TPP\data\philosopher.exe workspace --init
MsFragger [Work dir: C:\TPP\data]
C:\Program Files\Python37\python.exe C:\Users\NMPALM~1\AppData\Local\Temp\38\fragpipe\msfragger_pep_split.py 99 "java -jar -Dfile.encoding=UTF-8 -Xmx300G" C:\TPP\data\MSFragger-2.2.jar C:\TPP\data\fragger.params C:\TPP\data\080120_NISTcrowBrain_JH25colNoTrp_mlpl12_60m_Slot1-38_1_653.d
Crystal-C [Work dir: C:\TPP\data]
java -Dbatmass.io.libs.thermo.dir="C:\TPP\data\ext\thermo" -Xmx300G -cp "C:\Users\NMPALM~1\AppData\Local\Temp\38\fragpipe\batmass-io-1.17.1.jar;C:\Users\NMPALM~1\AppData\Local\Temp\38\fragpipe\grppr-0.3.23.jar;C:\Users\NMPALM~1\AppData\Local\Temp\38\fragpipe\original-crystalc-1.0.8.jar" crystalc.Run C:\TPP\data\crystalc-0-080120_NISTcrowBrain_JH25colNoTrp_mlpl12_60m_Slot1-38_1_653.pepXML.params C:\TPP\data\080120_NISTcrowBrain_JH25colNoTrp_mlpl12_60m_Slot1-38_1_653.pepXML
ReportDbAnnotate [Work dir: C:\TPP\data]
C:\TPP\data\philosopher.exe database --annotate C:\TPP\data\GCF_Alveolata_Fungi.fasta --prefix rev_
PeptideProphet [Work dir: C:\TPP\data]
C:\TPP\data\philosopher.exe peptideprophet --nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel -2 --decoy rev_ --database C:\TPP\data\GCF_Alveolata_Fungi.fasta --combine 080120_NISTcrowBrain_JH25colNoTrp_mlpl12_60m_Slot1-38_1_653_c.pepXML
ProteinProphet [Work dir: C:\TPP\data]
C:\TPP\data\philosopher.exe proteinprophet --maxppmdiff 2000000 --output combined C:\TPP\data\interact.pep.xml
ReportFilter [Work dir: C:\TPP\data]
C:\TPP\data\philosopher.exe filter --sequential --razor --mapmods --prot 0.01 --tag rev_ --pepxml C:\TPP\data --protxml C:\TPP\data\combined.prot.xml
ReportReport [Work dir: C:\TPP\data]
C:\TPP\data\philosopher.exe report
Workspace [Work dir: C:\TPP\data]
C:\TPP\data\philosopher.exe workspace --clean
~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~ fragpipe.config ~~~~~~~~~
#FragPipe (12.1) runtime properties
#Tue Jan 21 17:31:52 CET 2020
override_charge=false
ui.name.report.check.genspeclib=false
ui.imquant.im-tol=0.05
calibrate_mass=On and find optimal parameters
search_enzyme_butnotafter=P
max_variable_mods_per_mod=3
delta_mass_exclude_ranges=(-1.5,3.5)
ui.name.crystalc.max-charge=6
output_report_topN=1
ui.imquant.rt-tol=0.4
misc.fragger.remove-precursor-range-hi=1.5
ui.name.reoirt.pep-level-summary=false
misc.slice-db=99
output_format=PEP_XML
ui.name.downstream.check.run-pep-proph=true
ui.imquant.mz-tol=10
ui.name.crystalc.run-crystalc=true
histo_smoothbins=2
peakpicking_width=0.002
ui.name.report.check.dontuseprotprophfile=false
misc.fragger.precursor-charge-hi=4
ui.name.report.check.multiexp=false
ui.run-quantification=false
misc.fragger.digest-mass-lo=500
min_fragments_modelling=2
ui.name.report.check.printdecoys=false
allowed_missed_cleavage=2
search_enzyme_cutafter=KR
precursor_mass_lower=-50
misc.fragger.clear-mz-hi=0
peakpicking_promRatio=0.3
output_extended=false
misc.fragger.remove-precursor-range-lo=-1.5
fragment_mass_units=PPM
localization_background=4
ui.name.crystalc.precursor_mass=20
num_enzyme_termini=SEMI
ui.name.report.text.filter=--sequential --razor --mapmods --prot 0.01
ui.name.crystalc.correct_isotope_error=false
min_matched_fragments=4
ui.freequant.is-run=true
max_fragment_charge=2
misc.fragger.precursor-charge-lo=1
ui.name.downstream.text.pep-proph-cmd=--nonparam --expectscore --decoyprobs --masswidth 1000.0 --clevel -2
ui.name.downstream.check.separate-protxml=false
varmod_masses=
intensity_transform=None
ui.name.report.generate-report=true
add_topN_complementary=0
num_threads=1
output_max_expect=50
use_topN_peaks=100
remove_precursor_peak=Do not remove
zero_bin_mult_expect=1.00
allow_multiple_variable_mods_on_residue=false
precursor_mass_mode=selected
ui.name.report.check.mzid=false
ui.freequant.rt-tol=0.4
precursor_mass_units=PPM
mass_offsets=0
misc.ram=300
digest_min_length=7
zero_bin_accept_expect=0.00
minimum_peaks=15
digest_max_length=50
misc.fragger.clear-mz-lo=0
ui.imquant.min-freq=0.50
track_zero_topN=0
ui.freequant.mz-tol=10
precursor_true_units=PPM
ui.name.downstream.check.combine-pepxml=true
localize_delta_mass=true
max_variable_mods_combinations=5000
misc.fragger.enzyme-dropdown=trypsin
ui.name.downstream.check.run-prot-proph=true
search_enzyme_name=trypsin
clip_nTerm_M=true
ui.name.report.run-shepherd=false
ui.name.crystalc.precursor_isolation_window=0.7
ion_series_definitions=
ui.imquant.is-plot=false
ui.name.downstream.text.prot-proph-cmd=--maxppmdiff 2000000
fragment_ion_series=b,y
precursor_true_tolerance=20
ui.name.crystalc.isotope_number=3
report_alternative_proteins=true
precursor_mass_upper=65
ui.imquant.is-run=false
isotope_error=-1/0/1/2/3
misc.fragger.digest-mass-hi=5000
fragment_mass_tolerance=50
minimum_ratio=0.01

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Workspace [Work dir: C:\TPP\data]
C:\TPP\data\philosopher.exe workspace --clean
INFO[17:31:53] Executing Workspace  v2.0.0                  
INFO[17:31:53] Removing workspace                           
INFO[17:31:53] Done                                         
Process 'Workspace' finished, exit code: 0

Workspace [Work dir: C:\TPP\data]
C:\TPP\data\philosopher.exe workspace --init
INFO[17:31:53] Executing Workspace  v2.0.0                  
INFO[17:31:54] Creating workspace                           
INFO[17:31:54] Done                                         
Process 'Workspace' finished, exit code: 0

MsFragger [Work dir: C:\TPP\data]
C:\Program Files\Python37\python.exe C:\Users\NMPALM~1\AppData\Local\Temp\38\fragpipe\msfragger_pep_split.py 99 "java -jar -Dfile.encoding=UTF-8 -Xmx300G" C:\TPP\data\MSFragger-2.2.jar C:\TPP\data\fragger.params C:\TPP\data\080120_NISTcrowBrain_JH25colNoTrp_mlpl12_60m_Slot1-38_1_653.d
MSFragger version MSFragger-2.2
Batmass-IO version 1.17.1
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Windows Server 2012 R2, Architecture: AMD64
Java Info: 1.8.0_231, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 266 GB memory

Checking C:\TPP\data\080120_NISTcrowBrain_JH25colNoTrp_mlpl12_60m_Slot1-38_1_653.d...

There is a mzBIN file from C:\TPP\data\080120_NISTcrowBrain_JH25colNoTrp_mlpl12_60m_Slot1-38_1_653.d. Will use this mzBIN file.
If still want to use the .d folder, please delete the file C:\TPP\data\080120_NISTcrowBrain_JH25colNoTrp_mlpl12_60m_Slot1-38_1_653.mzBIN and re-run MSFragger.

***********************************FIRST SEARCH************************************
Parameters:
num_threads = 1
database_name = GCF_Alveolata_Fungi.fasta
decoy_prefix = rev_
precursor_mass_lower = -20.0
precursor_mass_upper = 20.0
precursor_mass_units = 1
precursor_true_tolerance = 20.0
precursor_true_units = 1
fragment_mass_tolerance = 50.0
fragment_mass_units = 1
calibrate_mass = 2
write_calibrated_mgf = true
isotope_error = 0/1
mass_offsets = 0
precursor_mass_mode = SELECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
search_enzyme_name = trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P
num_enzyme_termini = 2
allowed_missed_cleavage = 1
clip_nTerm_M = true
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_mod = 3
max_variable_mods_combinations = 5000
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50.0
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 2
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 100
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.01
intensity_transform = 0
remove_precursor_peak = 0
remove_precursor_range = -1.50,1.50
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^
add_A_alanine = 0.000000
add_B_user_amino_acid = 0.000000
add_C_cysteine = 57.021464
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_D_aspartic_acid = 0.000000
add_E_glutamic_acid = 0.000000
add_F_phenylalanine = 0.000000
add_G_glycine = 0.000000
add_H_histidine = 0.000000
add_I_isoleucine = 0.000000
add_J_user_amino_acid = 0.000000
add_K_lysine = 0.000000
add_L_leucine = 0.000000
add_M_methionine = 0.000000
add_N_asparagine = 0.000000
add_Nterm_peptide = 0.0
add_Nterm_protein = 0.0
add_O_user_amino_acid = 0.000000
add_P_proline = 0.000000
add_Q_glutamine = 0.000000
add_R_arginine = 0.000000
add_S_serine = 0.000000
add_T_threonine = 0.000000
add_U_user_amino_acid = 0.000000
add_V_valine = 0.000000
add_W_tryptophan = 0.000000
add_X_user_amino_acid = 0.000000
add_Y_tyrosine = 0.000000
add_Z_user_amino_acid = 0.000000
Not enough memory allocated to MSFragger.
If running using FragPipe: in MSFragger tab, increase the amount of memory allocated using RAM (Gb) parameter. If your computer does not have enough memory, use “Split database” option (requires python; see Configuration page of FragPipe). Set “Split database” parameter to 2. If the program continues to crash, gradually increase the “Split database” value (e.g. to 4, then to 8, etc.) until the program runs successfully.
Alternatively, or in combination with the “Split database” option, consider the following options: reduce the number of variable modifications specified; reduce the range of allowed peptide length (from 7-50 to e.g. 7-35).
For users running the stand-alone version of MSFragger (i.e. not through FragPipe):  try allocating more memory using the `-Xmx` option. If not successful, please contact the developers for the stand-alone version of MSFragger with “Split database” option enabled.
Traceback (most recent call last):
  File "C:\Users\NMPALM~1\AppData\Local\Temp\38\fragpipe\msfragger_pep_split.py", line 447, in <module>
    main()
  File "C:\Users\NMPALM~1\AppData\Local\Temp\38\fragpipe\msfragger_pep_split.py", line 435, in main
    calibrate_mzBIN, params_txt_new = calibrate(fasta_path_sample, calibrate_mass)
  File "C:\Users\NMPALM~1\AppData\Local\Temp\38\fragpipe\msfragger_pep_split.py", line 349, in calibrate
    raise AssertionError(p)
AssertionError: <subprocess.Popen object at 0x000000FCE55546A0>
Process 'MsFragger' finished, exit code: 1

Process returned non-zero exit code, stopping
Crystal-C [Work dir: C:\TPP\data]
java -Dbatmass.io.libs.thermo.dir="C:\TPP\data\ext\thermo" -Xmx300G -cp "C:\Users\NMPALM~1\AppData\Local\Temp\38\fragpipe\batmass-io-1.17.1.jar;C:\Users\NMPALM~1\AppData\Local\Temp\38\fragpipe\grppr-0.3.23.jar;C:\Users\NMPALM~1\AppData\Local\Temp\38\fragpipe\original-crystalc-1.0.8.jar" crystalc.Run C:\TPP\data\crystalc-0-080120_NISTcrowBrain_JH25colNoTrp_mlpl12_60m_Slot1-38_1_653.pepXML.params C:\TPP\data\080120_NISTcrowBrain_JH25colNoTrp_mlpl12_60m_Slot1-38_1_653.pepXML

~~~~~~~~~~~~~~~~~~~~
Cancelling 7 remaining tasks
Processing interrupted, stopping Crystal-C

**Comment by magnuspalmblad** [comment]
[log-fragpipe-run-at_2020-01-21_17-40-13.log](https://github.com/Nesvilab/MSFragger/files/4109043/log-fragpipe-run-at_2020-01-21_17-40-13.log)

**Comment by fcyu** [comment]
Thanks. Looks like MSFragger crashed in the first search due to not enough memory. You mentioned that it worked well without calibration, which had on first search but only main search. But the first search is supposed to have a smaller search space. Could you please send us the `fragger.params`? I would like to figure out why the first search crashed but the main search didn't.

Thanks,

Fengchao

**Comment by anesvi** [comment]
Were we able to figure out the problem?

**Comment by magnuspalmblad** [comment]
Here are the parameters I am running right now. The same parameters but with calibration on (with or without optimization) runs out of memory, even when >300 GB is available.

[fragger.params.zip](https://github.com/Nesvilab/MSFragger/files/4118149/fragger.params.zip)

**Comment by fcyu** [comment]
Thanks for your `fragger.params`. After comparing this one with the log you sent last time, we found that `digest_min_length`, `digest_max_length`, `digest_mass_range_low`, and `digest_mass_range_high` are different.

The log from the crashed task has:
```
digest_min_length = 7
digest_max_length = 50
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
```

The parameter from the not crashed task has:
```
digest_min_length = 7
digest_max_length = 35
digest_mass_range_low = 700.0
digest_mass_range_high = 4500.0
```
Clearly, this one has a much smaller search space. Could you please double check your parameters and try mass calibration with today's `fragger.params` again?

Thanks,

Fengchao

**Comment by magnuspalmblad** [comment]
Hi Fengchao,

Many thanks for the fast feedback and help with MSFragger!

I'll try with the same peptide lengths, but the difference in search space can't be that large, since most tryptic peptides are shorter than 35 residues (and MSFragger limits the number of variable PTMs considered per peptide, so longer peptides with many variably modified sites are not an issue). 

Does the calibration to a preliminary search against the whole database to identify peptides to use as internal calibrants? If so, I suppose it would make sense to split the database the same way in this first-pass search?

Magnus

**Comment by fcyu** [comment]
The first search also uses a split database.

Best,

Fengchao

**Comment by fcyu** [comment]
No feedback.
