### ISSUE TITLE
Support for non-canonical amino acids

### ISSUE THREAD

**Issue by andytyk** [Nesvilab/MSFragger#6]
Add and verify support for non-canonical amino acids.

**Comment by plbaldoni** [comment]
Apologies for revisiting this old issue.

With the default parameters for closed search, is MSFragger expected to consider non-canonical amino acids during peptide identification? I was surprised to see a couple of peptides with selenocysteine being identified with the default parameters, and I just wanted to confirm that is

**Comment by plbaldoni** [comment]
Got it, thanks Fengchao.

**Comment by brunoalex7** [comment]
Hi. I'm new to Fragpipe, I was actually just testing with using a couple of samples in closed search.

I got a few warnings such as this one (for protein sequences containing U):

.WARNING: Found the following zero-mass residues in protein entry sp|O62768|TRXR1_BOVIN : U
MNGSKDLPEPYDYDLIIIGGGSGGLAAAKEAAKYDKKVMVLDFVTPTPLGTRWGLGGTCVNVGCIPKKLMHQAALLGQALRDSRNYGWNVEETVKHDWERMTEAVQNHIGSLNWGYRVALREKKVTYENAYGEFVGPHRIKATNNKGKEKIYSAERFLIATGERPRYLGIPGDKEYCISSDDLFSLPYCPGKTLVVGASYVALECAGFLAGIGLDVTVMVRSILLRGFDQDMANKIGEHMQEHGIKFIRQFVPIKVEQIEAGTPGR



I'm not sure whether this relates or not, but in the end I got a non-zero exit code:



.........:.........:.........:.........:.........:.........:.........:.WARNING: Found the following zero-mass residues in protein entry sp|Q9C0D9|EPT1_HUMAN : U
MAGYEYVSPEQLAGFDKYKYSAVDTNPLSLYVMHPFWNTIVKVFPTWLAPNLITFSGFLLVVFNFLLMAYFDPDFYASAPGHKHVPDWVWIVVGILNFVAYTLDGVDGKQARRTNSSTPLGELFDHGLDSWSCVYFVVTVYSIFGRGSTGVSVFVLYLLLWVVLFSFILSHWEKYNTGILFLPWGYDISQVTISFVYIVTAVVGVEAWYEPFLFNFLYRDLFTAMIIGCALCVTLPMSLLNFFRSYKNNTLKLNSVYEAMVPLFSPCLLFILSTAWILWSPSDILELHPRVFYFMVGTAFANSTCQLIVCQMSSTRCPTLNWLLVPLFLVVLVVNLGVASYVESILLYTLTTAFTLAHIHYGVRVVKQLSSHFQIYPFSLRKPNSDULGMEEKNIGL
........:.........:.........50000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........51000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........52000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........53000
.........:.........:.........:...  Total: 53334
Computing degenerate peptides for 5358 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Computing probabilities for 6103 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 6103 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 6103 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 6103 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 6103 proteins.  Loop 1: 0%...20%...40%...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Calculating sensitivity...and error tables...
INFO: mu=4.28628e-05, db_size=55241432
Computing MU for 6103 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
INFO[17:54:17] Done                                         
Process 'ProteinProphet' finished, exit code: 0
PhilosopherDbAnnotate [Work dir: E:\Fragpipe_searches\UniMS2022_71_MSilva_Fragpipe\Results]
C:\Users\UM124\Desktop\FragPipe-jre-19.1\fragpipe\tools\philosopher_v4.8.1_windows_amd64\philosopher.exe database --annotate E:\AB SCIEX\ProteinPilot Data\SearchDatabases\2023-05-02-decoys-UniMS50_51_Human+Bovine+Vaccinia+Contaminants.fasta.fas --prefix rev_
INFO[17:54:18] Executing Database  v4.8.1                   
INFO[17:54:18] Annotating the database                      
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
philosopher/lib/dat.ProcessUniProtKB({0xc000234351, 0xf}, {0xc002c6f5e0, 0xe0}, {_, _})
	/workspace/philosopher/lib/dat/db.go:237 +0x9ff
philosopher/lib/dat.(*Base).ProcessDB(0xc00018c360, {0xc0000cc100, 0x77}, {0xc000020100, 0x4})
	/workspace/philosopher/lib/dat/dat.go:149 +0x29c
philosopher/lib/dat.Run({{0xc00001c780, 0x24}, {0xc00001a480, 0x39}, {0xc000026640, 0x46}, {0xc000026690, 0x48}, {0xc00001a4c0, 0x3f}, ...})
	/workspace/philosopher/lib/dat/dat.go:68 +0x51a
philosopher/cmd.glob..func4(0x333d6e0?, {0x1740615?, 0x4?, 0x4?})
	/workspace/philosopher/cmd/database.go:23 +0x7e
github.com/spf13/cobra.(*Command).execute(0x333d6e0, {0xc000236200, 0x4, 0x4})
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x333c2c0)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/prvst/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
philosopher/cmd.Execute()
	/workspace/philosopher/cmd/root.go:35 +0x25
main.main()
	/workspace/philosopher/main.go:25 +0x90
Process 'PhilosopherDbAnnotate' finished, exit code: 2
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 5 remaining tasks




Can you help?
Thanks,
Bruno

**Comment by fcyu** [comment]
Hi @brunoalex7 , the error is not about MSFragger. It is from Philosopher. Could you send the issue to https://github.com/Nesvilab/philosopher/issues ?

Thanks,

Fengchao

**Comment by brunoalex7** [comment]
Sure.
Thanks,
Bruno
