### ISSUE TITLE
[Issue] MSFragger slurm job not using memory allocated by -Xmx 

### ISSUE THREAD

**Issue by clb21565** [Nesvilab/MSFragger#60]
Dear all, thank you for your hard work on this impressive tool. 

I am attempting to do a large open search using MSFragger on an institutional HPC. 
It is quite a large search, so I requested a lot of memory (-Xmx192g) 
However, when I submit a slurm job, the out-script says: 

RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 1.8.0_162, OpenJDK 64-Bit Server VM, Oracle Corporation
JVM started with 170 GB memory

note that the JVM started with less memory than what was requested by -Xmx option. Later, the jobs I submit consistently fail with an OOM error. 

So, two questions here- 
1) Why is this happening? is this expected behavior?
2) It is possible that the job I am submitting did not request enough memory. Is there a split option for the command line version of MSFragger? 

Cheers from VA.

**Comment by fcyu** [comment]
Thanks for your interest in MSFragger, JVM normally starts with a heap size smaller than the maximum size (the value behine -Xmx), and later, it increases if needed. That's why you see a smaller number in the printed message.

Your out-of-memory error implies that 192GB is not enough for your task. There is a split database function in FragPipe but not available standalone.

Best,

Fengchao

**Comment by anesvi** [comment]
We only make the Split version for Linux available to collaborators at the moment. But I hope we will release it soon.
Try reducing the allowed peptide length (from 50 to say 40), and remove variable modifications. You should not be specifying a lot of PTMs for open search.
Or are you doing open search with nonspecific digest? Those searches are very tricky…
Alexey

**Comment by fcyu** [comment]
@clb21565 Can you send an email to yufe@umich.edu? We will send you the split script.

Best,

Fengchao
