### ISSUE TITLE
How to search AspN digested samples

### ISSUE THREAD

**Issue by chscho** [Nesvilab/MSFragger#66]
Hi there

I'm trying to search samples digested with AspN using MSFragger. But since there is only the option to define the aminoacid AFTER which the enzyme should cut, I'm kind of stuck, since I'd like to set it to "before D". Am I missing something, or how would I need to set up such a search?

Thanks!
ChScho

**Comment by fcyu** [comment]
Hi @chscho ,

Thanks for your interest in MSFragger. Unfortunately, MSFragger doesn't support N-terminal enzyme. We will add this function in the future.

Best,

Fengchao
