### ISSUE TITLE
fragment mass tolerance

### ISSUE THREAD

**Issue by kevinkovalchik** [Nesvilab/MSFragger#68]
Hello,

I'm seeing something strange with the fragment mass tolerance parameter and I'm wondering if it is a bug or intentional.

I am passing MSFragger (v2.4) a parameter file with the following (truncated):
```
num_threads = 8
database_name = /data/Analysis/eLife_systemhc/2020-03-19-decoys-contam-uniprot-human-20200319.fasta
precursor_mass_lower = -15
precursor_mass_upper = 15
precursor_mass_units = 1
precursor_true_tolerance = 15
precursor_true_units = 1
fragment_mass_tolerance = 0.5
fragment_mass_units = 0
calibrate_mass = 1
```
But what MSFragger prints to the terminal at startup is this:
```
MSFragger version MSFragger-2.4
Batmass-IO version 1.17.4
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Linux, Architecture: amd64
Java Info: 11.0.6, OpenJDK 64-Bit Server VM, Ubuntu
JVM started with 20 GB memory
Deisotoping doesn't support low resolution tandem mass spectra. Turning it off. Done
Checking /data/Analysis/eLife_systemhc/Data/Jurkat_Oxford/Jurkat_Oxford_TT0236a_DDA_MHC-I_Jurkat_iRT.mzXML...
***********************************FIRST SEARCH************************************
Parameters:
num_threads = 8
database_name = /data/Analysis/eLife_systemhc/2020-03-19-decoys-contam-uniprot-human-20200319.fasta
decoy_prefix = rev_
precursor_mass_lower = -15.0
precursor_mass_upper = 15.0
precursor_mass_units = 1
precursor_true_tolerance = 15.0
precursor_true_units = 1
fragment_mass_tolerance = 500.0
fragment_mass_units = 1
```
So 0.5 Da is being translated to 500 ppm. I have tried changing this value to 0.7 Da, and it gets translated to 700 ppm. Is this intentional? If so, why?

Thanks!
Kevin

**Comment by fcyu** [comment]
Hi Kevin,

Thanks for your interest in MSFrager. Yes, it is intentional. Because in the mass calibration, we use ppm for fragment mass tolerance.

Best,

Fengchao

**Comment by kevinkovalchik** [comment]
Okay, I guess assuming the average peptide is 1000 Da that makes sense. You haven't found using ppm instead of a fixed width causes any issues with data from say quadrupoles or ion traps?

**Comment by fcyu** [comment]
For low resolution MS/MS (quadrupoles or ion traps), it should be fine according to our test, and in the parameter optimization step, you will see that the candidate fragment tolerances are also adjusted (i.e., 100, 200, 300, 400, 500 ppm).

Best,

Fengchao
