### ISSUE TITLE
PeptideProphet or DB error

### ISSUE THREAD

**Issue by ykim7263** [Nesvilab/MSFragger#72]
I have an issue from peptideProphet step.
It keeps showing the error described below, when I use the specific DB.
When I use the DB downloaded from Uniprot, it works. But as long as I use the different database that is constructed manually, It shows the error. 

INFO: Processing standard MixtureModel ... 
Initialising statistical models ...
Iterations: .........10.........20.....WARNING: Mixture model quality test failed for charge (1+).
..
WARNING: Mixture model quality test failed for charge (2+).
WARNING: Mixture model quality test failed for charge (3+).
WARNING: Mixture model quality test failed for charge (4+).
WARNING: Mixture model quality test failed for charge (5+).
WARNING: Mixture model quality test failed for charge (6+).
WARNING: Mixture model quality test failed for charge (7+).
model complete after 28 iterations

**Comment by fcyu** [comment]
Thanks for your interest in our tools. Can you help to check if your database has decoys and the decoys' prefix matches what you gave to PeptideProphet?

Best,

Fengchao

**Comment by ykim7263** [comment]
Yes it does include decoys' prefix DB (Achieved the decoy sequence with
prefix from OPEN MS)

Best,
Kim

**Comment by ykim7263** [comment]
FYI, Both DBs that I used were obtained decoy prefix from the same
software. But only one of them is working.

Best,
Kim

**Comment by fcyu** [comment]
Looks like there is something related to your custom database. Maybe it's not suitable for your data.

**Comment by ykim7263** [comment]
The DB I am using was used with different software such as Proteome
Discoverer.

**Comment by chhh** [comment]
Can you share the "broken" db with us?

**Comment by ykim7263** [comment]
genes.fasta
<https://drive.google.com/file/d/1keFeVxLijJXp7BImL4Tk5zQtDZt5TZvZ/view?usp=drive_web>

**Comment by fcyu** [comment]
Hi @ykim7263 ,

I see your files are 274 MB with 416702 proteins (including decoys). Failure of PeptideProphet's modeling could be any reasons, which is really difficult to investigate. I think we cannot give you a quick solution with a reasonable period of time. I will close this issue if @chhh and @anesvi have no objection.

**Comment by ykim7263** [comment]
Thank you for your response

I have smaller size of DB which has a fifth size of previous one. Can you
investigate with that ?

Best
Kim

**Comment by fcyu** [comment]
Hi Kim,

That's not entirely related to the database size. As I said, the reason can be anything related to the score distributions of PSMs. You can try with your database to see if the modelling fails. 

Best,

Fengchao
