### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by jgmeyerucsd** [Nesvilab/MSFragger#75]
I'm getting the error referenced in the title when trying to run open search. Is this related to the data having low resolution MS2? The same files run fine in closed search.

I am using msfragger 2.4 and philosopher 3.2.3 in fragpipe 12.1. 

 See the attached logfile and params, and find an example file here:
https://drive.google.com/file/d/1jtITrCZ0Y8YlbKJzqbNu3gheyFvMfKbn/view?usp=sharing

Thanks in advance for your help. 

[log-fragpipe-run-at_2020-05-14_08-56-32.log](https://github.com/Nesvilab/MSFragger/files/4628903/log-fragpipe-run-at_2020-05-14_08-56-32.log)
[fragpipe_2020-05-14_08-31-07.config.txt](https://github.com/Nesvilab/MSFragger/files/4628907/fragpipe_2020-05-14_08-31-07.config.txt)
[shepherd.config.txt](https://github.com/Nesvilab/MSFragger/files/4628909/shepherd.config.txt)
[fragger.params.txt](https://github.com/Nesvilab/MSFragger/files/4628910/fragger.params.txt)

**Comment by fcyu** [comment]
Hi Jesse,

It's out of memory. I am sorry that I think there is not much we can do. BTW, low resolution MS2 is not recommended in open search.

Best,

Fengchao

**Comment by jgmeyerucsd** [comment]
Thanks for the quick reply, I'll inform my collaborators.
