### ISSUE TITLE
Open Search with a custom modification

### ISSUE THREAD

**Issue by wzhao6898** [Nesvilab/MSFragger#8]
# Describe the problem
Setting up an open search with a custom modification in our samples labeled with our probe of 196.2 on Lysine (variable).

* **I'm submitting a:**
  - [ ] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [x] question

* **My MSFragger use case:**
  - [ ] _Closed_ search (standard small precursor mass tolerance)
  - [x] _Open_ search (large precursor mass tolerance)

 We'd like to search for any PTM, such methox, acetylation, phosphorylation variable modifications that occur when the peptide is labeled by our probe. How should I set up the search parameters?
Here are some settings we tried:

precursor_mass_tolerance = 200.00
precursor_mass_units = 0               # 0=Daltons, 1=ppm
...
variable_mod_01 = 15.9949 M
variable_mod_02 = 42.0106 [^
variable_mod_03 = 79.96633 STY
variable_mod_04 = 42.0106 K
variable_mod_05 = 196.2 K
...
precursor_charge = 2 5
override_charge = 1

## System info

You can find that printed on the _Config_ tab.
- OS and version: Windows 7 64bit with 24 GB ram 8 cpu
- Java version: 1.8.61

----

### Genral proteomics experiment description
Human, full cell lysate label with our probe digested with Trypsin

**Comment by fcyu** [comment]
You can observe big massdiff in some "search_hit" tags. After post-processed by Philosopher, there are more informative information in psm.tsv, ion.tsv peptide.tsv, and protein.tsv. You may check those files.

Thanks,

Fengchao
