### ISSUE TITLE
Search peptide modifications

### ISSUE THREAD

**Issue by Wenhhao** [Nesvilab/MSFragger#80]
Hello,

I am interested in searching peptide modifications and run a **Open Search**. But there is no increasing of **Modified Peptide** in **psm.tsv** file, compared with **Closed Search**.

Should I add every variable modification by myself? And is **Open Search** better than **Closed Search** for me?

Best regards,
Wenhhao

**Comment by fcyu** [comment]
Hi Wenhhao,

The unknown modifications found by open search are not the same as variable modifications which will be listed in `Modified Peptide` and `Assigned Modifications`. You can find them by checking the delta mass. You can also check the result from PTM-Shepherd (`*.modsummary.tsv` and `*.profile.tsv`) for those modifications.

You don't need to add every modification, which is also almost impossible.

You may need to read some literature regarding the open search and its possible applications. We normally only answer questions regarding using our tools here.

Best,

Fengchao
