### ISSUE TITLE
Peptide digest_max_length fixed in nonspecific search

### ISSUE THREAD

**Issue by DongElkan** [Nesvilab/MSFragger#82]
I tried to perform nonspecific search using MSFragger 3.0. Due to limited memory, peptide length generated by theoretical digestion was limited during each search, e.g., 7-12, 13-20, 21-30. But seems MSFragger limited the `digest_max_length` to be 15 internally, so if I set the range to be 21-30, errors were raised.
The parameter printed in command line related to this:
`digest_min_length = 21`
`digest_max_length = 15`

Errors:
`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at edu.umich.andykong.msfragger.n.a(Unknown Source)
        at edu.umich.andykong.msfragger.A.<init>(Unknown Source)
        at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
        at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
        ... 6 more`

Any solution for this?

**Comment by fcyu** [comment]
Thanks for your interest in our tools. The 15 maximum length limitation is applied to the first search. For your case, you need to turn off the mass calibration. You can also try the split database option in the FragPipe, which can automatically split your fasta file into multiple (the number is dependent on your setting), search them sequentially, and combine the results.
 
Best,

Fengchao

**Comment by DongElkan** [comment]
> Thanks for your interest in our tools. The 15 maximum length limitation is applied to the first search. For your case, you need to turn off the mass calibration. You can also try the split database option in the FragPipe, which can automatically split your fasta file into multiple (the number is dependent on your setting), search them sequentially, and combine the results.
> 
> Best,
> 
> Fengchao

Hi Fengchao,

Thanks for your reply. I will try turning calibration off.
For FragPipe, I encountered a problem actually. Once I set up everything according to FragPipe's instruction, and run MSFragger, the interface froze without showing any error. This means it doesn't run the search, and also raise any message. So I changed the search in command line. I run FragPipe on Windows 10.

Best,

**Comment by fcyu** [comment]
Are you using the latest FragPipe? If so, could you click `Clear Cache and Close` and try again? If the issue is still there, could you send the screenshot to us?

Thanks,

Fengchao

**Comment by DongElkan** [comment]
> Are you using the latest FragPipe? If so, could you click `Clear Cache and Close` and try again? If the issue is still there, could you send the screenshot to us?
> 
> Thanks,
> 
> Fengchao

After `Clear Cache and Close`, seems normal now. Thanks.

**Comment by DongElkan** [comment]
After performing the suggestions, everything now runs well. I think all these should be well documented. It will be confusing to set defaulted parameters `digest_min_length=7` and `digest_max_length=25`, but not supported when running the software if the user don't know that tip, neither mentioned in the error message raised.
