### ISSUE TITLE
Open Search PTM analysis

### ISSUE THREAD

**Issue by Andreas-MPIbpc** [Nesvilab/MSFragger#85]
Dear MSFragger team,

I was wondering if there is a link between the reported results in global.modsummary.tsv after performing an Open Search for PTM analysis and the actual identified peptides (and the AA carrying the potential modification)?
Thanks in advance!

Best,
Andreas

**Comment by anesvi** [comment]
PTM-Shepherd takes as input PSM.tsv files. So you can find all PSMs with mass shifts corresponding to each mass shift reported in the PTM-Shepherd files (note: the summary file combines the isotopes; so it may be easier to compare with global.profile.tsv)

Also, MSFragger generates *.TSV files. There, you can find the localization info for each PSM (indicated with a small letter). Also, the best score with the mass shift placed somewhere on the peptide, and without. Often, it is not possible to localize (e.g. for labile modifications). Note that PTM-Shepherd is doing its own localization step, however it uses the same method as MSFragger. So the results reported in *.TSV should be similar to the localization results produced by PTM-Shepherd for each individual PSM.

Perhaps Danny can add more. And we need to explain this better somewhere….

Best
Alexey

**Comment by Andreas-MPIbpc** [comment]
Thanks for the fast response, Alexey.
Okay, comparing the global.profile.tsv output with the one of psm.tsv based on the delta masses. However, AA are only highlighted for the pre-configured modifications (e.g. oxidation of M). Anyway, that's a good start!

Best,
Andreas

**Comment by anesvi** [comment]
We talked about propagating localization from *.TSV to PSM file, but have not done it yet.
You have to do it ‘manually’ for now.
Alexey

**Comment by danielgeiszler** [comment]
Hi Andreas,

For more information about the .modsummary and .profile tables produced by PTM-Shepherd, you can check out the wiki:

https://github.com/Nesvilab/PTM-Shepherd/wiki/3.-Output

**Comment by Andreas-MPIbpc** [comment]
Thank you very much!

Best,
Andreas
