### ISSUE TITLE
mzXML file error

### ISSUE THREAD

**Issue by mikl93** [Nesvilab/MSFragger#89]
We have MSFragger with PD installed. We are wanting to run some data that we do not have the raw files for, just the mzXML files. 
The magellan log gives me this:
Could not find instrument ID attribute. Should be <msInstrument msInstrumentID='xxx'> or <msInstrument id='xxx'> 

The other error I sometimes get is that the spectrum number does not match. Is there a way to get around these?

I had previously had been suggested on here to convert them to mzML files but that didn't fix the error.

**Comment by fcyu** [comment]
It is very likely that your mzXML files do not follow the schema strictly. Can you tell how they are converted?

**Comment by mikl93** [comment]
We did not convert them ourselves. Are there specific things in the file or file header that need to be there or formatted in a certain way for MSFragger to work?

**Comment by fcyu** [comment]
MSFragger has no special requirement regarding mzXML file format. My guess is that your file does not follow mzXML schema well. Could you try to convert your mzXML to a new mzXML using msconvert from ProteoWizard (http://proteowizard.sourceforge.net/download.html)?
