### ISSUE TITLE
N-terminal cleavage sites

### ISSUE THREAD

**Issue by JB91451** [Nesvilab/MSFragger#90]
Dear all,

Today I realized that the current way to specify digestion enzymes hardly allows for N-terminal cleaving proteases? For instance the usage of LysN would require to define all amino acids as cleavage sites (search_enzyme_cutafter) and than putting all but lysine to the restriction list (search_enzyme_butnotbefore). I think it would be nice to have a more direct way for that in a future release if it is possible (i.e. additional parameters search_enzyme_cutbefore & search_enzyme_butnotafter).

Best regards,
Juergen

**Comment by fcyu** [comment]
Hi Juergen,

Yes, we are aware of that and it is in our waiting list. Since there is already a issue (https://github.com/Nesvilab/MSFragger/issues/9) about it, I will close this one.

Thanks,

Fengchao
