### ISSUE TITLE
Error: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by PatrickvanZalm** [Nesvilab/MSFragger#92]
Good day to you all,

I have been trying to run some .d TIMSTOF data (human, trypsin samples) using MSFragger, however, I have had this error come up every time. I have played around with splicing the same (10 up to 20) but this gave no luck.

Database was downloaded using the code below in the Philosopher command prompt. The database file is located in the C drive, while the .d files are located on another drive.
philosopher database --id UP000005640 --reviewed --contam --isoform

Added the rest of execution log in the attached file.
[MSfragger_Error.txt](https://github.com/Nesvilab/MSFragger/files/5091037/MSfragger_Error.txt)

I am not fully sure what this error means. Could you perhaps shed some light?

Best,
Patrick 

Checking database...
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 261
	at edu.umich.andykong.msfragger.O.a(Unknown Source)
	at edu.umich.andykong.msfragger.O.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Traceback (most recent call last):
  File "C:\Users\Tidus\Desktop\fragpipe\tools\msfragger_pep_split.py", line 472, in <module>
    main()
  File "C:\Users\Tidus\Desktop\fragpipe\tools\msfragger_pep_split.py", line 461, in main
    run_msfragger(calibrate_mzBIN if calibrate_mass in [1, 2] else infiles_name)
  File "C:\Users\Tidus\Desktop\fragpipe\tools\msfragger_pep_split.py", line 149, in run_msfragger
    subprocess.run(list(map(os.fspath, cmd)), cwd=cwd, check=True)
  File "C:\Users\Tidus\anaconda3\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\Tidus\\Desktop\\fragpipe\\jre\\bin\\java.exe', '-jar', '-Dfile.encoding=UTF-8', '-Xmx20G', 'C:\\Users\\Tidus\\Desktop\\fragpipe\\MSFragger-3.0\\MSFragger-3.0.jar', 'fragger.params', 'F:\\Anais\\TimsTOF_HumanThymus_Msfragger\\split_peptide_index_tempdir\\2020-03-06_AM_T1_Slot1-36_1_475.mzBIN_calibrated', '--partial', '0']' returned non-zero exit status 1.
Process 'MsFragger' finished, exit code: 1
Process returned non-zero exit code, stoppingMsFragger
C:\Users\Tidus\Desktop\fragpipe\jre\bin\java.exe -cp C:\Users\Tidus\Desktop\fragpipe\lib\fragpipe-13.0.jar com.github.chhh.utils.FileMove F:\Anais\Raw_Files_TimsTOF_90mingrad_25cmIonopticksCSIcol\2020-03-06_AM_T1_Slot1-36_1_475.pepXML F:\Anais\TimsTOF_XXX_Msfragger\2020-03-06_AM_T1_Slot1-36_1_475\2020-03-06_AM_T1_Slot1-36_1_475.pepXML

**Comment by fcyu** [comment]
I cannot reproduce this error with my own data. Can you send us yours? I can create a link for you to upload.

Best,

Fengchao

**Comment by PatrickvanZalm** [comment]
I will have to ask my colleague (perhaps it is patient sensitive). I will get back to you shortly.

**Comment by PatrickvanZalm** [comment]
Dear Fengchao,

I can send you a pooled sample file (same error occurs). Please let me know which files you'd like.

Best,
Patrick

**Comment by fcyu** [comment]
Hi Patrick,

Any file is good as long as it can reproduce the error.

Thanks,

Fengchao

**Comment by PatrickvanZalm** [comment]
Alright. I can do that yes.

**Comment by fcyu** [comment]
Hi @PatrickvanZalm ,

Sounds great! Could you please upload your files here (https://umich.app.box.com/f/f52a9664f79147a4a8ba365b5db9dae0)?

Thanks,

Fengchao

**Comment by PatrickvanZalm** [comment]
Dear Fengchao,

I have uploaded a .rar file, in it the following:
- .d folder that I used and got an error from
- WORKFLOW file
- database I used.

Let me know if any addiotonal data is required. 

I run on an (older) 32GB RAM computer if that is of any importance.

**Comment by fcyu** [comment]
Hi @PatrickvanZalm ,

Looks like you put `variable_mod_06 = 114.04290 Acetylation 1` to MSFragger's variable modification setting, which does not follow the format. It only takes `<mass><residue><count>`.

Best,

Fengchao

**Comment by PatrickvanZalm** [comment]
Dear Fengchauo,

Thank you for your help, your suggestions seemed to have done the trick. It has been running good since (still waiting on results, large number of files and a slow computer).

Best,
Patrick
