### ISSUE TITLE
Where do I find # of MS/MS and # of PSM from FragPipe output file?

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/MSFragger#94]
Greetings,

I am evaluating the assignment percentage (# of PSM/# of MS/MS) between CloseSearch and OpenSearch using FragPipe. I am only able to identify the # of PSMs (I am unsure if that is the right number I am looking at - there are multiple PSM #) but not able to find the # of MS/MS. I have provided a snap-shoot of all the output files provided by FragPipe in this thread.

Please do tell me where I am find the required numbers.

Lastly, I would like to thank you in advance for your assistance.

Regards, Samy

![FragPipe_Output_Files](https://user-images.githubusercontent.com/69944967/91673734-dd529080-eb78-11ea-817e-7340189bed7b.JPG)

**Comment by fcyu** [comment]
Thanks for your interest in our tools. I think the PSM number equals the MS/MS number after FDR filtering in your case.

The filter.log contains the numbers from two steps of the filtering. Entries in psm.tsv, ion.tsv, peptide.tsv, and protein.tsv are filtered at 1% PSM and protein FDR.

Best,

Fengchao

**Comment by BenSamy2020** [comment]
Greetings fcyu,

Thank you for your prompt reply. 

I am looking for the total number of MS/MS in my raw file (Counting MS2 scans for dataset default-ptmshepherd-dataset). For OpenSearch I am able to find from the output file named: log_2020-08-31_11-17-29 that contains the MS/MS (MS2) count. But for CloseSearch, I am not able to find the MS/MS (MS2) count. I have highlighted the MS/MS number that I can find from my OpenSearch file but in my CloseSearch file. Please refer to image.

Regards,
Ben

![FragPipe_OpenSearch](https://user-images.githubusercontent.com/69944967/91678760-bf415c00-eb89-11ea-9d9d-68cdbbf35f8e.JPG)
![FragPipe_CloseSearch](https://user-images.githubusercontent.com/69944967/91678764-c1a3b600-eb89-11ea-9b0c-e303e5a621bd.JPG)

**Comment by fcyu** [comment]
If you are looking for the number of MS/MS **after** FDR filtering, the number of PSMs equals to that. So, the line with info 'Converged to 0.xx % FDR with xxxxx PSMs' is what you need.

If you are looking for the total MS/MS from your data, the message from MSFragger has that info. The line looks like '[progress: 41808/**41808** (100%) - 6356 spectra/s] 6.6s | postprocessing 4.6 s' where 41808 is the total MS/MS number used in searching.

Best,

Fengchao
