### ISSUE TITLE
a/z ions

### ISSUE THREAD

**Issue by sbollings** [Nesvilab/MSFragger#98]
Hello,

Are a and z ions supported? A modification I am interested in promotes the generation of a and z ions and I am wondering if there is a way to incorporate them in my search?

Best,
Sarah

**Comment by fcyu** [comment]
Hi Sarah,

Yes, you can set ion series in 'Fragment ion series' from MSFragger tab in FragPipe:
![image](https://user-images.githubusercontent.com/6926299/93146954-27ca2600-f6be-11ea-92fa-6b40f9145d9f.png)

Best,

Fengchao
